---
permalink: cloud-connector/backup-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector backup 
summary: 您可以存取SANtricity 位於畫面左側瀏覽面板中的備份選項、以取得有關的資訊。備份選項會顯示「備份」頁面、可讓您建立新的映像型或檔案型備份工作。 
---
= 使用 SANtricity Cloud Connector 來建立和管理 E 系列 Volume 備份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以存取SANtricity 位於畫面左側瀏覽面板中的備份選項、以取得有關的資訊。備份選項會顯示「備份」頁面、可讓您建立新的映像型或檔案型備份工作。

請使用SANtricity 《E*Cloud Connector》應用程式的「*備份*」頁面來建立及處理E系列磁碟區的備份。您可以建立映像型或檔案型備份、然後立即或稍後執行這些作業。此外、您也可以選擇根據上次執行的完整備份來執行完整備份或遞增備份。根據上次透過SANtricity NetApp Cloud Connector應用程式執行的完整備份、最多可執行六個遞增備份。


NOTE: 所有備份與還原工作的時間戳記、都會SANtricity 使用本地時間。



== 建立新的映像型備份

您可以透過SANtricity 「ImageCloud Connector」應用程式備份頁面上的「Create」（建立）功能、建立新的映像型備份。

.開始之前
請務必將Web Services Proxy中的儲存陣列登錄至SANtricity 《解決方案與解決方案與解決方案：

.步驟
. 在「備份」頁面中、按一下「*建立*」。
+
隨即顯示Create Backup（建立備份）視窗。

. 選取*建立映像型備份*。
. 單擊 * 下一步 * 。
+
可用的E系列磁碟區清單會顯示在Create Backup（建立備份）視窗中。

. 選取所需的E系列磁碟區、然後按一下*「Next（下一步）」*。
+
此時將顯示Create Backup（創建備份）確認窗口的* Name the Backup and化a description*（命名備份並提供說明*）頁面。

. 若要修改自動產生的備份名稱、請在*工作名稱*欄位中輸入所需的名稱。
. 如有需要、請在「*工作說明*」欄位中新增備份說明。
+

NOTE: 您應該輸入工作說明、以便輕鬆識別備份內容。

. 單擊 * 下一步 * 。
+
所選映像型備份的摘要會顯示在「Create Backup」（建立備份）視窗的「* Review Backup information*」（*檢閱備份資訊*）頁面下方。

. 檢閱選取的備份、然後按一下「*完成*」。
+
隨即顯示Create Backup（建立備份）視窗的確認頁面。

. 選取下列其中一個選項：
+
** * Yes *（是）-針對所選備份開始完整備份。
** *否*：不會執行所選映像型備份的完整備份。
+

NOTE: 您可以稍後透過備份頁面上的執行功能、執行所選映像型備份的完整備份。



. 按一下「*確定*」。
+
所選E系列磁碟區的備份隨即啟動、工作狀態會顯示在「備份」頁面的「結果清單」區段下方。





== 建立新的資料夾/檔案型備份

您可以透過SANtricity 位於「還原Cloud Connector」應用程式備份頁面的「Create」（建立）功能、建立新的資料夾/檔案型備份。

.開始之前
請務必將Web Services Proxy中的儲存陣列登錄至SANtricity 《解決方案與解決方案與解決方案：

檔案型備份會無條件備份您指定檔案系統上的所有檔案。不過、您可以選擇性地還原檔案和資料夾。

.步驟
. 在「備份」頁面中、按一下「*建立*」。
+
隨即顯示Create Backup（建立備份）視窗。

. 選取*建立資料夾/檔案型備份*。
. 單擊 * 下一步 * 。
+
「Create Backup（建立備份）」視窗中會顯示包含可供備份之檔案系統的磁碟區清單。

. 選取所需的Volume、然後按一下*「Next（下一步）」*。
+
所選磁碟區上的可用檔案系統清單會顯示在Create Backup（建立備份）視窗中。

+

NOTE: 如果檔案系統未出現、請確認SANtricity 支援的檔案系統類型是否為《支援此功能的原因之一：如需詳細資訊、請參閱 link:learn-intro-concept.html#supported-file-systems["支援的檔案系統"]。

. 選取包含要備份之資料夾或檔案的所需檔案系統、然後按一下*「下一步*」。
+
此時將顯示Create Backup（創建備份）確認窗口的* Name the Backup and化a description*（命名備份並提供說明*）頁面。

. 若要修改自動產生的備份名稱、請在*工作名稱*欄位中輸入所需的名稱。
. 如有需要、請在「*工作說明*」欄位中新增備份說明。
+

NOTE: 您應該輸入工作說明、以便輕鬆識別備份內容。

. 單擊 * 下一步 * 。
+
所選資料夾/檔案型備份的摘要會顯示在「Create Backup」（建立備份）視窗的「* Review Backup information*」（檢閱備份資訊*）頁面下方。

. 檢閱選取的資料夾/檔案型備份、然後按一下「*完成*」。
+
隨即顯示Create Backup（建立備份）視窗的確認頁面。

. 選取下列其中一個選項：
+
** * Yes *（是）-針對所選備份開始完整備份。
** *否*：不會執行所選備份的完整備份。
+

NOTE: 您也可以稍後透過備份頁面上的執行功能、執行所選檔案型備份的完整備份。



. 按一下 * 關閉 * 。
+
所選E系列磁碟區的備份隨即啟動、工作狀態會顯示在「備份」頁面的「結果清單」區段下方。





== 執行完整和遞增備份

您可以透過備份頁面上的執行功能執行完整和遞增備份。遞增備份僅適用於檔案型備份。

.開始之前
請確定您已透過SANtricity 《Sfor the Sure Cloud Connector（英文）」建立備份工作。

.步驟
. 在備份索引標籤中、選取所需的備份工作、然後按一下*執行*。
+

NOTE: 只要選取映像型備份工作或備份工作、而不選取先前執行的初始備份、就會自動執行完整備份。

+
隨即顯示Run Backup（執行備份）視窗。

. 選取下列其中一個選項：
+
** *完整*：備份所選檔案型備份的所有資料。
** *遞增*-備份自上次執行備份後所做的變更。
+

NOTE: 根據上次透過SANtricity NetApp Cloud Connector應用程式執行的完整備份、最多可執行六個遞增備份。



. 按一下「*執行*」。
+
備份要求即會啟動。





== 刪除備份工作

刪除功能會刪除所選備份與備份集所在之指定目標位置的備份資料。

.開始之前
請確定備份狀態為「已完成」、「失敗」或「已取消」。

.步驟
. 在「備份」頁面中、選取所需的備份、然後按一下「*刪除*」。
+

NOTE: 如果選取要刪除的完整基礎備份、則所有相關的遞增備份也會一併刪除。

+
隨即顯示「Confirm Delete（確認刪除）」視窗。

. 在*類型刪除*欄位中、輸入「刪除」以確認刪除動作。
. 按一下*刪除*。
+
選取的備份隨即刪除。


