---
permalink: cloud-connector/restore-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector restore, 
summary: 您可以存取SANtricity 位於畫面左側瀏覽面板中的還原選項、以取得有關的資訊。「還原」選項會顯示「還原」頁面、可讓您建立新的映像型或檔案型還原工作。 
---
= 在 SANtricity Cloud Connector 中建立新的映像型或檔案型還原
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以存取SANtricity 位於畫面左側瀏覽面板中的還原選項、以取得有關的資訊。「還原」選項會顯示「還原」頁面、可讓您建立新的映像型或檔案型還原工作。

利用職務概念來執行E系列Volume的實際還原。SANtricity在執行還原之前、您必須先識別要用於作業的E系列磁碟區。在您新增E系列Volume以還原SANtricity 至支援此功能的支援中心主機之後、您可以使用SANtricity 支援此功能的「還原」頁面來建立及處理還原作業。


NOTE: 所有備份與還原工作的時間戳記、都會SANtricity 使用本地時間。



== 建立新的映像型還原

您可以透過SANtricity 「還原」頁面上的「Create」（建立）功能、建立以映像為基礎的新還原。

.開始之前
請務必透過SANtricity ImageCloud Connector取得映像型備份。

.步驟
. 在「還原」頁面的SANtricity 「還原Cloud Connector」應用程式中、按一下「*建立*」。
+
此時會顯示還原視窗。

. 選取所需的備份。
. 單擊 * 下一步 * 。
+
「還原」視窗中會顯示「選取備份點」頁面。

. 選取所需的完整備份。
. 單擊 * 下一步 * 。
+
「還原」視窗中會顯示「選取還原目標」頁面。

. 選取還原磁碟區、然後按一下*「下一步*」。
+
「檢閱」頁面會顯示在「還原」視窗中。

. 檢閱選取的還原作業、然後按一下「*完成*」。
+
所選目標主機磁碟區的還原隨即啟動、工作狀態會顯示在「還原」頁面的「結果清單」區段中。





== 建立新的檔案型還原

您可以透過SANtricity 「還原」頁面中的「Create」（建立）功能、建立以檔案為基礎的新還原。

.開始之前
請務必透過SANtricity 《支援檔案的解決方案：

.步驟
. 在「還原」頁面的SANtricity 「還原Cloud Connector」應用程式中、按一下「*建立*」。
+
此時會顯示還原視窗。

. 在「還原」視窗中、選取所需的檔案型備份。
. 單擊 * 下一步 * 。
+
「選取備份點」頁面會顯示在「建立還原工作」視窗中。

. 在Select Backup Point（選擇備份點）頁面中、選取所需的完整備份。
. 單擊 * 下一步 * 。
+
「還原」視窗中會顯示可用的檔案系統或資料夾/檔案頁面清單。

. 選取要還原的資料夾或檔案、然後按「*下一步*」。
+
「還原」視窗中會顯示「選取還原目標」頁面。

. 選取還原磁碟區、然後按一下*「下一步*」。
+
「檢閱」頁面會顯示在「還原」視窗中。

. 檢閱選取的還原作業、然後按一下「*完成*」。
+
所選目標主機磁碟區的還原隨即啟動、工作狀態會顯示在「還原」頁面的「結果清單」區段中。





== 刪除還原

您可以使用「刪除」功能、從「還原」頁面的「結果清單」區段中刪除選取的還原項目。

.開始之前
請確定還原工作的狀態為「已完成」、「失敗」或「已取消」。

.步驟
. 在「還原」頁面中、按一下「*刪除*」。
+
隨即顯示「Confirm Delete（確認刪除）」視窗。

. 在*類型刪除*欄位中、輸入「刪除」以確認刪除動作。
. 按一下*刪除*。
+

NOTE: 您無法刪除暫停的還原。

+
選取的還原即會刪除。


