---
permalink: config-linux/iscsi-configure-array-side-network-task.html 
sidebar: sidebar 
keywords: configure iSCSI networking, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 在陣列端設定iSCSI網路。 
---
= 設定陣列端的網路
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用SANtricity 支援支援系統的圖形使用者介面、在陣列端設定iSCSI網路。

.您需要的是 #8217 ；需要的是什麼
* 其中一個儲存陣列控制器的IP位址或網域名稱。
* System Manager GUI、角色型存取控制（RBAC）或LDAP的密碼、以及為儲存陣列的適當安全存取設定的目錄服務。如SANtricity 需存取管理的詳細資訊、請參閱《支援系統》線上說明。


本工作說明如何從System Manager的「Hardware（硬體）」頁面存取iSCSI連接埠組態。您也可以從功能表：系統[設定>設定iSCSI連接埠]存取組態。

.步驟
. 在瀏覽器中輸入下列URL：「+https://<DomainNameOrIPAddress>+`」
+
「IPAddress」是其中一個儲存陣列控制器的位址。

+
第一次SANtricity 在尚未設定的陣列上開啟時、會出現「Set Administrator Password（設定管理員密碼）」提示字元。角色型存取管理可設定四種本機角色：管理、支援、安全性及監控。後三個角色的隨機密碼是無法猜測的。設定管理員角色的密碼之後、您可以使用管理員認證來變更所有密碼。如需四個本機使用者角色的詳細資訊、請參閱SANtricity 《支援系統》使用者介面中的線上說明。

. 在Set Administrator Password（設定管理員密碼）和Confirm Password（確認密碼）欄位中輸入管理員角色的System Manager密碼、然後按一下* Set Password（設定密碼）*。
+
如果未設定集區、磁碟區群組、工作負載或通知、則會啟動設定精靈。

. 關閉設定精靈。
+
稍後您將使用精靈來完成其他設定工作。

. 選取*硬體*。
. 如果圖形顯示磁碟機、請按一下*顯示磁碟櫃背面*。
+
圖形會變更、以顯示控制器而非磁碟機。

. 按一下要設定iSCSI連接埠的控制器。
+
此時會出現控制器的內容功能表。

. 選取*設定iSCSI連接埠*。
+
此時將打開Configure iSCSI Portes（配置iSCSI端口）對話框。

. 在下拉式清單中、選取您要設定的連接埠、然後按一下「*下一步*」。
. 選取組態連接埠設定、然後按一下「*下一步*」。
+
若要查看所有連接埠設定、請按一下對話方塊右側的*顯示更多連接埠設定*連結。

+
|===
| 連接埠設定 | 說明 


 a| 
已設定乙太網路連接埠速度
 a| 
選取所需的速度。下拉式清單中顯示的選項取決於網路可支援的最大速度（例如10 Gbps）。


NOTE: 控制器上提供的選購25GB iSCSI主機介面卡不會自動交涉速度。您必須將每個連接埠的速度設定為10 GB或25 GB。所有連接埠都必須設定為相同的速度。



 a| 
啟用IPV4 /啟用IPv6
 a| 
選取一個或兩個選項、以啟用對IPv4和IPv6網路的支援。



 a| 
TCP接聽連接埠（按一下*顯示更多連接埠設定*即可取得）。
 a| 
如有必要、請輸入新的連接埠號碼。

接聽連接埠是控制器用來接聽來自主機iSCSI啟動器之iSCSI登入的TCP連接埠號碼。預設的接聽連接埠為3260。您必須輸入3260或49152到65535.之間的值。



 a| 
MTU大小（按一下*顯示更多連接埠設定*即可取得）。
 a| 
如有必要、請為最大傳輸單元（MTU）輸入新的位元組大小。

預設的最大傳輸單元（MTU）大小為每個框架1500位元組。您必須輸入介於1500和9000之間的值。



 a| 
啟用ICMP Ping回應
 a| 
選取此選項可啟用網際網路控制訊息傳輸協定（ICMP）。網路電腦的作業系統會使用此傳輸協定來傳送訊息。這些ICMP訊息可判斷主機是否可連線、以及從該主機取得封包所需的時間。

|===
+
如果您選取*啟用IPV4、則會在您按一下*下一步*之後、開啟一個對話方塊、供您選取IPV4設定。如果您選取*啟用IPv6 *、則會在您按一下*下一步*之後、開啟一個對話方塊來選取IPv6設定。如果您同時選取這兩個選項、則會先開啟[IPV4設定]對話方塊、然後按一下[* Next*（*下一步*）]之後、隨即開啟[IPv6設定]對話方塊。

. 自動或手動設定IPv6和/或IPv6設定。若要查看所有連接埠設定、請按一下對話方塊右側的*顯示更多設定*連結。
+
|===
| 連接埠設定 | 說明 


 a| 
自動取得組態
 a| 
選取此選項可自動取得組態。



 a| 
手動指定靜態組態
 a| 
選取此選項、然後在欄位中輸入靜態位址。對於IPV4、請加入網路子網路遮罩和閘道。對於IPv6、請包含可路由的IP位址和路由器IP位址。

|===
. 單擊*完成*。
. 關閉System Manager。

