---
permalink: config-linux/nvme-roce-assign-volume-task.html 
sidebar: sidebar 
keywords: assign volume Linux, assign namespace Linux, express linux configuration, linux host, 
summary: 您必須將磁碟區（命名空間）指派給主機或主機叢集、以便用於I/O作業。此指派可讓主機或主機叢集存取儲存陣列中的一或多個命名空間。 
---
= 指派磁碟區
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須將磁碟區（命名空間）指派給主機或主機叢集、以便用於I/O作業。此指派可讓主機或主機叢集存取儲存陣列中的一或多個命名空間。

指派磁碟區時、請謹記以下準則：

* 您一次只能將磁碟區指派給一個主機或主機叢集。
* 指派的磁碟區會在儲存陣列的控制器之間共用。
* 主機或主機叢集無法使用相同的命名空間ID（NSID）兩次來存取磁碟區。您必須使用唯一的NSID。


指派磁碟區會在下列情況下失敗：

* 所有磁碟區均已指派。
* 磁碟區已指派給其他主機或主機叢集。


在下列情況下、無法指派磁碟區：

* 不存在有效的主機或主機叢集。
* 已定義所有Volume指派。


顯示所有未指派的磁碟區、但具有或不具有Data Assurance（DA）的主機的功能如下所示：

* 對於具有DA功能的主機、您可以選取已啟用DA或未啟用DA的磁碟區。
* 對於不具備DA功能的主機、如果您選取的磁碟區已啟用DA、則會出現警告訊息指出系統必須在將磁碟區指派給主機之前、自動關閉磁碟區上的DA。


.步驟
. 選取功能表：Storage[hosts]。
. 選取您要指派磁碟區的主機或主機叢集、然後按一下*指派磁碟區*。
+
此時會出現一個對話方塊、列出所有可指派的磁碟區。您可以排序任何欄或在「*篩選*」方塊中輸入內容、以便更容易找到特定的磁碟區。

. 選取您要指派的每個Volume旁的核取方塊、或選取表格標題中的核取方塊、以選取所有Volume。
. 按一下「*指派*」以完成作業。


成功將磁碟區或磁碟區指派給主機或主機叢集之後、系統會執行下列動作：

* 指派的Volume會接收下一個可用的NSID。主機使用NSID存取磁碟區。
* 使用者提供的Volume名稱會出現在與主機相關聯的Volume清單中。

