---
permalink: config-linux/nvme-ib-define-host-task.html 
sidebar: sidebar 
keywords: define Linux host, express linux configuration, linux host, 
summary: 使用「系統管理程式」、您可以定義將資料傳送至儲存陣列的主機。SANtricity定義主機是讓儲存陣列知道其連接的主機、以及允許I/O存取磁碟區所需的步驟之一。 
---
= 定義主機
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用「系統管理程式」、您可以定義將資料傳送至儲存陣列的主機。SANtricity定義主機是讓儲存陣列知道其連接的主機、以及允許I/O存取磁碟區所需的步驟之一。

.關於這項工作
定義主機時、請謹記下列準則：

* 您必須定義與主機相關聯的主機識別碼連接埠。
* 請確定您提供的名稱與主機指派的系統名稱相同。
* 如果您選擇的名稱已在使用中、則此作業不會成功。
* 名稱長度不得超過30個字元。


.步驟
. 選取功能表：Storage[hosts]。
. 按一下功能表：Create [Host]（建立[主機]）。
+
此時會出現Create Host（建立主機）對話方塊。

. 視需要選取主機的設定。
+
|===
| 設定 | 說明 


 a| 
名稱
 a| 
輸入新主機的名稱。



 a| 
主機作業系統類型
 a| 
從下拉式清單中選取下列其中一個選項：

** * SANtricity 《Linux * for》（適用於更新版本的*《Linux *》）
** *適用於SANtricity 11.60之前版本的Linux DM-MP（Kernel 3.10或更新版本）*




 a| 
主機介面類型
 a| 
選取您要使用的主機介面類型。



 a| 
主機連接埠
 a| 
執行下列其中一項：

** *選擇I/O介面*
+
如果主機連接埠已登入、您可以從清單中選取主機連接埠識別碼。這是建議的方法。

** *手動新增*
+
如果主機連接埠尚未登入、請查看主機上的/etc/np/hostnqn、找出hostnqn識別碼、並將其與主機定義建立關聯。

+
您可以手動輸入主機連接埠識別碼、或從/etc/np/hostnqn檔案（一次一個）複製/貼到*主機連接埠*欄位。

+
您一次必須新增一個主機連接埠識別碼、才能將其與主機建立關聯、但您可以繼續選取與主機相關聯的識別碼數目。每個識別碼都會顯示在*主機連接埠*欄位中。如有必要、您也可以選取旁邊的* X*來移除識別碼。



|===
. 按一下「 * 建立 * 」。


.結果
成功建立主機之後SANtricity 、即可為為主機設定的每個主機連接埠建立預設名稱。

預設別名為「<主機名稱連接埠號碼>」。例如、為「主機IPT」建立的第一個連接埠的預設別名為IPT_1。
