---
permalink: config-linux/nvme-roce-configure-switch-task.html 
sidebar: sidebar 
keywords: configure switch, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 您可以根據廠商針對NVMe over RoCE的建議來設定交換器。這些建議可能同時包含組態指令和程式碼更新。 
---
= 設定 E 系列中的交換器 - Linux（NVMe over RoCE）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以根據廠商針對NVMe over RoCE的建議來設定交換器。這些建議可能同時包含組態指令和程式碼更新。


CAUTION: * 資料遺失風險 *您必須在無損環境中執行 NVMe/RoCE。在您的網路上使用全域暫停訊框型流量控制或優先權流量控制（PFC）啟用端對端流量控制，以消除資料遺失的風險。



== 全域暫停訊框

全域暫停訊框是最基本的流量控制形式，也是最容易實作的。當流量超過網路連接埠的處理能力時，系統會產生暫停訊框，暫停該連接埠上的所有流量，直到先前的流量已處理到足以讓網路連接埠能夠繼續處理而不會捨棄傳入流量。

.步驟
. 使用交換器廠商提供的文件，啟用以全域暫停訊框為基礎的*端對端*流程控制。
. 確保在此環境中，連接到主機、陣列和交換器間連結的所有交換器連接埠都啟用基於全域暫停訊框的流量控制。




== 優先流量控制

優先權流量控制 (PFC) 是一種更複雜的流量控制形式，它為不同類型的流量分配不同的優先權等級。當某個優先權的流量過大時，該優先權的流量會被暫停，而其他優先權等級的流量則可以繼續傳輸，從而防止某些類型的大量流量影響其他類型的流量。

目前，您必須使用運行 11.80.1 版本的 EF600 E-Series Array（配備 200Gb/s 乙太網路 HIC，零件號 111-04583）或運行任何支援的 NVMe/RoCE HIC 的 EF80 E-Series Array。PFC 參數已硬編碼在陣列上，並且要求 NVMe/RoCE 流量標記為優先權 3，DSCP 值為 `106`。

.步驟
. 如需使用 PFC 值設定網路的詳細資訊，請參閱交換器廠商文件。
. 如需為環境選擇最佳組態的秘訣、請洽詢您的網路管理員。


.接下來呢？
設定交換器之後，link:nvme-roce-setup-host-side-task.html["在主機上透過 RoCE 設定 NVMe 啟動器"]。
