---
permalink: config-linux/nvme-fc-setup-host-side-task.html 
sidebar: sidebar 
keywords: NVMe over Fibre Channel, host side, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Fibre Channel環境中的NVMe啟動器組態包括安裝及設定NVMe CLI套件、以及在主機上啟用NVMe / FC啟動器。 
---
= 在主機端設定NVMe over Fibre Channel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Fibre Channel環境中的NVMe啟動器組態包括安裝及設定NVMe CLI套件、以及在主機上啟用NVMe / FC啟動器。

下列程序適用於使用Broadcom Emulex或支援QLogic NVMe/FC的FC HBA的RHEL 7、RHEL 8、SLES 12和SLES 15。如需這些作業系統或HBA支援哪些版本的詳細資訊、請參閱 https://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"^]。

.步驟
. 安裝「NVMe-CLI（NVMe - CLI）套件：
+
* SLES 12或SLES 15*

+
[listing]
----

# zypper install nvme-cli
----
+
* RHEL 7或RHEL 8*

+
[listing]
----

# yum install nvme-cli
----
+
.. 僅適用於RHEL 7、請透過下載並安裝適用於NVMe / FC連線的外部Broadcom AutoConnect指令碼 https://www.broadcom.com/support/download-search["Broadcom網站"^]。輸入關鍵字* AutoConnect指令碼檔案以供採用FC驅動程式*的收件匣NVMe使用、並選擇您作業系統專屬的最新版本。
.. 若為Qlogic,請在安裝Broadcom NVMe/FC自動連線指令碼之後修改「/lib/systemd/system/nvmefc-boot-connections.service`」以包含下列項目：
+
[listing]
----
[Unit]
Description=Auto-connect to subsystems on FC-NVME devices found during boot

[Service]
Type=oneshot
ExecStart=/bin/sh -c "echo add > /sys/class/fc/fc_udev_device/nvme_discovery"

[Install]
WantedBy=default.target
----


. 啟用並啟動「nvmefc-boot-connections」服務。
+
[listing]
----
systemctl enable nvmefc-boot-connections.service
----
+
[listing]
----
systemctl start nvmefc-boot-connections.service
----


* Emulex HBA的主機端設定：*


NOTE: 以下步驟僅適用於Emulex HBA。

. 將「lffc_enable _FC4_tep」設為「3」、以將sless12 SP4啟用為NVMe / FC啟動器。
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_enable_fc4_type=3
----
. 重新建置「initrd-」以變更Emulex變更和開機參數。
+
[listing]
----
# dracut --force
----
. 重新啟動主機、將變更載入「IPFC」驅動程式。
+
[listing]
----
# reboot
----
+
主機重新開機、並在主機上啟用NVMe / FC啟動器。

+

NOTE: 完成主機端設定之後、NVMe over Fibre Channel連接埠會自動連線。


