---
permalink: config-linux/nvme-roce-discover-connect-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage, host, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 在SANtricity 定義完「支援系統管理程式」中的每個主機之前、您必須先從主機探索目標控制器連接埠、然後建立NVMe連線。 
---
= 從 E 系列 - Linux （ NVMe over roce ）的主機探索並連線至儲存設備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在SANtricity 定義完「支援系統管理程式」中的每個主機之前、您必須先從主機探索目標控制器連接埠、然後建立NVMe連線。

.步驟
. 使用以下命令驗證您可以使用預期的 MTU 速率從主機 ping 到每個陣列 HIC 連接埠：
+
[listing]
----
ping -M do -s <size> <IP of array HIC port>
----
. 使用下列命令探索所有路徑的NVMe目標子系統：
+
[listing]
----
nvme discover -t rdma -a target_ip_address
----
+
在此命令中、「target ip_address'」是目標連接埠的IP位址。

+

NOTE: 無論主機存取為何、「NVMe探索」命令都會探索子系統中的所有控制器連接埠。

+
[listing]
----
# nvme discover -t rdma -a 192.168.1.77
Discovery Log Number of Records 2, Generation counter 0
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  0
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94
traddr:  192.168.1.77
rdma_prtype: roce
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 1======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94
traddr:  192.168.2.77
rdma_prtype: roce
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
----
. 對任何其他連線重複步驟 2。
. 使用命令「NVMe CONNECT -t RDMA -n Disclided_sub nqn -A target ip_address-Q queue_depth_setting -l控制器損失超時期間」連線至第一條路徑上探索到的子系統
+

NOTE: 上述命令在重新開機後不會保留。每次重新開機後都需要執行  `nvme connect` 命令以重新建立 NVMe 連線。

+

NOTE: 不會針對主機無法存取的任何探索到的連接埠建立連線。

+

NOTE: 如果您使用此命令指定連接埠號碼、連線將會失敗。預設連接埠是唯一設定用於連線的連接埠。

+

NOTE: 建議的佇列深度設定為 1024。使用 `-Q 1024` 命令列選項，將預設設定 128 替換為 1024，如下列範例所示。

+

NOTE: 建議的控制器遺失逾時時間（以秒為單位）為60分鐘（3、600秒）。使用「-l 3600'命令列選項、以3、600秒取代預設設定、如下例所示。

+
[listing]
----
# nvme connect -t rdma -a 192.168.1.77 -n nqn.1992-
08.com.netapp:EF80.600a098000a527a7000000005ab3af94 -Q 1024 -l 3600
----
. 重複步驟 4，將探索到的子系統連接到第二條路徑。
. **選用** - 設定主機在每次開機時自動探索目標並與其連線。
+
.. 使用下列程序和格式，將步驟 2 和步驟 3 中的探索參數新增至  `/etc/nvme/discovery.conf`：
+
[listing]
----
# echo "--transport=rdma --traddr= target_ip_address --trsvcid=4420" | sudo tee -a /etc/nvme/discovery.conf
----
.. 使用以下命令填充  `/etc/nvme/discovery.conf` 檔案後啟用 nvmf-autoconnect 服務：
+
[listing]
----
sudo systemctl enable nvmf-autoconnect.service
----




.接下來呢？
建立連線之後，link:nvme-roce-define-host-task.html["定義主機"]。
