---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: 更新功能。SANtricity 
---
= 更新功能SANtricity
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下表說明SANtricity 適用於EF300、EF600、E2800/EF280及E5700/EF570控制器的內嵌式管理功能的更新功能。



== 11.74版的新功能

[cols="35h,~"]
|===
| 新功能 | 說明 


 a| 
支援FIPS 140-2
 a| 
FIPS 140-2和NVMe型SSD目前支援特定磁碟機使用FIPS 140-2。FIPS 140-2層級SSD磁碟機可與FIPS 140-2層級SSD磁碟機共存、但前提是這些磁碟機均為NVMe型或所有SAS型。在Volume群組和磁碟集區中混合使用這些層級時、請注意群組或集區將會以較低的安全性層級（1402）運作。



 a| 
MFA與SSH支援
 a| 
針對版本11.74及更新版本、遠端登入功能可讓您設定多因素授權（MFA）、方法是要求使用者輸入SSH金鑰及/或SSH密碼。SANtricity「硬體」區段中的功能表選項已從*變更遠端登入*變更為*設定遠端登入（SSH）*。



 a| 
存取權杖
 a| 
此版本包含一項新功能、可用來建立存取權杖。這些權杖可讓您使用REST API或命令列介面（CLI）進行驗證、而不會洩漏使用者名稱和密碼。存取管理區段提供此功能。



 a| 
美國政府執行令
 a| 
為了遵守執行訂單、本版本包含數項安全性變更。

|===


== 11.73版的新功能

[cols="35h,~"]
|===
| 新功能 | 說明 


 a| 
資源配置與DULBE支援
 a| 
此版本現在完全支援資源配置功能和DULBE磁碟機功能。這項支援包括讓主機導向的未對應資源配置磁碟區更容易使用。



 a| 
EF600 SAS（512e）擴充
 a| 
此版本支援EF600儲存系統擴充至SAS-3機箱。藉由這項擴充、4KiB-block NVMe SSD可與512e SAS SSD和HDD共存。但是、無法在相同的集區或磁碟區群組中設定具有不同區塊大小的磁碟機。



 a| 
支援qlc SSD
 a| 
此版本支援ONTAP 目前一代的QLC SSD、該SSD在磁碟機韌體中已設定了一些功能、但沒有完整的E系列專屬功能集。qlc磁碟機（僅限NVMe）成本較低、但寫入效能較低、耐受度較低、因此不應用於寫入密集的工作負載。



 a| 
TLS 1.3支援
 a| 
TLS 1.3現在支援內嵌管理。這項支援適用於System Manager和內嵌式Web服務、可啟用或停用。（在先前的Web服務Proxy和Unified Manager版本中新增了TLS 1.3支援。）



 a| 
RAID 1 DDP（至少8個磁碟機）
 a| 
在此版本中、RAID 1 DDP不再需要集區中至少11個SSD。如果池中只建立RAID 1磁碟區、則最低容量現在允許8個磁碟機SSD集區。



 a| 
EKMS金鑰刪除
 a| 
儲存管理員現在可以要求外部金鑰管理伺服器（EKMS）刪除舊金鑰。金鑰刪除只會在安裝磁碟機有新金鑰之後、於重新金鑰程序期間進行。

|===


== 11.72版的新功能

[cols="35h,~"]
|===
| 新功能 | 說明 


 a| 
支援v3
 a| 
您現在可以在功能表：設定[警示]中設定警示通知、支援使用v3。v3可透過強式驗證和資料加密來提供安全性。



 a| 
支援將金鑰複寫至多個金鑰伺服器
 a| 
針對自我加密磁碟機的外部金鑰管理、「建立外部金鑰管理」對話方塊中包含新的選項、可新增多個金鑰伺服器。



 a| 
更新瀏覽器版本
 a| 
已更新System Manager最低瀏覽器版本。

|===


== 11.71版的新功能

[cols="35h,~"]
|===
| 新功能 | 說明 


 a| 
EF300擴充
| 此版本支援EF300儲存系統擴充至SAS-3機箱。藉由這項擴充、4KiB-block NVMe SSD可與512e SAS SSD和HDD共存。但是、無法在相同的集區或磁碟區群組中設定具有不同區塊大小的磁碟機。 


 a| 
iSCSI組態中的FEC模式選項
 a| 
對於使用25GB iSCSI主機介面卡的儲存陣列、當您設定iSCSI連接埠時、可以使用新選項來設定轉送錯誤修正（FEC）模式。



 a| 
遠端儲存磁碟區
 a| 
選用的遠端儲存磁碟區功能可讓您使用iSCSI連線、從遠端儲存系統將磁碟區匯入本機E系列儲存系統。遠端儲存設備的品牌可能與您的E系列系統相同、也可能來自不同的儲存設備廠商、只要透過iSCSI即可存取即可。



 a| 
為非FDE磁碟機新增掃用（清除）功能
 a| 
磁碟機清理功能現在已在程序中包含非FDE磁碟機。在「Hardware（硬體）」頁面中、您可以開啟磁碟機的內容功能表、然後選取「Erase（清除）」（此選項先前為「Secure Erase（安全清除）」）。



 a| 
電子郵件警示的安全連線
 a| 
若要啟用加密電子郵件通知、您可以選擇性地設定傳出電子郵件（警示、ASUP派單）以提供驗證認證。加密類型包括SMTPS和ARTTLS。



 a| 
補充項目AutoSupport
 a| 
若未啟用功能、「通知」區域會出現警示AutoSupport 。



 a| 
系統記錄警示格式變更
 a| 
Syslog警示格式現在支援RFC 5424。

|===


== 11.70版的新功能

[cols="35h,~"]
|===
| 新功能 | 說明 


 a| 
全新儲存系統機型–EF300
 a| 
此版本推出EF300低成本All NVMe Flash儲存系統。EF300包括24個NVMe SSD磁碟機、以及每個控制器一個主機介面卡（HIC）。支援的NVMe over Fabrics主機介面包括NVMe over IB、NVMe over RoCE和NVMe over FC。支援的SCSI介面包括FC、IB over iSER和IB over SRP。可在Unified Manager中檢視及管理多個EF300儲存系統和其他E系列儲存系統。



 a| 
新的資源配置功能（僅限EF300和EF600）
 a| 
EF300和EF600儲存系統的資源配置功能是新功能。資源配置的磁碟區可立即投入使用、無需背景初始化程序。



 a| 
新增512e區塊大小選項（僅限EF300和EF600）
 a| 
對於EF300和EF600儲存系統、可以設定一個磁碟區來支援512位元組或4KiB區塊大小。新增512e功能、可支援iSCSI主機介面和VMware OS。如果可能、System Manager會建議適當的預設值。



 a| 
可AutoSupport 隨需傳送功能不全的更新選項
 a| 
全新的「傳送AutoSupport 支援資料」功能可讓您將資料傳送至技術支援部門、而無需等待排定的派單。此選項可在AutoSupport 支援中心的「支援中心」的「資訊」索引標籤中找到。



 a| 
外部金鑰管理伺服器增強功能
 a| 
連線至外部金鑰管理伺服器的功能包括下列增強功能：

* 略過建立備份金鑰的功能。
* 除了用戶端和伺服器憑證之外、請為金鑰管理伺服器選擇中繼憑證。




 a| 
憑證增強功能
 a| 
此版本可讓您使用外部工具（例如、OpenSSL）來產生憑證簽署要求（CSR）、這也需要您匯入私密金鑰檔案及簽署的憑證。



 a| 
Volume群組的全新離線初始化功能
 a| 
對於Volume建立、System Manager提供跳過主機指派步驟的方法、以便離線初始化新建立的Volume。此功能僅適用於SAS磁碟機上的RAID Volume群組（亦即、不適用於動態磁碟集區或EF300和EF600儲存系統中隨附的NVMe SSD）。此功能適用於需要在使用開始時讓磁碟區達到完整效能的工作負載、而非在背景執行初始化。



 a| 
全新的「收集組態資料」功能
 a| 
這項新功能可儲存控制器的RAID組態資料、其中包含Volume群組和磁碟集區的所有資料（與「儲存陣列dbmDatabase」的CLI命令相同）。此功能已新增至輔助技術支援、位於支援中心的診斷標籤中。



 a| 
在12個磁碟機案例中變更磁碟集區的預設保留容量
 a| 
先前建立的12個磁碟機磁碟集區具有足夠的保留（備援）容量、可容納兩個磁碟機。現在、預設值已變更為處理單一磁碟機故障、以提供更具成本效益的小型集區預設值。

|===