---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: 更新功能。SANtricity 
---
= 更新功能SANtricity
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下表說明 SANtricity OS 11.8 中嵌入式管理 EF300 、 EF600 、 E2800/EF280 和 E5700/EF570 控制器的新功能。



== 11.80 版的新功能

[cols="35h,~"]
|===
| 新功能 | 說明 


 a| 
增強的 Volume 同位檢查掃描
 a| 
Volume 同位元檢查掃描現在可以透過 REST API 或 CLI 作為背景程序啟動。只要需要完成掃描作業、所產生的同位元檢查掃描就會在背景中執行。在控制器重新開機和容錯移轉作業之後、掃描作業仍可繼續執行。



 a| 
Unified Manager 的 SAML 支援
 a| 
Unified Manager 現在支援 SAML （安全聲明標記語言）。啟用 Unified Manager 的 SAML 後、使用者必須針對身分識別提供者使用多因素驗證、才能與使用者介面互動。請注意、在 Unified Manager 上啟用 SAML 之後、只有透過 IDP 驗證要求、才能使用 REST API 。



 a| 
自動組態功能
 a| 
現在支援設定 Volume 區塊大小參數的功能、以搭配自動組態功能進行初始陣列設定。此功能僅在 CLI 中以「區塊大小」參數提供。



 a| 
控制器韌體密碼編譯簽署
 a| 
控制器韌體經過密碼編譯簽署。在初始下載期間和每個控制器開機時、都會檢查簽名。預期不會對終端使用者造成影響。簽章由 CA 核發的延伸驗證憑證作為後盾。



 a| 
磁碟機韌體密碼編譯簽署
 a| 
磁碟機韌體經過密碼編譯簽署。在初始下載期間會檢查簽名、並以 CA 核發的延伸驗證憑證作為後盾。磁碟機韌體內容現在會以 ZIP 檔案形式提供、其中包含舊版的未簽署韌體、以及新簽署的韌體。使用者必須根據目標系統上執行的程式碼發行版本、選擇適當的檔案。



 a| 
外部金鑰伺服器管理 - 憑證金鑰大小
 a| 
新的預設憑證金鑰大小為 3072 位元（ 2048 位元）。支援的金鑰大小最高可達 4096 位元。必須變更 NVSRAM 位元、才能支援非預設金鑰大小。



 a| 
使用容量為 512B 區塊的磁碟機、支援更大的動態磁碟集區大小
 a| 
使用版本 1 集區版本類型的客戶現在可以擁有 48 TB 最大容量的磁碟集區。較舊版本最多可支援 24 TB 磁碟集區大小。如果要將現有的磁碟集區轉換成較大的大小、則必須先移除所有磁碟區。存在版本 1 磁碟集區時、降級作業會受到限制。



 a| 
除非符合最低瀏覽器需求、否則 System Manager 和 Unified Manager 將不會啟動
 a| 
系統管理員或 Unified Manager 啟動前、必須先提供瀏覽器的最低版本。以下是支援的最低版本：

* Firefox 最低版本 80
* Chrome 最低版本 89
* Edge 最低版本 90
* Safari 最低版本 14




 a| 
支援 FIPS 140-3 NVMe SSD 磁碟機
 a| 
NetApp 認證的 FIPS 140-3 NVMe SSD 磁碟機現在受到支援。在儲存陣列設定檔和 System Manager 中、這些設定檔將會正確識別。



 a| 
支援 EF300 和 EF600 上的 SSD 讀取快取
 a| 
使用 SAS 擴充硬碟的 EF300 和 EF600 控制器現在支援 SSD 讀取快取。



 a| 
支援 EF300 和 EF600 上的 iSCSI 和光纖通道非同步遠端鏡射
 a| 
採用 NVMe 和 SAS 型磁碟區的 EF300 和 EF600 控制器現在支援非同步遠端鏡射（ ARVM ）。



 a| 
支援 EF300 和 EF600 、不需在基本托盤上安裝磁碟機
 a| 
現在支援基礎托盤上沒有 NVMe 磁碟機的 EF300 和 EF600 控制器組態。



 a| 
已停用所有平台的 USB 連接埠
 a| 
現在所有平台上的 USB 連接埠都已停用。

|===