---
permalink: getting-started/learn-terms-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, terms 
summary: 深入瞭解E系列中使用的術語。 
---
= E系列術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
深入瞭解E系列中使用的術語。

|===
| 期限 | 說明 


 a| 
控制器
 a| 
控制器由主機板、韌體和軟體組成。它控制磁碟機並實作功能。



 a| 
雙工/單工組態
 a| 
雙工是儲存陣列內的雙控制器模組組組態。單工是單一控制器模組組態。



 a| 
HDD
 a| 
硬碟機（HDD）是資料儲存設備、使用具有磁性塗層的旋轉式金屬盤片。



 a| 
HIC
 a| 
主機介面卡（HIC）會將陣列連接至主機。它可選擇性安裝在控制器容器內。



 a| 
IB
 a| 
InfiniBand（IB）是高效能伺服器與儲存系統之間資料傳輸的通訊標準。



 a| 
IOPS
 a| 
IOPS是每秒的輸入/輸出作業。



 a| 
鏡射
 a| 
鏡射是將資料磁碟區複寫到不同的儲存陣列、以確保持續可用度。



 a| 
資源池
 a| 
資源池是邏輯分組的一組磁碟機。您可以使用集區來建立一個或多個可供主機存取的磁碟區。



 a| 
電力/風扇容器
 a| 
電力/風扇容器是滑入機櫃的組件。其中包括電源供應器和整合式風扇。



 a| 
機架單元（U）
 a| 
機架單位（簡稱U）是指44.5公釐（1.75英吋）的測量單位。



 a| 
SAS
 a| 
序列附加SCSI（SAS）是一種點對點序列傳輸協定、可將控制器直接連結至磁碟機。



 a| 
RoCE
 a| 
RDMA over Converged Ethernet（RoCE）是一種網路傳輸協定、可透過乙太網路進行遠端直接記憶體存取（RDMA）。



 a| 
機櫃
 a| 
機櫃是安裝在機櫃或機架中的機箱。其中包含儲存陣列的硬體元件。磁碟櫃有兩種類型：控制器磁碟櫃和磁碟機磁碟櫃。控制器機櫃包含控制器和磁碟機。磁碟機櫃包含輸入/輸出模組（IOM）和磁碟機。



 a| 
Snapshot
 a| 
Snapshot映像是在特定時間點擷取的Volume資料邏輯複本。如同還原點、Snapshot映像可讓您回復至已知良好的資料集。



 a| 
SSD
 a| 
固態磁碟（SSD）是使用固態記憶體（Flash）持續儲存資料的資料儲存裝置。SSD可模擬傳統硬碟機、並與硬碟機使用的介面相同。



 a| 
儲存陣列
 a| 
儲存陣列包括磁碟櫃、控制器、磁碟機、軟體和韌體。



 a| 
Volume
 a| 
Volume是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機所建立的邏輯元件、可用來存取儲存陣列上的儲存設備。



 a| 
工作負載
 a| 
工作負載是支援應用程式的儲存物件。對於某些應用程式、System Manager會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。

|===