---
sidebar: sidebar 
permalink: vcenter-plugin/faq-storage-plugin-vcenter.html 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity Storage Plugin for vCenter 的常見問題解答
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 匯入哪些設定？

匯入設定功能是批次作業、可將組態從一個儲存陣列載入至多個儲存陣列。

在此作業期間匯入的設定取決於來源儲存陣列在System Manager中的設定方式。下列設定可匯入多個儲存陣列：

* *電子郵件警示*-設定包含電子郵件伺服器位址和警示收件者的電子郵件位址。
* *系統記錄警示*-設定包括系統記錄伺服器位址和一個udp連接埠。
* * SNMP警示*-設定包含SNMP伺服器的社群名稱和IP位址。
* * AutoSupport 《*》*《設定》包括獨立的功能（基本AutoSupport 功能、AutoSupport 《不限需求》和《遠端診斷》）、維護時間、交付方法、 和分派排程。
* *目錄服務*-組態包括LDAP（輕量型目錄存取傳輸協定）伺服器的網域名稱和URL、以及LDAP伺服器使用者群組與儲存陣列預先定義角色的對應。
* *儲存組態*-組態包括磁碟區（僅限完整磁碟區和非儲存庫磁碟區）、磁碟區群組、集區和熱備援磁碟機指派。
* *系統設定*-組態包括磁碟區的媒體掃描設定、控制器的SSD快取、以及自動負載平衡（不包括主機連線報告）。




== 為什麼我看不到所有的儲存陣列？

在匯入設定作業期間、目標選擇對話方塊中可能無法使用部分儲存陣列。

儲存陣列可能不會出現、原因如下：

* 韌體版本低於8.50。
* 儲存陣列已離線。
* 系統無法與該陣列通訊（例如、陣列有憑證、密碼或網路問題）。




== 為什麼這些磁碟區與工作負載無關？

如果磁碟區是使用命令列介面（CLI）建立、或是已從不同的儲存陣列移轉（匯入/匯出）、則不會與工作負載建立關聯。



== 我所選的工作負載如何影響磁碟區建立？

在磁碟區建立期間、系統會提示您提供工作負載使用的相關資訊。系統會使用此資訊為您建立最佳Volume組態、並可視需要加以編輯。您也可以在磁碟區建立順序中跳過此步驟。

工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。對於某些應用程式、系統會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。

* *應用程式專屬*-當您使用應用程式專屬的工作負載來建立磁碟區時、系統可能會建議最佳化的磁碟區組態、以將應用程式工作負載I/O與應用程式執行個體的其他流量之間的爭用降至最低。對於針對下列應用程式類型所建立的工作負載、會自動建議並最佳化I/O類型、區段大小、控制器擁有權、讀寫快取等Volume特性。
+
** Microsoft SQL Server
** Microsoft Exchange Server
** 視訊監控應用程式
** VMware ESXi（適用於與虛擬機器檔案系統搭配使用的磁碟區）
+
您可以使用「新增/編輯磁碟區」對話方塊來檢閱建議的磁碟區組態、以及編輯、新增或刪除系統建議的磁碟區和特性。



* *其他（或不支援特定磁碟區建立的應用程式）*- 其他工作負載則使用Volume組態、您必須手動指定何時要建立與特定應用程式無關的工作負載、或是儲存陣列上未針對您要使用的應用程式進行內建最佳化。您必須使用「新增/編輯磁碟區」對話方塊手動指定磁碟區組態。




== 為什麼我看不到所有的磁碟區、主機或主機叢集？

具有啟用DA基礎磁碟區的Snapshot Volume不符合指派給不具備Data Assurance（DA）功能的主機的資格。您必須先停用基礎磁碟區上的DA、才能將快照磁碟區指派給不具備DA功能的主機。

請針對您要指派快照磁碟區的主機、考慮下列準則：

* 如果主機透過不支援DA的I/O介面連接至儲存陣列、則該主機將無法執行DA功能。
* 如果主機叢集至少有一個主機成員不具備DA功能、則該主機叢集無法執行DA功能。



NOTE: 您無法在與快照（一致性群組、快照群組、快照映像和快照磁碟區）、磁碟區複本、 和鏡射。必須先刪除所有相關的保留容量和快照物件、才能在基礎磁碟區上停用DA。



== 為什麼我無法刪除選取的工作負載？

此工作負載由一組使用命令列介面（CLI）建立的磁碟區、或是從不同儲存陣列移轉（匯入/匯出）的磁碟區組成。因此、此工作負載中的磁碟區不會與應用程式專屬的工作負載相關聯、因此無法刪除工作負載。



== 應用程式專屬的工作負載如何協助我管理儲存陣列？

應用程式專屬工作負載的Volume特性決定了工作負載與儲存陣列元件的互動方式、並有助於在特定組態下判斷環境的效能。

應用程式是SQL Server或Exchange等軟體。您可以定義一或多個工作負載來支援每個應用程式。對於某些應用程式、系統會自動建議最佳化儲存設備的Volume組態。磁碟區組態中包含I/O類型、區段大小、控制器擁有權、讀寫快取等特性。



== 我需要如何辨識擴充的容量？

如果您增加磁碟區的容量、主機可能無法立即辨識磁碟區容量的增加。

大多數作業系統都會辨識擴充的Volume容量、並在啟動Volume擴充之後自動擴充。不過、有些可能沒有。如果作業系統無法自動辨識擴充的Volume容量、您可能需要執行磁碟重新掃描或重新開機。

擴充磁碟區容量之後、您必須手動增加檔案系統大小以符合需求。您的做法取決於所使用的檔案系統。

如需其他詳細資料、請參閱主機作業系統文件。



== 我想在何時使用「稍後指派主機」選項？

如果您想加速建立磁碟區的程序、可以跳過主機指派步驟、以便離線初始化新建立的磁碟區。

必須初始化新建立的磁碟區。系統可以使用兩種模式之一進行初始化、即立即可用的格式（IAF）背景初始化程序或離線程序。

將磁碟區對應到主機時、會強制該群組中任何初始化的磁碟區轉換成背景初始化。此背景初始化程序可同時執行主機I/O、有時可能會耗費大量時間。

如果未對應磁碟區群組中的任何磁碟區、則會執行離線初始化。離線程序比背景程序快得多。



== 我需要知道哪些關於主機區塊大小需求的資訊？

對於EF300和EF600系統、可以設定一個磁碟區來支援512位元組或4KiB區塊大小（也稱為「磁碟區大小」）。您必須在建立磁碟區期間設定正確的值。如果可能、系統會建議適當的預設值。

設定Volume區塊大小之前、請先閱讀下列限制與準則。

* 某些作業系統和虛擬機器（尤其是VMware目前）需要512位元組的區塊大小、而且不支援4KiB、因此請務必在建立磁碟區之前先瞭解主機需求。一般而言、您可以設定一個Volume來呈現4KiB區塊大小、以達到最佳效能；不過、請確定您的主機允許使用4KiB（或「4Kn」）區塊。
* 您為集區或磁碟區群組選取的磁碟機類型、也會決定支援哪些磁碟區塊大小、如下所示：
+
** 如果您使用寫入512位元組區塊的磁碟機來建立磁碟區群組、則只能建立含有512位元組區塊的磁碟區。
** 如果您使用寫入4KiB區塊的磁碟機來建立磁碟區群組、則可以使用512位元組或4KiB區塊來建立磁碟區。


* 如果陣列有iSCSI主機介面卡、則所有磁碟區都限制為512位元組區塊（無論磁碟區群組區塊大小）。這是因為特定的硬體實作。
* 一旦設定區塊大小、您就無法變更區塊大小。如果您需要變更區塊大小、則必須刪除磁碟區並重新建立。




== 為什麼我需要建立主機叢集？

如果您想要讓兩個以上的主機共用同一組磁碟區的存取權、則需要建立主機叢集。一般而言、個別主機上安裝了叢集軟體、以協調磁碟區存取。



== 如何知道哪種主機作業系統類型正確？

主機作業系統類型欄位包含主機的作業系統。您可以從下拉式清單中選取建議的主機類型。

下拉式清單中顯示的主機類型取決於儲存陣列機型和韌體版本。最新版本會先顯示最常見的選項、最可能是適當的選項。此清單上的外觀並不表示完全支援此選項。


NOTE: 如需主機支援的詳細資訊、請參閱 http://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"^]。

清單中可能會出現下列部分主機類型：

|===
| 主機作業系統類型 | 作業系統（OS）和多重路徑驅動程式 


| Linux DM-MP（核心3.10或更新版本） | 支援使用Device Mapper多重路徑容錯移轉解決方案搭配3.10或更新版本核心的Linux作業系統。 


| VMware ESXi | 使用VMware內建的儲存陣列類型原則模組SATP_ALUA、支援執行原生多路徑外掛程式（NMP）架構的VMware ESXi作業系統。 


| Windows（叢集式或非叢集式） | 支援未執行Atto多重路徑驅動程式的Windows叢集式或非叢集式組態。 


| Atto叢集（所有作業系統） | 支援所有使用Atto Technology、Inc.、多重路徑驅動程式的叢集組態。 


| Linux（Veritas DMP） | 使用Veritas DMP多重路徑解決方案支援Linux作業系統。 


| Linux（Atto） | 支援使用Atto Technology、Inc.、多重路徑驅動程式的Linux作業系統。 


| Mac OS | 支援使用Atto Technology、Inc.、多重路徑驅動程式的Mac OS版本。 


| Windows（Atto） | 支援使用Atto Technology、Inc.、多重路徑驅動程式的Windows作業系統。 


| IBM服務 | 支援IBM SAN Volume Controller組態。 


| 原廠預設值 | 保留用於儲存陣列的初始啟動。如果您的主機作業系統類型設為出廠預設值、請將其變更為符合主機作業系統和連接主機上執行的多重路徑驅動程式。 


| Linux DM-MP（Kernal 3.9或更早版本） | 支援使用具備3.9或更早核心的Device Mapper多重路徑容錯移轉解決方案的Linux作業系統。 


| 叢集式視窗（已過時） | 如果您的主機作業系統類型設定為此值、請改用Windows（叢集式或非叢集式）設定。 
|===


== 如何將主機連接埠與主機配對？

如果您是手動建立主機、則必須先使用主機上可用的適當主機匯流排介面卡（HBA）公用程式、來判斷與主機中安裝的每個HBA相關聯的主機連接埠識別碼。

取得此資訊後、請從「Create Host（建立主機）」對話方塊中提供的清單中、選取已登入儲存陣列的主機連接埠識別碼。


CAUTION: 請務必為您要建立的主機選取適當的主機連接埠識別碼。如果您將錯誤的主機連接埠識別碼關聯起來、可能會導致無法預期地從其他主機存取此資料。



== 什麼是預設叢集？

預設叢集是系統定義的實體、可讓登入儲存陣列的任何未關聯主機連接埠識別碼、存取指派給預設叢集的磁碟區。

未關聯的主機連接埠識別碼是與特定主機邏輯上並未關聯的主機連接埠、而是實際安裝在主機上並登入儲存陣列。


NOTE: 如果您想讓主機對儲存陣列中的特定磁碟區擁有特定存取權、則不得使用預設叢集。您必須將主機連接埠識別碼與其對應的主機建立關聯。此工作可在「建立主機」作業期間手動完成。然後、您可以將磁碟區指派給個別主機或主機叢集。

在特殊情況下、您只能使用預設叢集、因為外部儲存環境有助於讓所有主機和所有登入的主機連接埠識別碼都能存取儲存陣列的所有磁碟區（全存取模式）。 而不讓儲存陣列或使用者介面知道主機。

一開始、您只能透過命令列介面（CLI）將磁碟區指派給預設叢集。不過、在您將至少一個Volume指派給預設叢集之後、此實體（稱為預設叢集）會顯示在使用者介面中、您可以在其中管理此實體。



== 什麼是備援檢查？

備援檢查可決定集區或磁碟區群組中磁碟區上的資料是否一致。如果資源池或磁碟區群組中的某個磁碟機故障、備援資料可用於快速重建替換磁碟機上的資訊。

您一次只能在一個集區或磁碟區群組上執行此檢查。磁碟區備援檢查會執行下列動作：

* 掃描RAID 3 Volume、RAID 5 Volume或RAID 6 Volume中的資料區塊、然後檢查每個區塊的備援資訊。（RAID 3只能使用命令列介面指派給Volume群組。）
* 比較RAID 1鏡射磁碟機上的資料區塊。
* 如果控制器韌體判定資料不一致、則傳回備援錯誤。



NOTE: 在相同的集區或磁碟區群組上立即執行備援檢查可能會導致錯誤。若要避免此問題、請先等待一到兩分鐘、再在同一個集區或磁碟區群組上執行另一個備援檢查。



== 什麼是保留容量？

保留容量是指為支援潛在磁碟機故障而保留在集區中的容量（磁碟機數量）。

建立集區時、系統會根據集區中的磁碟機數量、自動保留預設的保留容量。

資源池會在重建期間使用保留容量、而磁碟區群組則會將熱備援磁碟機用於相同用途。保留容量方法是比熱備援磁碟機更好的方法、因為它可讓重建作業更快完成。保留容量會分散在集區中的多個磁碟機上、而非熱備援磁碟機上的一個磁碟機、因此您不會受限於單一磁碟機的速度或可用度。



== 哪種RAID層級最適合我的應用程式？

若要將磁碟區群組的效能最大化、您必須選取適當的RAID層級。

您可以知道存取磁碟區群組的應用程式讀取和寫入百分比、藉此判斷適當的RAID層級。請使用「效能」頁面取得這些百分比。



=== RAID層級與應用程式效能

RAID仰賴一系列的組態（稱為層級）來判斷如何從磁碟機寫入和擷取使用者和備援資料。每個RAID層級都提供不同的效能功能。由於RAID 5和RAID 6組態的優異讀取效能、高讀取百分比的應用程式在使用RAID 5磁碟區或RAID 6磁碟區時效能將會很好。

讀取百分比較低（寫入密集）的應用程式在RAID 5磁碟區或RAID 6磁碟區上的效能不佳。效能降級是控制器將資料和備援資料寫入RAID 5 Volume群組或RAID 6 Volume群組中的磁碟機的方式所致。

根據下列資訊選取RAID層級。



==== RAID 0

*說明：*

* 非備援的分段模式。
* RAID 0會在Volume群組中的所有磁碟機之間條帶化資料。


*資料保護功能：*

* RAID 0不建議用於高可用度需求。RAID 0更適合非關鍵資料。
* 如果磁碟區群組中的單一磁碟機故障、所有相關的磁碟區都會故障、而且所有資料都會遺失。


*磁碟機編號要求：*

* RAID層級0至少需要一個磁碟機。
* RAID 0磁碟區群組可有30個以上的磁碟機。
* 您可以建立包含儲存陣列中所有磁碟機的磁碟區群組。




==== RAID 1或RAID 10

*說明：*

* 分段/鏡射模式。


*運作方式：*

* RAID 1使用磁碟鏡射、將資料同時寫入兩個重複的磁碟。
* RAID 10使用磁碟機等量分段來在一組鏡射磁碟機配對之間分段資料。


*資料保護功能：*

* RAID 1和RAID 10提供高效能和最佳資料可用度。
* RAID 1和RAID 10使用磁碟機鏡射功能、從一個磁碟機精確複製到另一個磁碟機。
* 如果磁碟機配對中的其中一個磁碟機故障、儲存陣列就能立即切換至另一個磁碟機、而不會遺失任何資料或服務。
* 單一磁碟機故障會導致相關磁碟區降級。鏡射磁碟機可存取資料。
* 磁碟區群組中的磁碟機配對故障會導致所有相關的磁碟區故障、並可能導致資料遺失。


*磁碟機編號要求：*

* RAID 1至少需要兩個磁碟機：一個磁碟機用於使用者資料、一個磁碟機用於鏡射資料。
* 如果您選取四個或更多磁碟機、RAID 10會在整個磁碟區群組中自動設定：兩個磁碟機用於使用者資料、兩個磁碟機用於鏡射資料。
* 磁碟區群組中必須有偶數個磁碟機。如果您沒有偶數個磁碟機、但仍有一些未指派的磁碟機、請前往*資源池與磁碟區群組*、將其他磁碟機新增至磁碟區群組、然後重試此作業。
* RAID 1和RAID 10磁碟區群組可擁有30個以上的磁碟機。您可以建立包含儲存陣列中所有磁碟機的Volume群組。




==== RAID 5

*說明：*

* 高I/O模式。


*運作方式：*

* 使用者資料和備援資訊（同位元檢查）會在磁碟機之間進行等量分佈。
* 一個磁碟機的容量相當於備援資訊。


*資料保護功能*

* 如果RAID 5 Volume群組中的單一磁碟機故障、所有相關的磁碟區都會降級。備援資訊可讓您繼續存取資料。
* 如果RAID 5磁碟區群組中有兩個或多個磁碟機故障、所有相關的磁碟區都會故障、而且所有資料都會遺失。


*磁碟機編號要求：*

* 磁碟區群組中至少必須有三個磁碟機。
* 一般而言、磁碟區群組中最多只能有30個磁碟機。




==== RAID 6

*說明：*

* 高I/O模式。


*運作方式：*

* 使用者資料和備援資訊（雙同位元檢查）會在磁碟機之間分佈。
* 兩個磁碟機的容量相當於備援資訊。


*資料保護功能：*

* 如果RAID 6磁碟區群組中有一或兩個磁碟機故障、則所有相關的磁碟區都會降級、但冗餘資訊仍可存取資料。
* 如果在RAID 6 Volume群組中有三個以上的磁碟機故障、則所有相關的磁碟區都會故障、而且所有資料都會遺失。


*磁碟機編號要求：*

* 磁碟區群組中至少必須有五個磁碟機。
* 一般而言、磁碟區群組中最多只能有30個磁碟機。



NOTE: 您無法變更集區的RAID層級。使用者介面會自動將集區設定為RAID 6。



=== RAID層級與資料保護

RAID 1、RAID 5和RAID 6會將備援資料寫入磁碟機媒體、以利容錯。備援資料可能是資料（鏡射）的複本、或是從資料衍生的錯誤修正程式碼。如果磁碟機故障、您可以使用備援資料快速重建替換磁碟機上的資訊。

您可以在單一磁碟區群組中設定單一RAID層級。該磁碟區群組的所有備援資料都儲存在磁碟區群組中。磁碟區群組的容量是成員磁碟機的集合容量減去為備援資料保留的容量。備援所需的容量取決於所使用的RAID層級。



== 為什麼有些磁碟機沒有顯示？

在「Add Capacity」（新增容量）對話方塊中、並非所有磁碟機都能新增容量至現有的資源池或磁碟區群組。

磁碟機不符合下列任何理由：

* 磁碟機必須未指派、且未啟用安全功能。磁碟機已經是另一個集區、另一個磁碟區群組的一部分、或是設定為熱備援磁碟機、則不符合資格。如果磁碟機未指派、但已啟用安全功能、您必須手動清除該磁碟機、才能符合資格。
* 處於非最佳狀態的磁碟機不符合資格。
* 如果磁碟機的容量太小、就不符合資格。
* 磁碟機媒體類型必須與集區或磁碟區群組相符。您無法混用下列項目：
+
** 硬碟機（HDD）搭配固態磁碟（SSD）
** NVMe與SAS磁碟機
** 具有512位元組和4KiB磁碟區區塊大小的磁碟機


* 如果集區或磁碟區群組包含所有具有安全功能的磁碟機、則不會列出不安全功能的磁碟機。
* 如果集區或磁碟區群組包含所有聯邦資訊處理標準（FIPS）磁碟機、則不會列出非FIPS磁碟機。
* 如果集區或磁碟區群組包含所有資料保證（DA）功能的磁碟機、且集區或磁碟區群組中至少有一個啟用DA的磁碟區、則不符合不具備DA功能的磁碟機資格、因此無法將其新增至該集區或磁碟區群組。不過、如果集區或Volume群組中沒有啟用DA的磁碟區、則無法將無法使用DA的磁碟機新增至該集區或Volume群組。如果您決定混合使用這些磁碟機、請記住、您無法建立任何啟用DA的磁碟區。



NOTE: 您可以新增磁碟機、或刪除資源池或磁碟區群組、來增加儲存陣列的容量。



== 為什麼我無法增加保留容量？

如果您已在所有可用容量上建立磁碟區、則可能無法增加保留容量。

保留容量是指為支援潛在磁碟機故障而保留在集區上的容量（磁碟機數量）。建立集區時、系統會根據集區中的磁碟機數量、自動保留預設的保留容量。如果您已在所有可用容量上建立磁碟區、則無法透過新增磁碟機或刪除磁碟區、來增加保留容量、而不將容量新增至資源池。

您可以變更資源池和Volume群組的保留容量。選取您要編輯的資源池。按一下「*檢視/編輯設定*」、然後選取「*設定*」索引標籤。


NOTE: 保留容量會指定為多個磁碟機、即使實際保留容量會分散在集區中的磁碟機上。



== 什麼是資料保證？

資料保證（DA）實作T10保護資訊（PI）標準、藉由檢查及修正在I/O路徑傳輸資料時可能發生的錯誤、來提升資料完整性。

「資料保證」功能的一般用途是檢查控制器與磁碟機之間I/O路徑的部分。在資源池和Volume群組層級提供DA功能。

啟用此功能時、儲存陣列會將錯誤檢查代碼（也稱為循環備援檢查或CRC）附加到磁碟區中的每個資料區塊。資料區塊移動之後、儲存陣列會使用這些CRC代碼來判斷傳輸期間是否發生任何錯誤。可能毀損的資料既不會寫入磁碟、也不會傳回主機。如果您想要使用DA功能、請在建立新磁碟區時、選取具有DA功能的資源池或磁碟區群組（請在「資源池和磁碟區群組候選資料表」中尋找「* Yes*」旁邊的資料池或磁碟區群組）。

請務必使用能夠執行DA的I/O介面、將這些啟用DA的磁碟區指派給主機。具備DA功能的I/O介面包括光纖通道、SAS、TCP/IP iSCSI、NVMe / FC、NVMe / IB、 適用於InfiniBand的NVMe/RoCE和iSER（適用於RDMA/ IB的iSCSI擴充功能）。SRP不支援DA over InfiniBand。



== 什麼是FDE/FIPS安全性？

FDE/FIPS安全性是指可在讀取期間使用獨特加密金鑰加密資料的安全磁碟機。

這些具有安全功能的磁碟機可防止未獲授權存取實體從儲存陣列移除的磁碟機上的資料。安全的磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。FIPS磁碟機已通過認證測試。


NOTE: 對於需要FIPS支援的磁碟區、請僅使用FIPS磁碟機。在磁碟區群組或集區中混合使用FIPS和FDE磁碟機、將會將所有磁碟機視為FDE磁碟機。此外、FDE磁碟機無法新增至All FIPS Volume群組或Pool、也無法作為備援磁碟機使用。



== 什麼是安全功能（磁碟機安全性）？

磁碟機安全功能可防止在從儲存陣列移除時、未獲授權存取啟用安全功能之磁碟機上的資料。

這些磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。



== 如何檢視及解讀所有SSD快取統計資料？

您可以檢視SSD快取的名義統計資料和詳細統計資料。

名義統計資料是詳細統計資料的子集。只有當您將所有SSD統計資料匯出至CSV檔案時、才能檢視詳細的統計資料。當您檢閱及解讀統計資料時、請記住、有些解讀是由統計資料的組合所衍生而來。



=== 名義統計資料

若要檢視SSD快取統計資料、請前往*管理*頁面。選取功能表：資源配置[設定資源池與磁碟區群組]。選取您要檢視統計資料的SSD快取、然後選取功能表：More（更多）[View Statistics（檢視統計資料）]。名義統計資料會顯示在「檢視SSD快取統計資料」對話方塊中。


NOTE: EF600或EF300儲存系統無法使用此功能。

清單中包含名義統計資料、這是詳細統計資料的子集。



=== 詳細統計資料

詳細統計資料包括名義統計資料、以及其他統計資料。這些額外的統計資料會連同名義統計資料一起儲存、但與名義統計資料不同的是、它們不會顯示在「檢視SSD快取統計資料」對話方塊中。您只能在將統計資料匯出至.csv檔案之後、才能檢視詳細的統計資料。

詳細統計資料會列在名義統計資料之後。



== 什麼是機櫃損失保護和藥櫃損失保護？

機櫃遺失保護和藥櫃遺失保護是資源池和磁碟區群組的屬性、可讓您在單一機櫃或藥櫃故障時維持資料存取。



=== 機櫃損失保護

機櫃是包含磁碟機或磁碟機與控制器的機箱。機櫃遺失保護可確保在單一磁碟機櫃發生通訊完全中斷時、能夠存取資源池或磁碟區群組中磁碟區上的資料。通訊中斷的範例可能是磁碟機櫃電力中斷、或兩個I/O模組（IOM）故障。


NOTE: 如果磁碟機已在集區或磁碟區群組中故障、則無法保證磁碟櫃遺失保護。在這種情況下、失去磁碟機櫃的存取權、進而導致集區或磁碟區群組中的另一個磁碟機遺失資料。

機櫃損失保護的準則取決於保護方法、如下表所述。

|===
| 層級 | 機櫃損失保護標準 | 所需的磁碟櫃數量下限 


| 資源池 | 集區必須包含至少五個磁碟櫃的磁碟機、而且每個磁碟櫃中必須有相同數量的磁碟機。機櫃遺失保護不適用於大容量機櫃；如果您的系統含有大容量機櫃、請參閱「藥櫃遺失保護」。 | 5. 


| RAID 6 | 磁碟區群組在單一藥櫃中不包含兩個以上的磁碟機。 | 3. 


| RAID 3或RAID 5 | Volume群組中的每個磁碟機都位於不同的磁碟櫃中。 | 3. 


| RAID 1 | RAID 1配對中的每個磁碟機都必須位於不同的磁碟櫃中。 | 2. 


| RAID 0 | 無法達到機架遺失保護。 | 不適用 
|===


=== 藥櫃遺失保護

抽屜是您拉出以存取磁碟機的磁碟櫃之一。只有大容量的機櫃才有抽屜。藥櫃遺失保護可確保在單一藥櫃發生通訊中斷時、能夠存取資源池或磁碟區群組中磁碟區上的資料。通訊中斷的範例可能是藥櫃電力中斷、或藥櫃內的內部元件故障。


CAUTION: 如果磁碟機已在集區或磁碟區群組中故障、則無法保證藥櫃遺失保護。在這種情況下、無法存取藥櫃（以及池或Volume群組中的另一個磁碟機）會導致資料遺失。

藥櫃遺失保護的條件取決於保護方法、如下表所述：

|===
| 層級 | 藥櫃損失保護條件 | 所需的藥櫃數量下限 


| 資源池 | 資源池候選裝置必須包含所有藥櫃的磁碟機、而且每個藥櫃中的磁碟機數量必須相等。集區必須包含至少五個抽屜的磁碟機、而且每個抽屜中的磁碟機數量必須相等。當集區包含15、20、25、30、35、 40、45、50、55或60個磁碟機。初始建立之後、可以將5的倍數遞增量新增至資源池。 | 5. 


| RAID 6 | 磁碟區群組在單一藥櫃中不包含兩個以上的磁碟機。 | 3. 


| RAID 3或5 | 磁碟區群組中的每個磁碟機都位於獨立的磁碟櫃中 | 3. 


| RAID 1 | 鏡射配對中的每個磁碟機都必須位於獨立的抽屜中。 | 2. 


| RAID 0 | 無法達到藥櫃損失保護。 | 不適用 
|===


== 如何維護機櫃和藥櫃遺失保護？

若要維護資源池或磁碟區群組的機櫃和藥櫃遺失保護、請使用下表中指定的條件。

|===
| 層級 | 機櫃/藥櫃損失保護條件 | 所需的機櫃/藥櫃數量下限 


| 資源池 | 如果是磁碟櫃、該資源池必須在單一磁碟櫃中包含兩個以上的磁碟機。對於藥櫃、該資源池必須包含每個藥櫃的相同磁碟機數量。 | 6個用於機櫃5個用於機櫃 


| RAID 6 | 磁碟區群組在單一磁碟櫃或磁碟櫃中不含兩個以上的磁碟機。 | 3. 


| RAID 3或RAID 5 | Volume群組中的每個磁碟機都位於獨立的磁碟櫃或抽屜中。 | 3. 


| RAID 1 | 鏡射配對中的每個磁碟機必須位於獨立的磁碟櫃或磁碟櫃中。 | 2. 


| RAID 0 | 無法達到機櫃/藥櫃遺失保護。 | 不適用 
|===

NOTE: 如果磁碟機已在集區或磁碟區群組中故障、則無法維護機櫃/藥櫃遺失保護。在這種情況下、失去磁碟機櫃或抽屜的存取權、進而導致集區或磁碟區群組中的另一個磁碟機遺失資料。



== 集區的最佳化容量為何？

當SSD磁碟機的一部分容量未配置時、其壽命將更長、寫入效能將更高。

對於與集區相關聯的磁碟機、未分配的容量由集區的保留容量、可用容量（磁碟區未使用的容量）以及保留為額外最佳化容量的可用容量所組成。額外的最佳化容量可藉由減少可用容量來確保最小程度的最佳化容量、因此無法建立磁碟區。

建立集區時、會產生建議的最佳化容量、以平衡效能、磁碟機耗損壽命和可用容量。「資源池設定」對話方塊中的「其他最佳化容量」滑桿可調整資源池的最佳化容量。調整滑桿可提高效能、延長使用壽命、同時犧牲可用容量或額外可用容量、同時犧牲效能和磁碟機使用壽命。


NOTE: 額外最佳化容量滑桿僅適用於EF600和EF300儲存系統。



== 什麼是Volume群組的最佳化容量？

當SSD磁碟機的一部分容量未配置時、其壽命將更長、寫入效能將更高。

對於與磁碟區群組相關聯的磁碟機、未分配的容量由磁碟區群組的可用容量（磁碟區未使用的容量）和保留為最佳化容量的部分可用容量組成。額外的最佳化容量可藉由減少可用容量來確保最小程度的最佳化容量、因此無法建立磁碟區。

建立Volume群組時、會產生建議的最佳化容量、以平衡效能、磁碟機耗損壽命和可用容量。Volume Group Settings（Volume群組設定）對話方塊中的其他Optimization Capacity（最佳化容量）滑桿可調整Volume群組的最佳化容量。調整滑桿可提高效能、延長使用壽命、同時犧牲可用容量或額外可用容量、同時犧牲效能和磁碟機使用壽命。


NOTE: 其他最佳化容量滑桿僅適用於EF600和EF300儲存系統。



== 什麼是資源資源配置功能？

資源資源配置是EF300和EF600儲存陣列的一項功能、可讓磁碟區立即投入使用、而無需背景初始化程序。

資源配置的磁碟區是SSD磁碟區群組或集區中的一個完整磁碟區、在建立磁碟區時、會將磁碟機容量分配給該磁碟區（指派給該磁碟區）、但磁碟區塊會被取消分配（未對應）。相較之下、在傳統的厚磁碟區中、所有磁碟區區塊都會在背景磁碟區初始化作業期間對應或配置、以便初始化Data Assurance保護資訊欄位、並使每個RAID等量磁碟區的資料和RAID同位元保持一致。使用資源配置的Volume、就不會進行時間限制的背景初始化。相反地、每個RAID等量磁碟區都會在第一次寫入等量磁碟區塊時初始化。

資源配置的磁碟區僅支援SSD磁碟區群組和集區、群組或集區中的所有磁碟機都支援NVMe取消分配或未寫入的邏輯區塊錯誤啟用（DULBE）錯誤恢復功能。建立資源配置的Volume時、會取消分配指派給該磁碟區的所有磁碟區塊（未對應）。此外、主機可以使用NVMe資料集管理命令取消分配磁碟區中的邏輯區塊。取消分配區塊可改善SSD的耗損壽命、並提高最大寫入效能。每個磁碟機機型和容量的改善程度各不相同。



== 關於資源配置的Volume功能、我需要知道什麼？

資源資源配置是EF300和EF600儲存陣列的一項功能、可讓磁碟區立即投入使用、而無需背景初始化程序。


NOTE: 目前無法使用資源配置功能。在某些檢視中、元件可能會回報為資源資源配置功能、但在未來更新中重新啟用之前、建立資源配置的磁碟區的功能已停用。



=== 資源配置的磁碟區

資源配置的磁碟區是SSD磁碟區群組或集區中的一個完整磁碟區、在建立磁碟區時、會將磁碟機容量分配給該磁碟區（指派給該磁碟區）、但磁碟區塊會被取消分配（未對應）。相較之下、在傳統的厚磁碟區中、所有磁碟區區塊都會在背景磁碟區初始化作業期間對應或配置、以便初始化Data Assurance保護資訊欄位、並使每個RAID等量磁碟區的資料和RAID同位元保持一致。使用資源配置的Volume、就不會進行時間限制的背景初始化。相反地、每個RAID等量磁碟區都會在第一次寫入等量磁碟區塊時初始化。

資源配置的磁碟區僅支援SSD磁碟區群組和集區、群組或集區中的所有磁碟機都支援NVMe取消分配或未寫入的邏輯區塊錯誤啟用（DULBE）錯誤恢復功能。建立資源配置的Volume時、會取消分配指派給該磁碟區的所有磁碟區塊（未對應）。此外、主機可以使用NVMe資料集管理命令取消分配磁碟區中的邏輯區塊。取消分配區塊可改善SSD的耗損壽命、並提高最大寫入效能。每個磁碟機機型和容量的改善程度各不相同。



=== 啟用和停用功能

預設會在磁碟機支援DULBE的系統上啟用資源配置。您可以從資源池和Volume群組停用該預設設定。停用資源資源配置是現有磁碟區的永久性動作、無法回復（亦即、您無法重新啟用這些磁碟區群組和資源池的資源配置）。

不過、如果您想要為所建立的任何新磁碟區重新啟用資源資源配置、可以從功能表：設定[系統]執行此作業。請注意、當您重新啟用資源資源配置時、只有新建立的Volume群組和集區會受到影響。任何現有的Volume群組和集區都將維持不變。如有需要、您也可以從功能表：設定[系統]再次停用資源資源配置。



== 內部安全金鑰與外部安全金鑰管理有何不同？

當您實作磁碟機安全功能時、可以使用內部安全金鑰或外部安全金鑰、在從儲存陣列移除已啟用安全功能的磁碟機時鎖定資料。

安全金鑰是一串字元、可在已啟用安全功能的磁碟機和儲存陣列中的控制器之間共用。內部金鑰會保留在控制器的持續記憶體上。外部金鑰是使用金鑰管理互通性傳輸協定（KMIP）、在獨立的金鑰管理伺服器上維護。



== 在建立安全金鑰之前、我需要知道什麼？

安全金鑰由儲存陣列內的控制器和啟用安全功能的磁碟機共用。如果從儲存陣列中移除啟用安全功能的磁碟機、安全金鑰會保護資料免於未經授權的存取。

您可以使用下列其中一種方法來建立及管理安全性金鑰：

* 控制器持續記憶體的內部金鑰管理。
* 外部金鑰管理伺服器上的外部金鑰管理。




== 內部金鑰管理

內部金鑰會在控制器的持續記憶體上不可存取的位置進行維護和「隱藏」。在建立內部安全金鑰之前、您必須執行下列動作：

. 在儲存陣列中安裝具有安全功能的磁碟機。這些磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。
. 確定磁碟機安全功能已啟用。如有必要、請聯絡您的儲存設備廠商、以取得啟用磁碟機安全功能的指示。


然後您可以建立內部安全金鑰、其中包括定義識別碼和密碼。識別碼是與安全金鑰相關聯的字串、儲存在控制器和與金鑰相關聯的所有磁碟機上。密碼用於加密安全金鑰以供備份之用。完成後、安全金鑰會儲存在無法存取的控制器位置。然後您可以建立啟用安全功能的Volume群組或集區、或是在現有的Volume群組和集區上啟用安全功能。



=== 外部金鑰管理

外部金鑰是使用金鑰管理互通性傳輸協定（KMIP）、在獨立的金鑰管理伺服器上維護。在建立外部安全金鑰之前、您必須執行下列動作：

. 在儲存陣列中安裝具有安全功能的磁碟機。這些磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。
. 確定磁碟機安全功能已啟用。如有必要、請聯絡您的儲存設備廠商、以取得啟用磁碟機安全功能的指示
. 取得已簽署的用戶端憑證檔案。用戶端憑證會驗證儲存陣列的控制器、因此金鑰管理伺服器可以信任其KMIP要求。
+
.. 首先、您必須完成並下載用戶端憑證簽署要求（CSR）。前往功能表：設定[憑證>金鑰管理>完整的CSR ]。
.. 接下來、您會向金鑰管理伺服器信任的CA要求已簽署的用戶端憑證。（您也可以使用下載的CSR檔案、從金鑰管理伺服器建立及下載用戶端憑證。）
.. 擁有用戶端憑證檔案之後、請將該檔案複製到您要存取System Manager的主機。


. 從金鑰管理伺服器擷取憑證檔案、然後將該檔案複製到您正在存取System Manager的主機。金鑰管理伺服器憑證會驗證金鑰管理伺服器、因此儲存陣列可以信任其IP位址。您可以將根、中繼或伺服器憑證用於金鑰管理伺服器。


然後您可以建立外部金鑰、其中包括定義金鑰管理伺服器的IP位址、以及KMIP通訊所使用的連接埠號碼。在此過程中、您也會載入憑證檔案。完成後、系統會以您輸入的認證資料連線至金鑰管理伺服器。然後您可以建立啟用安全功能的Volume群組或集區、或是在現有的Volume群組和集區上啟用安全功能。



== 為什麼我需要定義密碼？

密碼用於加密及解密儲存在本機管理用戶端上的安全金鑰檔案。如果安全金鑰重新安裝在另一個儲存陣列中、則沒有密碼、就無法解密安全金鑰、也無法用來解除鎖定已啟用安全功能的磁碟機中的資料。
