---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-storage-provisioning.html 
keywords: create volumes vCenter plugin, provision Plugin for vCenter, vCenter plugin storage provisioning, vCenter plugin host 
summary: 使用外掛程式for vCenter建立磁碟區、將磁碟區指派給主機、然後將磁碟區指派給資料存放區。 
---
= 在 SANtricity Storage Plugin for vCenter 中配置儲存設備
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
若要配置儲存設備、請建立磁碟區、將磁碟區指派給主機、然後將磁碟區指派給資料存放區。



== 步驟1：建立磁碟區

Volume是資料容器、可管理及組織儲存陣列上的儲存空間。您可以從儲存陣列上可用的儲存容量建立磁碟區、以協助組織系統資源。「Volume」的概念類似於使用電腦上的資料夾/目錄來組織檔案以供快速存取。

Volume是唯一可讓主機看到的資料層。在SAN環境中、磁碟區會對應至邏輯單元編號（LUN）。這些LUN包含使用儲存陣列支援的一或多個主機存取傳輸協定來存取的使用者資料。

.步驟
. 在「Manage（管理）」頁面中、選取儲存陣列。
. 選取功能表：資源配置[管理磁碟區]。
. 選取功能表：Create [Volumes]（建立[磁碟區]）
+
此時會出現選取主機對話方塊。

. 從下拉式清單中、選取您要指派磁碟區的特定主機或主機叢集、或選擇稍後指派主機或主機叢集。
. 若要繼續選取主機或主機叢集的磁碟區建立順序、請按一下*「下一步*」。
+
此時會出現Select Workload對話方塊。工作負載包含具有類似特性的磁碟區、這些磁碟區會根據工作負載所支援的應用程式類型進行最佳化。您可以定義工作負載、也可以選取現有的工作負載。

. 執行下列其中一項：
+
** 選取*為現有工作負載建立磁碟區*選項、然後從下拉式清單中選取工作負載。
** 選取*建立新的工作負載*選項、為支援的應用程式或「其他」應用程式定義新的工作負載、然後執行下列步驟：
+
... 從下拉式清單中、選取您要建立新工作負載的應用程式名稱。如果您要在此儲存陣列上使用的應用程式未列出、請選取其中一個「其他」項目。
... 輸入您要建立的工作負載名稱。




. 單擊 * 下一步 * 。如果您的工作負載與支援的應用程式類型相關聯、請輸入要求的資訊；否則、請前往下一步。
+
「新增/編輯磁碟區」對話方塊隨即出現。在此對話方塊中、您可以從合格的資源池或磁碟區群組建立磁碟區。針對每個合格的資源池和磁碟區群組、會顯示可用磁碟機數量和可用總容量。對於某些應用程式專屬的工作負載、每個合格的資源池或Volume群組會根據建議的Volume組態顯示建議的容量、並顯示GiB中的剩餘可用容量。對於其他工作負載、當您將磁碟區新增至資源池或磁碟區群組、並指定報告的容量時、就會顯示建議的容量。

. 開始新增磁碟區之前、請閱讀下表中的準則。
+
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
可用容量
 a| 
由於磁碟區是從集區或磁碟區群組建立、因此您選取的集區或磁碟區群組必須具有足夠的可用容量。



 a| 
資料保證（DA）
 a| 
若要建立啟用DA的磁碟區、您打算使用的主機連線必須支援DA。

** 如果您想要建立啟用DA的磁碟區、請選取具有DA功能的資源池或磁碟區群組（請在「資源池和磁碟區群組候選項目」表中尋找「DA」旁邊的*「Yes」（是）。
** 在資源池和Volume群組層級提供DA功能。DA保護會檢查並修正資料經由控制器向下傳輸到磁碟機時可能發生的錯誤。為新磁碟區選取具有DA功能的集區或磁碟區群組、可確保偵測並修正任何錯誤。
** 如果儲存陣列中控制器上的任何主機連線不支援DA、則相關主機無法存取啟用DA的磁碟區上的資料。




 a| 
磁碟機安全性
 a| 
若要建立啟用安全功能的磁碟區、必須為儲存陣列建立安全金鑰。

** 如果您想要建立啟用安全功能的Volume、請選取安全功能的資源池或Volume群組（請在Pool and Volume Group候選資料表的「Secure Capable（安全功能）」旁尋找* Yes（是）*）。
** 磁碟機安全功能會顯示在集區和磁碟區群組層級。具有安全功能的磁碟機可防止未獲授權存取實體從儲存陣列移除的磁碟機上的資料。啟用安全功能的磁碟機會在寫入期間加密資料、並使用獨特的加密金鑰在讀取期間解密資料。
** 集區或磁碟區群組可同時包含具有安全功能和不安全功能的磁碟機、但所有磁碟機必須具備安全功能、才能使用其加密功能。




 a| 
資源配置
 a| 
若要建立資源配置的磁碟區、所有磁碟機都必須是NVMe磁碟機、並具有取消分配或未寫入的邏輯區塊錯誤（DULBE）選項。

|===
. 根據您在上一步中選擇的是「其他」或應用程式專屬的工作負載、選擇下列其中一項動作：
+
** *其他*–在您要用來建立一或多個磁碟區的每個集區或磁碟區群組中、按一下*「新增磁碟區」。
** *應用程式專屬工作負載*：按一下*「下一步*」接受系統建議的所選工作負載磁碟區與特性、或按一下*「編輯磁碟區」*、變更、新增或刪除所選工作負載的系統建議磁碟區與特性。
+
此時會顯示下列欄位。

+
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
Volume名稱
 a| 
磁碟區在建立磁碟區順序期間會指派預設名稱。您可以接受預設名稱、或提供更具說明性的名稱、以指示儲存在磁碟區中的資料類型。



 a| 
報告容量
 a| 
定義新Volume的容量和要使用的容量單位（mib、GiB或TiB）。對於大型磁碟區、最小容量為1個mib、最大容量則取決於集區或Volume群組中磁碟機的數量和容量。資源池中的容量會以4-GiB為增量分配。任何非4 GiB倍數的容量都會被分配、但無法使用。若要確保整個容量都可使用、請以4-GiB為單位指定容量。如果存在不可用的容量、則重新取得容量的唯一方法是增加磁碟區的容量。



 a| 
Volume類型
 a| 
如果您選取「應用程式專屬工作負載」、「Volume Type（Volume類型）」欄位就會出現。這表示為應用程式專屬工作負載所建立的磁碟區類型。



 a| 
Volume區塊大小（僅限EF300和EF600）
 a| 
顯示可為Volume建立的區塊大小：

*** 512–512位元組
*** 4K–4、096位元組




 a| 
區段大小
 a| 
顯示區段大小調整的設定、僅適用於Volume群組中的磁碟區。您可以變更區段大小以最佳化效能。

*允許的區段大小轉換*–系統決定允許的區段大小轉換。無法在下拉式清單中使用不適當的從目前區段大小轉換的區段大小。允許的轉換通常是目前區段大小的兩倍或一半。例如、如果目前的Volume區段大小為32 KiB、則允許新的Volume區段大小為16 KiB或64 KiB。

*啟用SSD快取的磁碟區*–您可以為啟用SSD快取的磁碟區指定4-KiB區段大小。請務必針對啟用SSD快取的磁碟區選取4-KiB區段大小、以便處理小區塊I/O作業（例如、16個KiB I/O區塊大小或更小）。如果您選取4 KiB做為啟用SSD快取的磁碟區的區段大小、以處理大量區塊循序作業、效能可能會受到影響。

*變更區段大小的時間*–變更磁碟區區區段大小的時間長短取決於下列變數：

*** 主機的I/O負載
*** 磁碟區的修改優先順序
*** Volume群組中的磁碟機數量
*** 磁碟機通道數
*** 儲存陣列控制器的處理能力


當您變更磁碟區的區段大小時、I/O效能會受到影響、但您的資料仍可繼續使用。



 a| 
安全功能
 a| 
*是*僅當集區或磁碟區群組中的磁碟機具有加密功能時、才會出現在「安全功能」旁。磁碟機安全功能可防止未獲授權存取從儲存陣列中實際移除的磁碟機上的資料。此選項僅在磁碟機安全功能已啟用、且已為儲存陣列設定安全金鑰時可用。集區或磁碟區群組可同時包含具有安全功能和不安全功能的磁碟機、但所有磁碟機必須具備安全功能、才能使用其加密功能。



| 大 | *是*僅當集區或磁碟區群組中的磁碟機支援Data Assurance（DA）時、「DA」旁邊才會顯示「Yes（是）」。DA可提升整個儲存系統的資料完整性。DA可讓儲存陣列檢查資料經由控制器向下傳輸到磁碟機時可能發生的錯誤。將DA用於新磁碟區可確保偵測到任何錯誤。 
|===


. 若要繼續選取應用程式的磁碟區建立順序、請按一下「*下一步*」。
. 在最後一個步驟中、檢閱您要建立的磁碟區摘要、並進行任何必要的變更。若要進行變更、請按一下*上一步*。當您對磁碟區組態感到滿意時、請按一下*完成*。




== 步驟2：建立主機存取並指派磁碟區

可手動建立主機：

* *手動*–在手動建立主機期間、您可以從清單中選取主機連接埠識別碼、或手動輸入識別碼、藉此建立關聯。建立主機之後、如果您打算共用對磁碟區的存取權、可以將磁碟區指派給主機叢集或將其新增至主機叢集。




=== 手動建立主機

.開始之前
請閱讀下列準則：

* 您必須已經在環境中新增或探索儲存陣列。
* 您必須定義與主機相關聯的主機識別碼連接埠。
* 請確定您提供的名稱與主機指派的系統名稱相同。
* 如果您選擇的名稱已在使用中、則此作業不會成功。
* 名稱長度不得超過30個字元。


.步驟
. 在「Manage（管理）」頁面中、選取具有主機連線的儲存陣列。
. 選取功能表：資源配置[設定主機]。
+
此時會開啟「設定主機」頁面。

. 按一下功能表：Create [Host]（建立[主機]）。
+
此時會出現Create Host（建立主機）對話方塊。

. 視需要選取主機的設定。
+
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
名稱
 a| 
輸入新主機的名稱。



 a| 
主機作業系統類型
 a| 
從下拉式清單中選取新主機上執行的作業系統。



 a| 
主機介面類型
 a| 
（選用）如果儲存陣列支援多種主機介面類型、請選取您要使用的主機介面類型。



 a| 
主機連接埠
 a| 
執行下列其中一項：

** *選擇I/O介面*-一般而言、主機連接埠應該已登入、並可從下拉式清單中使用。您可以從清單中選取主機連接埠識別碼。
** *手動新增*-如果清單中未顯示主機連接埠識別碼、表示主機連接埠尚未登入。HBA公用程式或iSCSI啟動器公用程式可用來尋找主機連接埠識別碼、並將其與主機建立關聯。


您可以手動輸入主機連接埠識別碼、或從公用程式（一次一個）複製/貼到主機連接埠欄位。

您一次必須選取一個主機連接埠識別碼、才能將其與主機建立關聯、但您可以繼續選取與主機相關聯的識別碼數目。每個識別碼都會顯示在主機連接埠欄位中。如有必要、您也可以選取旁邊的* X*來移除識別碼。



 a| 
設定CHAP啟動器密碼
 a| 
（選用）如果您選取或手動輸入iSCSI IQN的主機連接埠、而且想要要求嘗試存取儲存陣列以使用Challenge Handshake驗證傳輸協定（CHAP）進行驗證的主機、請選取「*設定CHAP啟動器密碼*」核取方塊。針對您選取或手動輸入的每個iSCSI主機連接埠、執行下列動作：

** 輸入在每個iSCSI主機啟動器上為CHAP驗證設定的相同CHAP密碼。如果您使用的是相互CHAP驗證（雙向驗證、可讓主機驗證自己是否為儲存陣列、以及讓儲存陣列驗證自己是否為主機）、則您也必須在初始設定或變更設定時、為儲存陣列設定CHAP機密。
** 如果不需要主機驗證、請將欄位留白。


目前唯一使用的iSCSI驗證方法是CHAP。

|===
. 按一下「 * 建立 * 」。
. 如果您需要更新主機資訊、請從表格中選取主機、然後按一下「*檢視/編輯設定*」。
+
成功建立主機之後、系統會針對為主機設定的每個主機連接埠建立預設名稱（使用者標籤）。預設別名為「<主機名稱連接埠號碼>」。例如、為主機IPT建立的第一個連接埠的預設別名為「IPT_1」。

. 接下來、您必須將磁碟區指派給主機或主機叢集、以便用於I/O作業。選取功能表：資源配置[設定主機]。
+
此時會開啟「設定主機」頁面。

. 選取您要指派磁碟區的主機或主機叢集、然後按一下*指派磁碟區*。
+
此時會出現一個對話方塊、列出所有可指派的磁碟區。您可以排序任一欄、或在「篩選」方塊中輸入內容、以便更容易找到特定的磁碟區。

. 選取您要指派的每個磁碟區旁的核取方塊、或選取表格標題中的核取方塊、以選取所有磁碟區。
. 按一下「*指派*」以完成作業。
+
系統會執行下列動作：

+
** 指派的磁碟區會收到下一個可用的LUN號碼。主機使用LUN編號來存取磁碟區。
** 使用者提供的Volume名稱會出現在與主機相關聯的Volume清單中。如果適用、原廠設定的存取Volume也會顯示在與主機相關的Volume清單中。






== 步驟3：在vSphere Client中建立資料存放區

若要在 vSphere Client 中建立資料存放區、請參閱 https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-5AC611E0-7CEB-4604-A03C-F600B1BA2D23.html["在vSphere Client中建立VMFS資料存放區"^] VMware 文件中心主題。



=== 增加磁碟區容量、以增加現有資料存放區的容量

您可以使用資源池或磁碟區群組中可用的可用容量、來增加磁碟區的報告容量（報告給主機的容量）。

.開始之前
請確定：

* 磁碟區相關聯的資源池或磁碟區群組中有足夠的可用容量可用。
* 磁碟區是最佳的、不會處於任何修改狀態。
* 磁碟區中沒有使用熱備援磁碟機。（僅適用於Volume群組中的Volume。）



NOTE: 增加磁碟區容量僅在某些作業系統上受支援。如果您在不支援LUN擴充的主機作業系統上增加磁碟區容量、擴充的容量將無法使用、而且您無法還原原始磁碟區容量。

.步驟
. 瀏覽至vSphere Client內的外掛程式。
. 在外掛程式中、選取所需的儲存陣列。
. 單擊* Provisioning *（配置*）並選擇* Manage Volumes（管理卷）*。
. 選取您要增加容量的磁碟區、然後選取*增加容量*。
+
此時會出現「確認增加容量」對話方塊。

. 選擇* Yes*繼續。
+
「增加報告容量」對話方塊隨即出現。

+
此對話方塊會顯示磁碟區目前報告的容量、以及磁碟區相關聯之資源池或Volume群組中可用的可用容量。

. 使用「*透過新增...*來增加報告容量」方塊、將容量新增至目前可用的報告容量。您可以變更容量值、以百萬位元組（mebibbytes、mibibibbytes、GiB）或tebibbytes（TiB）顯示。
. 按一下*「增加*」。
. 檢視「近期工作」窗格、以取得目前針對所選磁碟區執行的增加容量作業進度。這項作業可能會耗費大量時間、並可能影響系統效能。
. 磁碟區容量完成後、您必須手動增加 VMFS 大小、以符合中所述 https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-D57FEF5D-75F1-433D-B337-E760732282FC.html["增加vSphere Client中的VMFS資料存放區容量"^] VMware 文件中心下的主題。




=== 新增磁碟區以增加現有資料存放區的容量

. 您可以新增磁碟區來增加資料存放區的容量。請依照中的步驟進行 <<步驟1：建立磁碟區>>。
. 接下來、將磁碟區指派給所需的主機、以增加資料存放區的容量。
+
請參閱 https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.hostclient.doc/GUID-B0D89816-02E5-4C42-AAFC-19751800A284.html["增加vSphere Client中的VMFS資料存放區容量"^] 如需詳細資訊、請參閱 VMware 文件中心下的主題。


