---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-installation.html 
keywords: install vCenter plugin, installing vCenter plugin, vCenter plugin, 
summary: 安裝或升級SANtricity 適用於vCenter的《The VMware vCenter儲存外掛程式》。 
---
= 安裝或升級 SANtricity Storage Plugin for vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
請依照下列步驟安裝vCenter的儲存外掛程式、並驗證外掛程式登錄。您也可以使用這些指示來升級外掛程式。



== 檢閱安裝先決條件

請確定您的系統符合中的要求 link:san-spvc-ic-reqs.html["檢閱安裝與升級需求"]。


NOTE: 升級程序不會保留* vcenter.properties*檔案。如果您要升級、則必須在升級前取消登錄外掛程式。一旦升級成功、您就可以再次將外掛程式登錄至vCSA。



== 安裝外掛程式軟體

若要安裝外掛程式軟體：

. 將安裝程式檔案複製到將做為應用程式伺服器的主機、然後存取您下載安裝程式的資料夾。
. 按兩下安裝檔案：
+
「antricity儲存設備_vcenterplugin-windows_x64-- n.n.nn.nns.exe」

+
在上述檔案名稱中、「n.n.n.nn.nnn.nnn」代表版本編號。

. 安裝開始時、請依照畫面上的提示啟用多項功能、並輸入一些組態參數。如有必要、您可以稍後在組態檔中變更這些選項。
+

NOTE: 在升級期間、系統不會提示您輸入組態參數。

+

NOTE: 安裝期間、系統會提示您進行憑證驗證。如果您要在外掛程式與儲存陣列之間強制執行憑證驗證、請保持核取方塊的選取狀態。在這項強制措施下、儲存陣列憑證會根據外掛程式加以檢查、以確保可信。如果憑證不受信任、則不允許將其新增至外掛程式。如果您要置換憑證驗證、請取消選取核取方塊、以便使用自我簽署的憑證將所有儲存陣列新增至外掛程式。若要深入瞭解憑證、請參閱外掛程式介面提供的線上說明。

. 出現Webserver started（Webserver已啟動）訊息時、按一下* OK（確定）*完成安裝、然後按一下* DOU*（*完成）。
. 執行* services.msc*命令、確認應用程式伺服器已成功安裝。
. 確認已SANtricity 安裝應用程式伺服器（VCP）服務*適用於VCenter*的NetApp VMware vCenter儲存外掛程式、且服務已啟動。
+

NOTE: 如有必要、您可以在安裝後變更「憑證驗證」和「Web服務連接埠」設定。從安裝目錄開啟wsconfig.xml檔案。若要移除儲存陣列上的憑證驗證、請將「env」金鑰「trust．all.Array」變更為「true」。若要變更Web服務連接埠、請將「slport」值修改為所需的連接埠值、範圍從0-65535.請確定所使用的連接埠號碼未繫結至其他程序。完成後、請儲存變更並重新啟動外掛程式Web伺服器。如果將外掛程式登錄至vCSA之後、外掛程式Web伺服器的連接埠值已變更、則您必須取消登錄並重新登錄外掛程式、以便vCSA在變更的連接埠上與外掛程式Web伺服器通訊。





== 向vCenter Server Appliance註冊外掛程式

安裝外掛程式軟體之後、請向vCSA註冊外掛程式。


NOTE: 外掛程式一次只能登錄到一個vCSA。若要登錄至不同的vCSA、您必須從目前的vCSA中取消登錄外掛程式、然後從應用程式主機解除安裝。然後您可以重新安裝外掛程式、並將其登錄至其他vCSA。

. 透過命令列開啟提示字元、然後瀏覽至下列目錄：
+
「<安裝目錄>\vCenter-Register \bin」

. 執行* vCenter-Register．bat*檔案：「vcenter-register.bat」、「-action registerPlugin」、「-vcenterHostname」、「vCenter FQDN」、「-使用者名稱」、「^」
. 驗證指令碼是否成功。


記錄會儲存至「%install_dir%/工作日 誌/vC-registry.log」。



== 驗證外掛程式登錄

安裝外掛程式並執行登錄指令碼之後、請確認外掛程式已成功登錄vCenter Server Appliance。

. 開啟vSphere Client至vCenter Server Appliance。
. 在功能表列上、選取功能表：「Administrator」（管理員）[Client Plugins]（用戶端外掛程式）。
. 請確定vCenter的儲存外掛程式已列為*已啟用*。
+
如果外掛程式列為「已停用」、並顯示錯誤訊息指出無法與應用程式伺服器通訊、請確認已啟用為應用程式伺服器定義的連接埠號碼、以通過可能使用的任何防火牆。預設的應用程式伺服器傳輸控制傳輸協定（TCP）連接埠編號為84445。


