---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-storage-array-discovery.html 
keywords: discover arrays vCenter plugin, discover storage resources Plugin for vCenter, resolve certificates vCenter plugin 
summary: 使用外掛程式for vCenter介面來探索網路中陣列的IP位址。 
---
= 探索外掛程式中的儲存陣列
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要顯示及管理儲存資源、您必須使用Storage Plugin for vCenter介面來探索網路中陣列的IP位址。



== 步驟1：輸入網路位址進行探索

.開始之前
* 您必須知道陣列控制器的網路IP位址（或位址範圍）。
* 儲存陣列必須正確設定和設定、而且您必須知道儲存陣列登入認證（使用者名稱和密碼）。


.步驟
. 從「管理」頁面選取*「新增/探索」*。
+
此時會出現「輸入網路位址範圍」對話方塊。

. 執行下列其中一項：
+
** 若要探索一個陣列、請選取*探索單一儲存陣列*選項按鈕、然後輸入儲存陣列中其中一個控制器的IP位址。
** 若要探索多個儲存陣列、請選取*探索網路範圍內的所有儲存陣列*選項按鈕、然後輸入起始網路位址和結束網路位址、以搜尋整個本機子網路。


. 按一下*開始探索*。
+
當探索程序開始時、對話方塊會顯示探索到的儲存陣列。探索程序可能需要幾分鐘才能完成。

+
如果未找到可管理的陣列、請確認儲存陣列已正確連線至您的網路、且其指派的位址在範圍內。按一下「*新增探索參數*」以返回「新增/探索」頁面。

. 選取您要新增至管理網域之任何儲存陣列旁的核取方塊。
+
系統會對您要新增至管理網域的每個陣列執行認證檢查。您可能需要先解決不受信任憑證的任何問題、然後再繼續。

. 單擊*下一步*繼續執行精靈中的下一步。
+
如果儲存陣列擁有有效的憑證、請前往 <<Step 3: Provide passwords>>。

+
如果任何儲存陣列沒有有效的憑證、「解析自我簽署的憑證」對話方塊就會出現。前往 <<Step 2: Resolve untrusted certificates during discovery>>。

+
如果您要匯入CA簽署的憑證、請取消探索精靈、然後從左側面板按一下「*憑證管理*」。如需進一步指示、請參閱線上說明。





== 步驟2：在探索期間解析不受信任的憑證

您必須先解決任何憑證問題、才能繼續探索程序。

. 如果[解析自我簽署的憑證]對話方塊開啟，請檢閱顯示的不受信任憑證資訊。如需詳細資訊、您也可以按一下表格最末端的省略符號、然後從快顯功能表中選取*檢視*。
. 執行下列其中一項：
+
** 如果您信任已發現儲存陣列的連線、請按一下「*下一步*」、然後按一下「*是*」以確認並繼續精靈中的下一個對話方塊。自我簽署的憑證會標示為信任、儲存陣列也會新增至外掛程式。
** 如果您不信任儲存陣列的連線、請選取*取消*、然後在新增任何儲存陣列之前驗證每個儲存陣列的安全性憑證策略。


. 單擊*下一步*繼續執行精靈中的下一步。




== 步驟3：提供密碼

探索的最後一步、您必須輸入要新增至管理網域之儲存陣列的密碼。

. 針對每個探索到的陣列、在欄位中輸入其管理密碼。
. 單擊*完成*。
+
系統連線至指定的儲存陣列可能需要數分鐘的時間。當程序完成時、儲存陣列會新增至您的管理網域、並與所選群組相關聯（若有指定）。


