---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-discover-storage-arrays.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 若要在vCenter的儲存外掛程式中顯示及管理儲存資源、您必須探索網路中陣列的IP位址。 
---
= 探索儲存陣列
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要在vCenter的儲存外掛程式中顯示及管理儲存資源、您必須探索網路中陣列的IP位址。

.開始之前
* 您必須知道陣列控制器的網路IP位址（或位址範圍）。
* 必須正確設定和設定儲存陣列。
* 儲存陣列密碼必須使用System Manager的「存取管理」方塊來設定。


陣列探索是一個多步驟程序：

*  1: Enter network addresses for discovery
*  2: Resolve untrusted certificates during discovery
*  3: Provide passwords




== 步驟1：輸入網路位址進行探索

探索儲存陣列的第一步、是輸入單一IP位址或IP位址範圍、以便在本機子網路中搜尋。「新增/探索」功能會開啟精靈、引導您完成探索程序。

.步驟
. 從*管理*頁面、選取*新增/探索*。
+
此時會出現「輸入網路位址範圍」對話方塊。

. 執行下列其中一項：
+
** 若要探索一個陣列、請選取*探索單一儲存陣列*選項按鈕、然後輸入儲存陣列中其中一個控制器的IP位址。
** 若要探索多個儲存陣列、請選取*探索網路範圍內的所有儲存陣列*選項按鈕、然後輸入起始網路位址和結束網路位址、以搜尋整個本機子網路。


. 按一下*開始探索*。
+
當探索程序開始時、對話方塊會顯示探索到的儲存陣列。探索程序可能需要幾分鐘才能完成。

+

NOTE: 如果未找到可管理的陣列、請確認儲存陣列已正確連線至您的網路、且其指派的位址在範圍內。按一下「*新增探索參數*」以返回「新增/探索」頁面。

. 選取您要新增至管理網域之任何儲存陣列旁的核取方塊。
+
系統會對您要新增至管理網域的每個陣列執行認證檢查。您可能需要先解決不受信任憑證的任何問題、然後再繼續。

. 單擊*下一步*繼續執行精靈中的下一步。
. 如果儲存陣列擁有有效的憑證、請前往  3: Provide passwords。如果任何儲存陣列沒有有效的憑證、「解析自我簽署的憑證」對話方塊會出現、請前往  2: Resolve untrusted certificates during discovery。如果您要匯入CA簽署的憑證、請從探索對話方塊中取消、然後前往 link:vc-olh-import-certificates-for-arrays.html["匯入陣列的憑證"]。




== 步驟2：在探索期間解析不受信任的憑證

如有必要、您必須先解決任何憑證問題、然後再繼續探索程序。

在探索期間、如果任何儲存陣列顯示「不受信任的憑證」狀態、則會出現「解析自我簽署的憑證」對話方塊。您可以在此對話方塊中解析不受信任的憑證、也可以匯入CA憑證（請參閱 link:vc-olh-import-certificates-for-arrays.html["匯入陣列的憑證"]）。

.步驟
. 如果[解析自我簽署的憑證]對話方塊開啟，請檢閱顯示的不受信任憑證資訊。如需詳細資訊、您也可以按一下表格最末端的省略符號、然後從快顯功能表中選取*檢視*。
. 執行下列其中一項：
+
** 如果您信任已發現儲存陣列的連線、請按一下「*下一步*」、然後按一下「*是*」以確認並繼續精靈中的下一個卡片。自我簽署的憑證會標示為信任、儲存陣列也會新增至外掛程式。
** 如果您不信任儲存陣列的連線、請選取*「取消」*、然後在將每個儲存陣列的安全性憑證策略新增至外掛程式之前驗證。






== 步驟3：提供密碼

探索的最後一步、您必須輸入要新增至管理網域之儲存陣列的密碼。

.步驟
. 或者、如果您先前已為陣列設定群組、您可以使用下拉式功能表來為探索到的陣列選取群組。
. 針對每個探索到的陣列、在欄位中輸入其管理密碼。
. 單擊*完成*。



NOTE: 系統連線至指定的儲存陣列可能需要數分鐘的時間。

儲存陣列會新增至您的管理網域、並與選取的群組相關聯（若有指定）。


NOTE: 當您想要執行管理作業時、可以使用「Launch」（啟動）選項來開啟一或多個儲存陣列的瀏覽器型系統管理員。
