---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-host-creation-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 若要使用vCenter的儲存外掛程式來管理儲存設備、您必須探索或定義網路中的每個主機。 
---
= 主機建立總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要使用vCenter的儲存外掛程式來管理儲存設備、您必須探索或定義網路中的每個主機。主機是一種伺服器、可將I/O傳送至儲存陣列上的磁碟區。



== 自動與手動建立主機

建立主機是讓儲存陣列瞭解其連接的主機、以及允許I/O存取磁碟區所需的步驟之一。可以自動或手動建立主機。

* *自動*：主機內容代理程式（HCA）會啟動SCSI型（非NVMe型）主機的自動主機建立。HCA是一個公用程式、您可以在連接至儲存陣列的每個主機上安裝。安裝HCA的每個主機都會透過I/O路徑、將其組態資訊推送至儲存陣列控制器。根據主機資訊、控制器會自動建立主機及相關的主機連接埠、並設定主機類型。如有需要、您可以對主機組態進行任何其他變更。HCA執行自動偵測之後、會自動設定具有下列屬性的主機：
+
** 主機名稱衍生自主機的系統名稱。
** 與主機相關聯的主機識別碼連接埠。
** 主機的主機作業系統類型。





NOTE: 主機會建立為獨立主機、HCA不會自動建立或新增至主機叢集。

* *手動*-在手動建立主機期間、您可以從清單中選取主機連接埠識別碼、或手動輸入識別碼、藉此建立關聯。建立主機之後、如果您打算共用對磁碟區的存取權、可以將磁碟區指派給主機叢集或將其新增至主機叢集。




== 如何指派磁碟區

若要讓主機將I/O傳送至磁碟區、您必須將該磁碟區指派給該磁碟區。您可以在建立磁碟區時選取主機或主機叢集、也可以稍後將磁碟區指派給主機或主機叢集。主機叢集是一組主機。您可以建立主機叢集、以便輕鬆將相同的磁碟區指派給多個主機。

將磁碟區指派給主機是很靈活的、可讓您滿足特定的儲存需求。

* *獨立主機、而非主機叢集*的一部分、您可以將磁碟區指派給個別主機。該磁碟區只能由一部主機存取。
* *主機叢集*-您可以將磁碟區指派給主機叢集。該磁碟區可由主機叢集中的所有主機存取。
* *主機叢集內的主機*-您可以將磁碟區指派給屬於主機叢集一部分的個別主機。即使主機是主機叢集的一部分、也只能由個別主機存取磁碟區、而不能由主機叢集中的任何其他主機存取。


建立磁碟區時、系統會自動指派邏輯單元編號（LUN）。在I/O作業期間、LUN會做為主機與控制器之間的位址。您可以在建立磁碟區之後變更LUN。
