---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-storage-configuration-settings.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 將儲存組態從一個儲存陣列匯入其他儲存陣列。 
---
= 匯入儲存組態設定
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以將儲存組態從一個儲存陣列匯入其他儲存陣列。當您需要在網路中設定多個陣列時、這項批次作業可節省時間。

請確定：

* 儲存設備是在System Manager中針對您要作為來源的儲存陣列進行設定。
* 在System Manager中備份目標儲存陣列的現有組態（功能表：設定[系統>儲存儲存儲存陣列組態]）。
* 您已檢閱中複寫儲存組態的需求 link:vc-olh-import-settings-overview.html["匯入設定總覽"]。
* 來源陣列和目標陣列必須符合下列需求：
+
** 控制器所在的磁碟櫃必須相同。
** 機櫃ID必須相同。
** 擴充櫃必須裝入相同磁碟機類型的相同插槽。
** RBOD機箱類型必須相同。
** HIC（包括主機的資料保證功能）必須相同。
** 目標陣列必須處於最佳狀態。
** 目標陣列上的Volume容量大於來源陣列的容量。


* 您瞭解下列限制：
+
** 不支援從雙工匯入至單工組態、但允許從單工匯入至雙工。
** 來源陣列上的磁碟集區磁碟區容量大於或等於64 TB、將會妨礙目標上的匯入程序。




匯入的設定包括已設定的磁碟區（僅適用於完整磁碟區和非儲存庫磁碟區）、磁碟區群組、集區和熱備援磁碟機指派。

.步驟
. 在「管理」頁面中、按一下功能表：「動作」[Import Settings]（匯入設定）。
+
「匯入設定」精靈隨即開啟。

. 在Select Settings（選擇設置）對話框中，選擇* Storage configuration（*儲存配置）*，然後單擊* Next*（*下一步*）。
+
此時會開啟一個對話方塊、供您選取來源陣列。

. 在「選取來源」對話方塊中、選取含有您要匯入之設定的陣列、然後按一下「*下一步*」。
. 在「選取目標」對話方塊中、選取一或多個陣列以接收新設定。
+

NOTE: 韌體低於8.50的儲存陣列無法選取。此外、如果外掛程式無法與該陣列通訊（例如離線或有憑證、密碼或網路問題）、則陣列不會出現在此對話方塊中。

. 單擊*完成*。
+
「作業」頁面會顯示匯入作業的結果。如果作業失敗、您可以按一下其列以查看更多資訊。



現在、目標儲存陣列已設定與來源陣列相同的儲存組態。
