---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-is-shelf-loss-protection-and-drawer-loss-protection.html 
keywords:  
summary:  
---
= 什麼是機櫃損失保護和藥櫃損失保護？
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
機櫃遺失保護和藥櫃遺失保護是資源池和磁碟區群組的屬性、可讓您在單一機櫃或藥櫃故障時維持資料存取。



=== 機櫃損失保護

機櫃是包含磁碟機或磁碟機與控制器的機箱。機櫃遺失保護可確保在單一磁碟機櫃發生通訊完全中斷時、能夠存取資源池或磁碟區群組中磁碟區上的資料。通訊中斷的範例可能是磁碟機櫃電力中斷、或兩個I/O模組（IOM）故障。


NOTE: 如果磁碟機已在集區或磁碟區群組中故障、則無法保證磁碟櫃遺失保護。在這種情況下、失去磁碟機櫃的存取權、進而導致集區或磁碟區群組中的另一個磁碟機遺失資料。

機櫃損失保護的準則取決於保護方法、如下表所述。

|===
| 層級 | 機櫃損失保護標準 | 所需的磁碟櫃數量下限 


| 資源池 | 集區必須包含至少五個磁碟櫃的磁碟機、而且每個磁碟櫃中必須有相同數量的磁碟機。機櫃遺失保護不適用於大容量機櫃；如果您的系統含有大容量機櫃、請參閱「藥櫃遺失保護」。 | 5. 


| RAID 6 | 磁碟區群組在單一藥櫃中不包含兩個以上的磁碟機。 | 3. 


| RAID 3或RAID 5 | Volume群組中的每個磁碟機都位於不同的磁碟櫃中。 | 3. 


| RAID 1 | RAID 1配對中的每個磁碟機都必須位於不同的磁碟櫃中。 | 2. 


| RAID 0 | 無法達到機架遺失保護。 | 不適用 
|===


=== 藥櫃遺失保護

抽屜是您拉出以存取磁碟機的磁碟櫃之一。只有大容量的機櫃才有抽屜。藥櫃遺失保護可確保在單一藥櫃發生通訊中斷時、能夠存取資源池或磁碟區群組中磁碟區上的資料。通訊中斷的範例可能是藥櫃電力中斷、或藥櫃內的內部元件故障。


CAUTION: 如果磁碟機已在集區或磁碟區群組中故障、則無法保證藥櫃遺失保護。在這種情況下、無法存取藥櫃（以及池或Volume群組中的另一個磁碟機）會導致資料遺失。

藥櫃遺失保護的條件取決於保護方法、如下表所述：

|===
| 層級 | 藥櫃損失保護條件 | 所需的藥櫃數量下限 


| 資源池 | 資源池候選裝置必須包含所有藥櫃的磁碟機、而且每個藥櫃中的磁碟機數量必須相等。集區必須包含至少五個抽屜的磁碟機、而且每個抽屜中的磁碟機數量必須相等。當集區包含15、20、25、30、35、 40、45、50、55或60個磁碟機。初始建立之後、可以將5的倍數遞增量新增至資源池。 | 5. 


| RAID 6 | 磁碟區群組在單一藥櫃中不包含兩個以上的磁碟機。 | 3. 


| RAID 3或5 | 磁碟區群組中的每個磁碟機都位於獨立的磁碟櫃中 | 3. 


| RAID 1 | 鏡射配對中的每個磁碟機都必須位於獨立的抽屜中。 | 2. 


| RAID 0 | 無法達到藥櫃損失保護。 | 不適用 
|===