---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-storage.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 先建立特定應用程式類型的工作負載、以建立儲存設備。接下來、您可以建立具有類似基礎Volume特性的磁碟區、以新增儲存容量至工作負載。 
---
= 建立儲存設備
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在vCenter的儲存外掛程式中、您可以先建立特定應用程式類型的工作負載、以建立儲存設備。接下來、您可以建立具有類似基礎Volume特性的磁碟區、以新增儲存容量至工作負載。



== 步驟1：建立工作負載

工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。

對於某些應用程式、系統會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。

系統僅建議針對下列應用程式類型進行最佳化的Volume組態：

* Microsoft SQL Server
* Microsoft Exchange Server
* 視訊監控
* VMware ESXi（適用於與虛擬機器檔案系統搭配使用的磁碟區）


.步驟
. 在「Manage（管理）」頁面中、選取儲存陣列。
. 選取功能表：資源配置[管理磁碟區]。
. 選取功能表：Create [Workload。
+
此時會出現Create Application Workload對話方塊。

. 使用下拉式清單選取您要建立工作負載的應用程式類型、然後輸入工作負載名稱。
. 按一下「 * 建立 * 」。




== 步驟2：建立磁碟區

您可以建立磁碟區、將儲存容量新增至應用程式專屬的工作負載、並使建立的磁碟區對特定主機或主機叢集可見。

大多數的應用程式類型預設為使用者定義的Volume組態、而其他類型則在建立Volume時套用智慧組態。例如、如果您要為Microsoft Exchange應用程式建立磁碟區、系統會詢問您需要多少信箱、平均信箱容量需求為何、以及您想要的資料庫複本數量。系統會使用此資訊為您建立最佳Volume組態、並可視需要加以編輯。

您可以從功能表：資源配置[管理磁碟區>建立>磁碟區]或功能表：資源配置[設定資源池和磁碟區群組>建立>磁碟區]建立磁碟區。任一選擇的程序都相同。

建立Volume的程序是多步驟的程序。



=== 步驟2a：選取磁碟區的主機

在第一步中、您可以為磁碟區選取特定的主機或主機叢集、也可以選擇稍後指派主機。

請確定：

* 已定義有效的主機或主機叢集（前往功能表：資源配置[設定主機]）。
* 已為主機定義主機連接埠識別碼。
* 如果您打算建立啟用DA的磁碟區、則主機連線必須支援Data Assurance（DA）。如果儲存陣列中控制器上的任何主機連線不支援DA、則相關主機無法存取啟用DA的磁碟區上的資料。


指派磁碟區時、請謹記以下準則：

* 主機的作業系統可以對主機可存取的磁碟區數量有特定限制。當您建立要供特定主機使用的磁碟區時、請謹記此限制。
* 您可以為儲存陣列中的每個磁碟區定義一個指派。
* 指派的磁碟區會在儲存陣列的控制器之間共用。
* 主機或主機叢集無法使用相同的邏輯單元編號（LUN）兩次來存取磁碟區。您必須使用唯一的LUN。
* 如果您想加速建立磁碟區的程序、可以跳過主機指派步驟、以便離線初始化新建立的磁碟區。



NOTE: 如果您嘗試將磁碟區指派給主機叢集、而該磁碟區與已建立的主機叢集指派衝突、則指派給主機的磁碟區將會失敗。

.步驟
. 在「Manage（管理）」頁面中、選取儲存陣列。
. 選取功能表：資源配置[管理磁碟區]。
. 選取功能表：Create [Volumes]（建立[磁碟區]）
+
此時會出現選取主機對話方塊。

. 從下拉式清單中、選取您要指派磁碟區的特定主機或主機叢集、或選擇稍後指派主機或主機叢集。
. 若要繼續選取主機或主機叢集的磁碟區建立順序、請按一下*「Next（下一步）」。*
+
此時會出現Select Workload對話方塊。





=== 步驟2b：選取磁碟區的工作負載

在第二步中、您可以選取工作負載、針對特定應用程式（例如VMware）自訂儲存陣列組態。

此工作說明如何為工作負載建立磁碟區。通常、工作負載包含具有類似特性的磁碟區、這些磁碟區會根據工作負載所支援的應用程式類型進行最佳化。您可以在此步驟中定義工作負載、也可以選取現有的工作負載。

請謹記以下準則：

* 使用應用程式專屬的工作負載時、系統建議使用最佳化的Volume組態、以將應用程式工作負載I/O與應用程式執行個體的其他流量之間的爭用降至最低。您可以檢閱建議的Volume組態、然後使用「Add / Edit Volumes（新增/編輯磁碟區）」對話方塊（下一步提供）來編輯、新增或刪除系統建議的磁碟區和特性。
* 使用其他應用程式類型時、您可以使用「新增/編輯磁碟區」對話方塊（下一步提供）手動指定磁碟區組態。


.步驟
. 執行下列其中一項：
+
** 選取*為現有工作負載建立磁碟區*選項、然後從下拉式清單中選取工作負載。
** 選取*建立新的工作負載*選項、為支援的應用程式或「其他」應用程式定義新的工作負載、然後執行下列步驟：
+
*** 從下拉式清單中、選取您要建立新工作負載的應用程式名稱。如果您要在此儲存陣列上使用的應用程式未列出、請選取其中一個「其他」項目。
*** 輸入您要建立的工作負載名稱。




. 單擊 * 下一步 * 。
. 如果您的工作負載與支援的應用程式類型相關聯、請輸入要求的資訊；否則、請前往下一步。




=== 步驟2c：新增或編輯磁碟區

在第三步中、您可以定義Volume組態。

.開始之前
* 資源池或磁碟區群組必須有足夠的可用容量。
* Volume群組中允許的最大Volume數為256。
* 集區中允許的最大磁碟區數取決於儲存系統機型：
+
** 2、048個磁碟區（EF600和E5700系列）
** 1、024個磁碟區（EF300）
** 512個磁碟區（E2800系列）


* 若要建立啟用Data Assurance（DA）的Volume、您打算使用的主機連線必須支援DA。
+
** 如果您想要建立啟用DA的磁碟區、請選取具有DA功能的資源池或磁碟區群組（請在「資源池和磁碟區群組候選項目」表中尋找「DA」旁邊的*「Yes」（是）。
** 在資源池和Volume群組層級提供DA功能。DA保護會檢查並修正資料經由控制器向下傳輸到磁碟機時可能發生的錯誤。為新磁碟區選取具有DA功能的集區或磁碟區群組、可確保偵測並修正任何錯誤。
** 如果儲存陣列中控制器上的任何主機連線不支援DA、則相關主機無法存取啟用DA的磁碟區上的資料。


* 若要建立啟用安全功能的磁碟區、必須為儲存陣列建立安全金鑰。
+
** 如果您想要建立啟用安全功能的Volume、請選取安全功能的資源池或Volume群組（請在Pool and Volume Group候選資料表的「Secure Capable（安全功能）」旁尋找「Yes（是）」）。
** 磁碟機安全功能會顯示在集區和磁碟區群組層級。具有安全功能的磁碟機可防止未獲授權存取實體從儲存陣列移除的磁碟機上的資料。啟用安全功能的磁碟機會在寫入期間加密資料、並使用獨特的加密金鑰在讀取期間解密資料。
** 集區或磁碟區群組可同時包含具有安全功能和不安全功能的磁碟機、但所有磁碟機必須具備安全功能、才能使用其加密功能。


* 若要建立資源配置的磁碟區、所有磁碟機都必須是NVMe磁碟機、並具有取消分配或未寫入的邏輯區塊錯誤（DULBE）選項。


您可以從合格的資源池或Volume群組建立磁碟區、這些資源會顯示在「新增/編輯磁碟區」對話方塊中。針對每個合格的資源池和磁碟區群組、會顯示可用磁碟機數量和可用總容量。

對於某些應用程式專屬的工作負載、每個合格的資源池或Volume群組會根據建議的Volume組態顯示建議的容量、並顯示GiB中的剩餘可用容量。對於其他工作負載、當您將磁碟區新增至資源池或磁碟區群組、並指定報告的容量時、就會顯示建議的容量。

.步驟
. 根據您在上一步中選擇的是其他工作負載或應用程式專屬工作負載、選擇下列其中一項動作：
+
** *其他*-在您要用來建立一或多個磁碟區的每個集區或磁碟區群組中、按一下*「新增磁碟區」。
+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
Volume名稱
 a| 
磁碟區在建立磁碟區順序期間會指派預設名稱。您可以接受預設名稱、或提供更具說明性的名稱、以指示儲存在磁碟區中的資料類型。



 a| 
報告容量
 a| 
定義新Volume的容量和要使用的容量單位（mib、GiB或TiB）。對於大型磁碟區、最小容量為1個mib、最大容量則取決於集區或Volume群組中磁碟機的數量和容量。請記住、複製服務（快照映像、快照磁碟區、磁碟區複本和遠端鏡像）也需要儲存容量、因此、 請勿將所有容量分配給標準磁碟區。資源池中的容量會以4GiB為增量分配。任何非4GiB倍數的容量都會被分配、但無法使用。若要確保整個容量都可使用、請以4GiB為單位遞增指定容量。如果存在不可用的容量、則重新取得容量的唯一方法是增加磁碟區的容量。



 a| 
Volume區塊大小（僅限EF300和EF600）
 a| 
顯示可為Volume建立的區塊大小：

*** 512–512位元組
*** 4K–4、096位元組




 a| 
區段大小
 a| 
顯示區段大小調整的設定、僅適用於Volume群組中的磁碟區。您可以變更區段大小以最佳化效能。*允許的區段大小轉換*-系統會決定允許的區段大小轉換。無法在下拉式清單中使用不適當的從目前區段大小轉換的區段大小。允許的轉換通常是目前區段大小的兩倍或一半。例如、如果目前的Volume區段大小為32 KiB、則允許新的Volume區段大小為16 KiB或64 KiB。*啟用SSD快取的磁碟區*-您可以為啟用SSD快取的磁碟區指定4-KiB區段大小。請務必針對啟用SSD快取的磁碟區選取4-KiB區段大小、以便處理小區塊I/O作業（例如、16個KiB I/O區塊大小或更小）。如果您選取4 KiB做為啟用SSD快取的磁碟區的區段大小、以處理大量區塊循序作業、效能可能會受到影響。*變更區段大小的時間*-變更磁碟區區區段大小的時間長短取決於下列變數：

*** 主機的I/O負載
*** 磁碟區的修改優先順序
*** Volume群組中的磁碟機數量
*** 磁碟機通道數
*** 儲存陣列控制器的處理能力


當您變更磁碟區的區段大小時、I/O效能會受到影響、但您的資料仍可繼續使用。



 a| 
安全功能
 a| 
*是*只有當集區或磁碟區群組中的磁碟機具有安全功能時、才會顯示在「安全功能」旁邊。磁碟機安全功能可防止未獲授權存取從儲存陣列中實際移除的磁碟機上的資料。此選項僅在磁碟機安全功能已啟用、且已為儲存陣列設定安全金鑰時可用。集區或磁碟區群組可同時包含具有安全功能和不安全功能的磁碟機、但所有磁碟機必須具備安全功能、才能使用其加密功能。



 a| 
大
 a| 
*是*僅當集區或磁碟區群組中的磁碟機支援資料保證（DA）時、才會顯示在「DA」旁邊。DA可提升整個儲存系統的資料完整性。DA可讓儲存陣列檢查資料經由控制器向下傳輸到磁碟機時可能發生的錯誤。將DA用於新磁碟區可確保偵測到任何錯誤。



 a| 
資源已配置（僅限EF300和EF600）
 a| 
*是*僅當磁碟機支援此選項時、才會在「資源已配置」旁顯示。資源資源配置是EF300和EF600儲存陣列的一項功能、可讓磁碟區立即投入使用、而無需背景初始化程序。

|===
====
** *應用程式專屬工作負載*：按一下*「下一步」*接受系統建議的所選工作負載磁碟區與特性、或按一下*「編輯磁碟區」*、變更、新增或刪除所選工作負載的系統建議磁碟區與特性。
+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
Volume名稱
 a| 
磁碟區在建立磁碟區順序期間會指派預設名稱。您可以接受預設名稱、或提供更具說明性的名稱、以指示儲存在磁碟區中的資料類型。



 a| 
報告容量
 a| 
定義新Volume的容量和要使用的容量單位（mib、GiB或TiB）。對於大型磁碟區、最小容量為1個mib、最大容量則取決於集區或Volume群組中磁碟機的數量和容量。請記住、複製服務（快照映像、快照磁碟區、磁碟區複本和遠端鏡像）也需要儲存容量、因此、 請勿將所有容量分配給標準磁碟區。資源池中的容量會以4-GiB為增量分配。任何非4 GiB倍數的容量都會被分配、但無法使用。若要確保整個容量都可使用、請以4-GiB為單位指定容量。如果存在不可用的容量、則重新取得容量的唯一方法是增加磁碟區的容量。



 a| 
Volume類型
 a| 
Volume類型表示為應用程式專屬工作負載所建立的Volume類型。



 a| 
Volume區塊大小（僅限EF300和EF600）
 a| 
顯示可為Volume建立的區塊大小：

*** 512 - 512位元組
*** 4K - 4、096位元組




 a| 
區段大小
 a| 
顯示區段大小調整的設定、僅適用於Volume群組中的磁碟區。您可以變更區段大小以最佳化效能。*允許的區段大小轉換*-系統會決定允許的區段大小轉換。無法在下拉式清單中使用不適當的從目前區段大小轉換的區段大小。允許的轉換通常是目前區段大小的兩倍或一半。例如、如果目前的Volume區段大小為32 KiB、則允許新的Volume區段大小為16 KiB或64 KiB。*啟用SSD快取的磁碟區*-您可以為啟用SSD快取的磁碟區指定4-KiB區段大小。請務必針對啟用SSD快取的磁碟區選取4-KiB區段大小、以便處理小區塊I/O作業（例如、16個KiB I/O區塊大小或更小）。如果您選取4 KiB做為啟用SSD快取的磁碟區的區段大小、以處理大量區塊循序作業、效能可能會受到影響。*變更區段大小的時間*-變更磁碟區區區段大小的時間長短取決於下列變數：

*** 主機的I/O負載
*** 磁碟區的修改優先順序
*** Volume群組中的磁碟機數量
*** 磁碟機通道數
*** 儲存陣列控制器的處理能力


當您變更磁碟區的區段大小時、I/O效能會受到影響、但您的資料仍可繼續使用。



 a| 
安全功能
 a| 
*是*只有當集區或磁碟區群組中的磁碟機具有安全功能時、才會顯示在「安全功能」旁邊。磁碟機安全性可防止未獲授權存取從儲存陣列實體移除的磁碟機上的資料。此選項僅在磁碟機安全功能已啟用、且已為儲存陣列設定安全金鑰時可用。集區或磁碟區群組可同時包含具有安全功能和不安全功能的磁碟機、但所有磁碟機必須具備安全功能、才能使用其加密功能。



 a| 
大
 a| 
*是*僅當集區或磁碟區群組中的磁碟機支援資料保證（DA）時、才會顯示在「DA」旁邊。DA可提升整個儲存系統的資料完整性。DA可讓儲存陣列檢查資料經由控制器向下傳輸到磁碟機時可能發生的錯誤。將DA用於新磁碟區可確保偵測到任何錯誤。



 a| 
資源已配置（僅限EF300和EF600）
 a| 
*是*僅當磁碟機支援此選項時、才會在「資源已配置」旁顯示。資源資源配置是EF300和EF600儲存陣列的一項功能、可讓磁碟區立即投入使用、而無需背景初始化程序。

|===
====


. 若要繼續選取應用程式的磁碟區建立順序、請按一下「*下一步*」。




=== 步驟2D：檢閱Volume組態

在最後一個步驟中、您將檢閱您要建立的磁碟區摘要、並進行任何必要的變更。

.步驟
. 檢閱您要建立的磁碟區。若要進行變更、請按一下*上一步*。
. 當您對磁碟區組態感到滿意時、請按一下*完成*。


.完成後
* 在vSphere Client中、為磁碟區建立資料存放區。
* 在應用程式主機上執行任何必要的作業系統修改、以便應用程式使用該磁碟區。
* 執行主機型的「hot_add」公用程式或作業系統專用的公用程式（可從協力廠商取得）、然後執行「simmdevices」公用程式、將磁碟區名稱與主機儲存陣列名稱建立關聯。
+
「hot_add」公用程式和「Mdevices'公用程式都包含在「Msutils」套件中。「ututils」套件是一組公用程式、用來驗證主機從儲存陣列看到的內容。它是SANtricity 包含在整個軟件安裝過程中的一部分。


