---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-host-cluster.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 當兩個或多個主機需要I/O存取相同的磁碟區時、您可以建立一個主機叢集。 
---
= 在 SANtricity Storage Plugin for vCenter 中建立主機叢集
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
當兩個或多個主機需要I/O存取相同的磁碟區時、您可以建立一個主機叢集。

.關於這項工作
建立主機叢集時、請謹記下列準則：

* 除非有兩個以上的主機可供建立叢集、否則此作業不會啟動。
* 主機叢集中的主機可以有不同的作業系統（異質）。
* 主機叢集中的NVMe主機無法與非NVMe主機混合使用。
* 若要建立啟用Data Assurance（DA）的Volume、您打算使用的主機連線必須支援DA。
+
如果儲存陣列中控制器上的任何主機連線不支援DA、則相關主機無法存取啟用DA的磁碟區上的資料。

* 如果您選擇的名稱已在使用中、則此作業不會成功。
* 名稱長度不得超過30個字元。


.步驟
. 在「Manage（管理）」頁面中、選取具有主機連線的儲存陣列。
. 選取功能表：資源配置[設定主機]。
+
此時會開啟「設定主機」頁面。

. 選取功能表：「Create[主機叢集]」。
+
此時會出現Create Host Cluster（建立主機叢集）對話方塊。

. 視需要選取主機叢集的設定。
+
|===
| 設定 | 說明 


| 名稱 | 輸入新主機叢集的名稱。 


| 選取「主機」以共用磁碟區存取 | 從下拉式清單中選取兩個以上的主機。清單中只會顯示尚未加入主機叢集的主機。 
|===
. 按一下「 * 建立 * 」。
+
如果選取的主機附加至具有不同資料保證（DA）功能的介面類型、則會出現一個對話方塊、顯示主機叢集上無法使用DA的訊息。此不可用性可防止將啟用DA的磁碟區新增至主機叢集。選擇* Yes *（是*）繼續、或選擇* No *（否*）取消。

+
DA可提升整個儲存系統的資料完整性。DA可讓儲存陣列檢查資料在主機和磁碟機之間移動時可能發生的錯誤。將DA用於新磁碟區可確保偵測到任何錯誤。



.結果
新的主機叢集會出現在表格中、並在表格下方的列中顯示指派的主機。

.完成後
您必須將磁碟區指派給主機叢集、以便用於I/O作業。前往 link:vc-olh-assign-volumes-to-hosts.html["將磁碟區指派給主機"]。
