---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-add-capacity-to-a-pool-or-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 新增磁碟機以擴充現有資源池或磁碟區群組中的可用容量。 
---
= 新增容量至資源池或磁碟區群組
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以新增磁碟機、以擴充現有資源池或磁碟區群組中的可用容量。

.開始之前
* 磁碟機必須處於最佳狀態。
* 磁碟機必須具有相同的磁碟機類型（HDD或SSD）。
* 集區或磁碟區群組必須處於最佳狀態。
* 如果集區或磁碟區群組包含所有具有安全功能的磁碟機、請僅新增具備安全功能的磁碟機、以繼續使用具有安全功能的磁碟機的加密功能。


安全的磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。

在此工作中、您可以新增可用容量以納入資源池或磁碟區群組。您可以使用此可用容量來建立其他磁碟區。在此作業期間、磁碟區中的資料仍可存取。

對於集區、一次最多可新增60個磁碟機。對於Volume群組、一次最多可新增兩個磁碟機。如果您需要新增的磁碟機數量超過上限、請重複此程序。（集區所包含的磁碟機數量不得超過儲存陣列的上限。）


NOTE: 新增磁碟機之後、您的保留容量可能需要增加。擴充作業之後、您應該考慮增加保留容量。


NOTE: 避免使用資料保證（DA）的磁碟機、將容量新增至不具備DA功能的資源池或磁碟區群組。集區或磁碟區群組無法利用具有DA功能的磁碟機功能。在此情況下、請考慮使用不具備DA功能的磁碟機。

.步驟
. 從「Manage（管理）」頁面中、選取具有Pool（資源池）或Volume（磁碟區）群組的儲存陣列。
. 選取功能表：資源配置[設定資源池和磁碟區群組]。
. 選取您要新增磁碟機的集區或磁碟區群組、然後按一下*「Add Capacity」（新增容量）*。
+
此時將出現Add Capacity（添加容量）對話框。只會顯示與集區或磁碟區群組相容的未指派磁碟機。

. 在*選取磁碟機以新增容量...*下、選取您要新增至現有資源池或磁碟區群組的一或多個磁碟機。
+
控制器韌體會排列未指派的磁碟機、並在頂端列出最佳選項。新增至資源池或磁碟區群組的可用總容量會顯示在*選取的總容量*清單下方。

+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
機櫃
 a| 
表示磁碟機的機櫃位置。



 a| 
Bay
 a| 
指示磁碟機的機櫃位置



 a| 
容量（GiB）
 a| 
表示磁碟機容量。

** 如果可能、請選取容量等於集區或Volume群組中目前磁碟機容量的磁碟機。
** 如果您必須新增容量較小的未指派磁碟機、請注意、目前位於集區或磁碟區群組中的每個磁碟機的可用容量都會減少。因此、整個集區或磁碟區群組的磁碟機容量相同。
** 如果您必須新增容量較大的未指派磁碟機、請注意、您新增的未指派磁碟機的可用容量會減少、使其符合集區或磁碟區群組中磁碟機的目前容量。




 a| 
安全功能
 a| 
指出磁碟機是否具備安全功能。

** 您可以使用「磁碟機安全性」功能來保護集區或磁碟區群組、但所有磁碟機都必須具備安全功能才能使用此功能。
** 您可以建立集區或磁碟區群組、混合使用安全功能和不安全功能的磁碟機、但無法啟用「磁碟機安全性」功能。
** 具有所有安全功能磁碟機的集區或Volume群組、即使未使用加密功能、也無法接受不安全的磁碟機來進行備援或擴充。
** 安全的磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。FIPS磁碟機可以是140-2或140-3級、而層級140-2則是較高的安全層級。如果您混合選擇140-2和140-2層級磁碟機、則集區或Volume群組將會以較低的安全性層級（140-2）運作。




 a| 
DA能力
 a| 
指出磁碟機是否具備資料保證（DA）功能。

** 不建議使用不具備資料保證（DA）功能的磁碟機、將容量新增至具有DA功能的資源池或磁碟區群組。集區或磁碟區群組不再具有DA功能、而且您不再可以在集區或磁碟區群組中新建立的磁碟區上啟用DA。
** 不建議使用資料保證（DA）功能的磁碟機、將容量新增至不支援DA的資源池或磁碟區群組、因為該資源池或磁碟區群組無法利用具有DA功能的磁碟機（磁碟機屬性不相符）的功能。在此情況下、請考慮使用不具備DA功能的磁碟機。




 a| 
具備DUBE功能
 a| 
指出磁碟機是否有取消分配或未寫入的邏輯區塊錯誤（DULBE）選項。DULBE是NVMe磁碟機的選項、可讓EF300或EF600儲存陣列支援資源配置的磁碟區。

|===
====
. 按一下「 * 新增 * 」。
+
如果您要將磁碟機新增至集區或磁碟區群組、如果您選取的磁碟機導致集區或磁碟區群組不再具有下列一或多個屬性、則會出現確認對話方塊：

+
** 機櫃損失保護
** 藥櫃遺失保護
** 全磁碟加密功能
** 資料保證功能
** DUBE功能


. 若要繼續、請按一下*是*；否則請按一下*取消*。


將未指派的磁碟機新增至集區或磁碟區群組之後、會重新分配集區或磁碟區群組中每個磁碟區的資料、以納入其他磁碟機。
