---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-upgrade-santricity-os.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 使用最新的軟體和NVSRAM,升級一或多個儲存陣列以確保您擁有所有最新的功能和錯誤修復。 
---
= 升級SANtricity 作業系統
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用最新的軟體和NVSRAM,升級一或多個儲存陣列以確保您擁有所有最新的功能和錯誤修復。控制器NVSRAM-是控制器檔案、可指定控制器的預設設定。

請確定：

* 執行外掛程式的主機系統上提供最新SANtricity 的支援作業系統檔案。
* 您知道現在或之後是否要啟動軟體升級。您可以選擇稍後啟動、原因如下：
+
** *每天的時間*-啟動軟體可能需要很長時間、因此您可能需要等待I/O負載變輕。控制器會在啟動期間容錯移轉、因此在升級完成之前、效能可能會比平常低。
** *套件類型*：在升級其他儲存陣列上的檔案之前、您可能會想要在一個儲存陣列上測試新的作業系統軟體。





CAUTION: *資料遺失的風險或儲存陣列受損的風險*-升級期間請勿變更儲存陣列。維持儲存陣列的電力。

.步驟
. 如果您的儲存陣列只包含一個控制器、或是未使用多重路徑驅動程式、請停止儲存陣列的I/O活動、以避免應用程式錯誤。如果您的儲存陣列有兩個控制器、而且安裝了多重路徑驅動程式、則不需要停止I/O活動。
. 從主檢視畫面選取*管理*、然後選取您要升級的一或多個儲存陣列。
. 選擇功能表：Upgrade Center[升級> SANtricity 支援作業系統>軟體]。
+
此時會出現「Upgrade SANtricity VMware OS軟體」頁面。

. 從SANtricity Support網站下載最新的支援作業系統軟體套件至您的本機電腦。
+
.. 按一下「新增檔案至軟體儲存庫」
.. 按一下連結以尋找SANtricity 最新的更新版作業系統下載。
.. 按一下*下載最新版本*連結。
.. 請依照其餘指示、將作業系統檔案和NVSRAM/檔案下載到您的本機機器。
+

NOTE: 8.42版及更新版本需要數位簽署的韌體。如果您嘗試下載未簽署的韌體、將會顯示錯誤、且下載會中止。



. 選取您要用來升級控制器的OS軟體檔案和NVSRAM..
+
.. 從下拉式清單中、選取您下載到本機電腦的OS檔案。
+
如果有多個檔案可用、檔案會從最新日期排序至最舊日期。

+

NOTE: 軟體儲存庫會列出與外掛程式相關的所有軟體檔案。如果您沒有看到要使用的檔案、可以按一下「*新增檔案至軟體儲存庫*」連結、瀏覽至您要新增的OS檔案所在的位置。

.. 從*選取一個NVSRAM*下拉式清單中、選取您要使用的控制器檔案。
+
如果有多個檔案、檔案會從最新日期排序至最舊日期。



. 在「相容儲存陣列」表中、檢閱與您所選OS軟體檔案相容的儲存陣列、然後選取您要升級的陣列。
+
** 您在「管理」檢視中選取且與所選韌體檔案相容的儲存陣列、預設會在「相容的儲存陣列」表格中選取。
** 無法以所選韌體檔案更新的儲存陣列無法在相容的儲存陣列表中選取、狀態*不相容*會顯示此資訊。


. （可選）要將軟件文件傳輸到儲存陣列而不進行激活，請選中*將操作系統軟件傳輸到儲存陣列、將其標記爲分段並在稍後時間激活*複選框。
. 按一下* Start*。
. 視您選擇現在或之後啟動而定、請執行下列其中一項：
+
** 輸入「transfer」以確認您要在您選擇要升級的陣列上傳輸建議的作業系統軟體版本、然後按一下「* Transfit*」。若要啟動傳輸的軟體、請選取功能表：Upgrade Center[啟動分段SANtricity 式作業系統軟體]。
** 鍵入「升級」以確認您要傳輸並啟動所選要升級陣列上建議的作業系統軟體版本、然後按一下「*升級*」。
+
系統會將軟體檔案傳輸至您選擇要升級的每個儲存陣列、然後啟動重新開機以啟動該檔案。

+
升級作業期間會執行下列動作：

** 升級前的狀況檢查會在升級程序中執行。升級前的健全狀況檢查會評估所有儲存陣列元件、以確保升級能夠繼續進行。
** 如果儲存陣列的任何健全狀況檢查失敗、升級就會停止。您可以按一下省略符號（…） 然後選取*儲存記錄*以檢閱錯誤。您也可以選擇置換健全狀況檢查錯誤、然後按一下*繼續*繼續升級。
** 您可以在升級前狀況檢查之後取消升級作業。


. （可選）升級完成後、您可以按一下省略符號（…）、查看特定儲存陣列的升級項目清單。 然後選取*儲存記錄*。
+
檔案會以「升級記錄-<日期>」的名稱儲存在瀏覽器的「下載」資料夾中。JSON'。


