---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-pools-and-volume-group-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 若要配置儲存設備、您可以建立一個集區或磁碟區群組、其中包含您要在儲存陣列中使用的硬碟機（HDD）或固態磁碟（SSD）磁碟機。 
---
= 資源池與磁碟區群組總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要在vCenter的儲存外掛程式中配置儲存設備、您可以建立一個集區或Volume群組、其中包含您要在儲存陣列中使用的硬碟機（HDD）或固態磁碟（SSD）磁碟機。



== 資源配置

實體硬體已配置至邏輯元件、以便組織及輕鬆擷取資料。支援兩種群組類型：

* 資源池
* Volume群組


集區和磁碟區群組是儲存陣列中的最上層儲存單元：它們會將磁碟機的容量劃分為可管理的磁碟區。在這些邏輯區中、是儲存資料的個別磁碟區或LUN。

部署儲存系統時、第一步是透過下列方式、將可用的磁碟機容量呈現給各個主機：

* 建立具有足夠容量的集區或Volume群組
* 將符合效能需求的磁碟機數量新增至集區或磁碟區群組
* 選取所需的RAID保護層級（若使用Volume群組）、以符合特定的業務需求


您可以在同一個儲存系統上擁有資源池或磁碟區群組、但磁碟機不能是多個資源池或磁碟區群組的一部分。然後使用資源池或磁碟區群組上的空間、建立呈現給主機的I/O磁碟區。



== 資源池

集區的設計可將實體硬碟機集合成大型儲存空間、並為其提供增強的RAID保護。集區會從指派給集區的磁碟機總數中建立許多虛擬RAID集區、並在所有參與的磁碟機之間平均分散資料。如果磁碟機遺失或新增、系統會在所有作用中磁碟機之間動態重新平衡資料。

集區可作為另一個RAID層級、虛擬化基礎RAID架構、以最佳化執行重建、磁碟擴充及處理磁碟機遺失等工作時的效能與靈活度。系統會在8+2組態中自動將RAID層級設為6（八個資料磁碟加上兩個同位元檢查磁碟）。



=== 磁碟機配對

您可以選擇HDD或SSD用於資源池；不過、如同磁碟區群組、資源池中的所有磁碟機都必須使用相同的技術。控制器會自動選取要包含哪些磁碟機、因此您必須確保擁有足夠數量的磁碟機來搭配您選擇的技術。



=== 管理故障磁碟機

集區的最小容量為11個磁碟機；不過、在磁碟機故障時、一個磁碟機的容量值會保留給備用容量。此備用容量稱為「保留容量」。

建立集區時、會保留一定容量以供緊急使用。此容量是以多個磁碟機來表示、但實際實作卻分散在整個磁碟機資源池中。保留的預設容量量是根據集區中的磁碟機數量而定。

建立集區之後、您可以將保留容量值變更為更多或更少容量、甚至將其設為無保留容量（0個磁碟機的價值）。可保留的最大容量（以磁碟機數量表示）為10、但可用容量可能會較少、視集區中的磁碟機總數而定。



== Volume群組

Volume群組定義如何將儲存系統中的容量分配給磁碟區。磁碟機會組織成RAID群組、而磁碟區則位於RAID群組中的各個磁碟機。因此、Volume群組組組態設定會識別哪些磁碟機屬於群組、以及使用的RAID層級。

建立磁碟區群組時、控制器會自動選取要納入群組的磁碟機。您必須手動選擇群組的RAID層級。Volume群組的容量是您選取的磁碟機總數乘以其容量。



=== 磁碟機配對

您必須符合Volume群組中的磁碟機大小和效能。如果Volume群組中有較小和較大的磁碟機、則所有磁碟機都會被視為最小容量。如果磁碟區群組中的磁碟機速度較慢且速度較快、則所有磁碟機都會以最慢的速度辨識。這些因素會影響儲存系統的效能和整體容量。

您無法混用不同的磁碟機技術（HDD和SSD磁碟機）。RAID 3、5和6最多限制為30個磁碟機。RAID 1和RAID 10使用鏡射、因此這些磁碟區群組必須擁有偶數個磁碟。



=== 管理故障磁碟機

磁碟區群組使用熱備援磁碟機做為待命、以防磁碟機在磁碟區群組所包含的RAID 1/10、RAID 3、RAID 5或RAID 6磁碟區中故障。熱備援磁碟機不含資料、可為儲存陣列新增另一個層級的備援功能。

如果儲存陣列中的磁碟機故障、則熱備援磁碟機將自動取代故障磁碟機、而不需要實體交換。如果熱備援磁碟機在磁碟機故障時可用、則控制器會使用備援資料、將故障磁碟機的資料重新建構至熱備援磁碟機。



== 決定要使用集區或磁碟區群組



=== 選擇資源池

* 如果您需要更快的磁碟機重建和簡化的儲存管理、以及/或具有高度隨機的工作負載、
* 如果您想要在組成集區的一組磁碟機上隨機散佈每個磁碟區的資料、則無法設定或變更集區的RAID層級或集區中的磁碟區。集區使用RAID層級6。




=== 選擇一個Volume群組

* 如果您需要最大的系統頻寬、調整儲存設定的能力、以及高度連續的工作負載。
* 如果您想要根據RAID層級、將資料分散到各個磁碟機。您可以在建立磁碟區群組時指定RAID層級。
* 如果您想要在組成Volume群組的磁碟機集合中、依序寫入每個磁碟區的資料。



NOTE: 由於資源池可與Volume群組共存、因此儲存陣列可同時包含資源池和Volume群組。



== 自動與手動建立資源池

視儲存組態而定、您可以允許系統自動建立集區、也可以自行手動建立集區。資源池是一組邏輯分組的磁碟機。

在建立及管理資源池之前、請先檢閱下列各節、瞭解如何自動建立資源池、以及何時需要手動建立資源池。



=== 自動建立

當系統偵測到儲存陣列中未指派的容量時、系統會在偵測到儲存陣列中未指派的容量時、啟動自動建立資源池。它會自動提示您建立一個或多個資源池、或將未指派的容量新增至現有資源池、或同時新增至兩者。

當下列其中一項條件成立時、就會自動建立集區：

* 儲存陣列中不存在集區、而且有足夠的類似磁碟機可建立新的集區。
* 新的磁碟機會新增至至少有一個集區的儲存陣列。集區中的每個磁碟機必須為相同的磁碟機類型（HDD或SSD）、而且容量必須相似。系統會提示您完成下列工作：
* 如果有足夠數量的磁碟機屬於這些類型、請建立單一集區。
* 如果未指派的容量包含不同的磁碟機類型、請建立多個資源池。
* 如果儲存陣列中已定義集區、請將磁碟機新增至現有集區、然後將相同磁碟機類型的新磁碟機新增至集區。
* 將相同磁碟機類型的磁碟機新增至現有的集區、如果新磁碟機類型不同、請使用其他磁碟機類型來建立不同的集區。




=== 手動建立

當自動建立無法判斷最佳組態時、您可能需要手動建立集區。發生這種情況的原因如下：

* 新磁碟機可能會新增至多個集區。
* 一或多個新的資源池候選對象可以使用機櫃損失保護或藥櫃損失保護。
* 一或多個目前的資源池候選對象無法維持其機櫃遺失保護或藥櫃遺失保護狀態。如果您的儲存陣列上有多個應用程式、但不希望它們競用相同的磁碟機資源、您可能也想要手動建立資源池。在這種情況下、您可以考慮手動為一或多個應用程式建立較小的資源池。您只能指派一或兩個磁碟區、而不需將工作負載指派給有許多磁碟區的大型集區、以便在其中發佈資料。手動建立專屬特定應用程式工作負載的獨立資源池、可讓儲存陣列作業更快速地執行、同時減少爭用。

