---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-pool-manually.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 如果您的設定不符合自動集區組態的需求、則可以手動建立集區。資源池是一組邏輯分組的磁碟機。 
---
= 在 SANtricity Storage Plugin for vCenter 中手動建立集區
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果您的設定不符合自動集區組態的需求、則可以手動建立集區。資源池是一組邏輯分組的磁碟機。

.開始之前
* 您必須至少擁有11個相同磁碟機類型（HDD或SSD）的磁碟機。
* 磁碟櫃遺失保護要求組成資源池的磁碟機必須位於至少六個不同的磁碟機櫃中、而且單一磁碟機櫃中不超過兩個磁碟機。
* 藥櫃遺失保護功能要求組成資源池的磁碟機位於至少五個不同的藥櫃、且資源池中包含的磁碟機磁碟櫃數量與每個藥櫃相同。
* 在設定EF600或EF300儲存陣列時、請確定每個控制器在前12個插槽中有相同數量的磁碟機、以及在最後12個插槽中有相同數量的磁碟機。此組態可協助控制器更有效地使用兩個磁碟機端PCIe匯流排。若要建立集區、您應該使用儲存陣列中的所有磁碟機。


.關於這項工作
在建立集區期間、您可以判斷其特性、例如磁碟機類型、安全功能、資料保證（DA）功能、機櫃損失保護、以及抽屜損失保護。

對於EF600和EF300儲存陣列、設定也包括資源配置和磁碟區區塊大小。

.步驟
. 從「Manage（管理）」頁面中、選取集區的儲存陣列。
. 選取功能表：資源配置[設定資源池和磁碟區群組]。
. 按一下功能表：Create（建立）[Pool]（資源池）
+
此時將出現Create Pool（創建池）對話框。

. 輸入集區的名稱。
. （可選）如果您的儲存陣列中有多種磁碟機類型、請選取您要使用的磁碟機類型。
+
結果表會列出您可以建立的所有可能集區。

. 根據下列特性選取您要使用的資源池候選項目、然後按一下*建立*。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
可用容量
 a| 
顯示GiB中應徵集區的可用容量。選擇容量符合應用程式儲存需求的資源池候選資源。保留（備援）容量也會分散到整個資源池、而非可用容量的一部分。



 a| 
磁碟機總數
 a| 
顯示池候選中的可用磁碟機數量。系統會自動保留盡可能多的磁碟機以保留容量（對於集區中的每六個磁碟機、系統會保留一個磁碟機以保留容量）。發生磁碟機故障時、會使用保留容量來保留重建的資料。



 a| 
磁碟區塊大小（僅限EF300和EF600）
 a| 
顯示集區中磁碟機可以寫入的區塊大小（磁區大小）。價值可能包括：

** 512 - 512位元組區段大小。
** 4K - 4、096位元組區大小。




 a| 
安全功能
 a| 
指出此候選資源池是否完全由具備安全功能的磁碟機組成、磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。

** 您可以使用磁碟機安全性來保護集區、但所有磁碟機都必須具備安全功能、才能使用此功能。
** 如果您想要建立僅FDE集區、請在「Secure Capable（安全功能）」欄中尋找* Yes - FDE*。如果您要建立僅限FIPS的集區、請尋找*是- FIPS-或*是- FIPS（混合）*。「混合」表示混合使用140-2和140-2級磁碟機。如果混合使用這些層級、請注意集區將會以較低的安全層級（1402）運作。
** 您可以建立由磁碟機所組成的集區、這些磁碟機可能具有安全功能、也可能不具有安全功能、或是混合了安全性層級。如果集區中的磁碟機包含不安全的磁碟機、您就無法確保集區安全無虞。




 a| 
啟用安全性？
 a| 
提供選項、讓磁碟機安全功能可與安全的磁碟機搭配使用。如果集區具備安全功能、而且您已建立安全金鑰、則可選取核取方塊來啟用安全性。


NOTE: 啟用「磁碟機安全性」之後、唯一的移除方法是刪除集區並清除磁碟機。



 a| 
DA能力
 a| 
指出此資源池候選對象是否適用資料保證（DA）。DA會檢查並修正資料經由控制器向下傳輸到磁碟機時可能發生的錯誤。如果您要使用DA、請選取具有DA功能的資源池。此選項僅在啟用DA功能時可用。集區可以包含具有DA功能或不具備DA功能的磁碟機、但所有磁碟機都必須具備DA功能、才能使用此功能。



 a| 
資源資源配置功能（僅限EF300和EF600）
 a| 
顯示資源資源配置是否適用於此資源池候選對象。資源資源配置是EF300和EF600儲存陣列的一項功能、可讓磁碟區立即投入使用、而無需背景初始化程序。



 a| 
機櫃損失保護
 a| 
顯示機櫃遺失保護是否可用。如果單一磁碟機櫃發生通訊完全中斷、機櫃遺失保護功能可確保存取集區中磁碟區上的資料。



 a| 
藥櫃遺失保護
 a| 
顯示藥櫃遺失保護功能是否可用、僅當您使用含有藥櫃的磁碟機櫃時才會提供此功能。如果磁碟櫃中的單一藥櫃發生通訊完全中斷、藥櫃遺失保護可確保存取資源池中磁碟區上的資料。



 a| 
支援的Volume區塊大小（僅限EF300和EF600）
 a| 
顯示可為集區中的磁碟區建立的區塊大小：

** 512n -原生512位元組。
** 512e -模擬512位元組。
** 4K - 4、096位元組。


|===
====

