---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-the-settings-for-a-host.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 您可以變更主機或主機叢集的名稱、主機作業系統類型及相關的主機叢集。 
---
= 變更主機的設定
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以變更主機或主機叢集的名稱、主機作業系統類型及相關的主機叢集。

.步驟
. 在「Manage（管理）」頁面中、選取具有主機連線的儲存陣列。
. 選取功能表：資源配置[設定主機]。
+
此時會開啟「設定主機」頁面。

. 選取您要編輯的主機、然後按一下「*檢視/編輯設定*」。
+
此時會出現一個對話方塊、顯示目前的主機設定。

. 若要變更主機內容、請確定已選取「*內容*」索引標籤、然後視需要變更設定。
+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
名稱
 a| 
您可以變更使用者提供的主機名稱。必須指定主機名稱。



 a| 
相關的主機叢集
 a| 
您可以選擇下列其中一個選項：

** *無*：主機仍為獨立主機。如果主機與主機叢集相關聯、系統會從叢集移除該主機。
** *<主機叢集>*-系統會將主機與選取的叢集建立關聯。




 a| 
主機作業系統類型
 a| 
您可以變更所定義主機上執行的作業系統類型。

|===
====
. 若要變更連接埠設定、請按一下*主機連接埠*索引標籤、然後視需要變更設定。
+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
主機連接埠
 a| 
您可以選擇下列其中一個選項：

** *新增*-使用「新增」將新的主機連接埠識別碼關聯至主機。主機連接埠識別碼名稱的長度取決於主機介面技術。Fibre Channel和Infiniband主機連接埠識別碼名稱必須有16個字元。iSCSI主機連接埠識別碼名稱最多可有223個字元。連接埠必須是唯一的。不允許已設定的連接埠號碼。
** *刪除*-使用刪除來移除（取消關聯）主機連接埠識別碼。刪除選項不會實際移除主機連接埠。此選項會移除主機連接埠與主機之間的關聯。除非您移除主機匯流排介面卡或iSCSI啟動器、否則控制器仍會識別主機連接埠。



CAUTION: 如果刪除主機連接埠識別碼、則該識別碼不再與此主機相關聯。此外、主機也無法透過此主機連接埠識別碼存取任何已指派的磁碟區。



 a| 
標籤
 a| 
若要變更連接埠標籤名稱、請按一下*編輯*圖示（鉛筆）。連接埠標籤名稱必須是唯一的。不允許已設定的標籤名稱。



 a| 
CHAP機密
 a| 
僅適用於iSCSI主機。您可以設定或變更啟動器（iSCSI主機）的CHAP機密。系統使用Challenge Handshake驗證傳輸協定（CHAP）方法、在初始連結期間驗證目標和啟動器的身分。驗證是以稱為CHAP機密的共用安全金鑰為基礎。

|===
====
. 按一下「 * 儲存 * 」。

