---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-upgrade-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 您可以管理SANtricity 同類型多個儲存陣列的支援功能、以利執行更新。 
---
= 瞭解如何使用適用於 vCenter 的儲存外掛程式來管理 SANtricity 軟體升級
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在vCenter的儲存外掛程式中、您可以管理SANtricity 同類型多個儲存陣列的VMware vCenter軟體和NVSRAM升級。



== 升級工作流程

下列步驟提供執行軟體升級的高層級工作流程：

. 您可從SANtricity 支援網站下載最新的支援作業系統檔案（可從支援頁面取得連結）。將檔案儲存到管理主機系統（您在瀏覽器中存取外掛程式的主機）、然後將檔案解壓縮。
. 在外掛程式中、您可以將SANtricity S還原OS軟體檔案和NVSRAM/檔案載入儲存庫（儲存檔案的伺服器區域）。
. 在檔案載入儲存庫之後、您可以選取要用於升級的檔案。從「Upgrade SANtricity SKETOS Software」（升級版SOS軟體）頁面中、選取OS軟體檔案和NVSRAM.選取軟體檔案後、相容儲存陣列的清單就會出現在此頁面上。然後選擇要使用新軟體升級的儲存陣列。（您無法選取不相容的陣列。）
. 接著您可以立即開始軟體傳輸和啟動、也可以選擇稍後將檔案登入以進行啟動。在升級過程中、外掛程式會執行下列工作：
+
** 對儲存陣列執行健全狀況檢查、以判斷是否存在任何可能妨礙升級完成的情況。如果有任何陣列未通過健全狀況檢查、您可以跳過該特定陣列並繼續升級其他陣列、或是停止整個程序、並疑難排解未通過的陣列。
** 將升級檔案傳輸至每個控制器。
** 重新啟動控制器、並啟動新的作業系統軟體、一次一個控制器。在啟動期間、現有的OS檔案會被新檔案取代。





NOTE: 您也可以指定日後啟動軟體。



== 升級考量

在升級多個儲存陣列之前、請先檢閱規劃中的重要考量事項。



=== 目前版本

您可以SANtricity 從vCenter的「Storage Plugin for vCenter」（儲存外掛程式for vCenter）頁面、針對每個探索到的儲存陣列、檢視目前的VMware作業系統軟體版本。版本會顯示在SANtricity 「更新OS軟體」欄位中。當您按一下每列的OS版本時、控制器韌體和NVSRAM資訊 會出現在快顯對話方塊中。



=== 其他需要升級的元件

在升級過程中、您可能還需要升級主機的多重路徑/容錯移轉驅動程式或HBA驅動程式、以便主機能夠正確與控制器互動。如需相容性資訊、請參閱 link:https://imt.netapp.com/matrix/["互通性對照表工具"^]。



=== 雙控制器

如果儲存陣列包含兩個控制器、而且您已安裝多重路徑驅動程式、則儲存陣列可在升級時繼續處理I/O。在升級期間、會發生下列程序：

. 控制器A將其所有LUN容錯移轉至控制器B
. 在控制器A上進行升級
. 控制器A會恢復其LUN及控制器B的所有LUN。
. 在控制器B上進行升級


升級完成後、您可能需要在控制器之間手動重新分配磁碟區、以確保磁碟區回到正確的擁有控制器。
