---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-settings-for-a-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 變更磁碟區的設定、例如名稱、主機指派、區段大小、修改優先順序、快取、 等等。 
---
= 變更Volume的設定
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以變更磁碟區的設定、例如名稱、主機指派、區段大小、修改優先順序、快取、 等等。

確定您要變更的Volume處於最佳狀態。

.步驟
. 從「Manage（管理）」頁面中、選取包含您要變更之磁碟區的儲存陣列。
. 選取功能表：資源配置[管理磁碟區]。
. 選取您要變更的Volume、然後選取*檢視/編輯設定*。
+
Volume Settings（Volume設定）對話方塊隨即出現。您所選Volume的組態設定會顯示在此對話方塊中。

. 選取* Basic *索引標籤以變更磁碟區的名稱和主機指派。
+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
名稱
 a| 
顯示磁碟區名稱。當目前名稱不再有意義或適用時、請變更Volume名稱。



 a| 
容量
 a| 
顯示所選磁碟區的已報告和已分配容量。



 a| 
資源池/ Volume群組
 a| 
顯示集區或磁碟區群組的名稱和RAID層級。指出集區或磁碟區群組是否具備安全功能和安全功能。



 a| 
主機
 a| 
顯示Volume指派。您可以將磁碟區指派給主機或主機叢集、以便存取該磁碟區進行I/O作業。這項指派可讓主機或主機叢集存取儲存陣列中的特定磁碟區或多個磁碟區。

** *指派給*-識別可存取所選磁碟區的主機或主機叢集。
** * LUN*-邏輯單元號碼（LUN）是指派給主機用來存取磁碟區之位址空間的號碼。磁碟區會以LUN的形式、以容量形式呈現給主機。每個主機都有自己的LUN位址空間。因此、不同主機可以使用相同的LUN來存取不同的磁碟區。


對於NVMe介面、此欄會顯示命名空間ID。命名空間是NVM儲存設備、其格式化為區塊存取。它類似於SCSI中的邏輯單元、與儲存陣列中的磁碟區相關。命名空間ID是NVMe控制器的命名空間唯一識別碼、可設定為1到255之間的值。它類似於SCSI中的邏輯單元號碼（LUN）。



 a| 
識別碼
 a| 
顯示所選磁碟區的識別碼。

** 全球識別碼（WWID）。磁碟區的唯一十六進位識別碼。
** 延伸唯一識別碼（EUE）。Volume的EUI-64識別碼。
** 子系統識別碼（SSID）。Volume的儲存陣列子系統識別碼。


|===
====
. 選取*進階*索引標籤以變更集區或Volume群組中某個磁碟區的其他組態設定。
+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
應用程式與工作負載資訊
 a| 
在磁碟區建立期間、您可以建立應用程式專屬的工作負載或其他工作負載。如果適用、所選磁碟區的工作負載名稱、應用程式類型和磁碟區類型將會出現。您可以視需要變更工作負載名稱。



 a| 
服務品質設定
 a| 
*永久停用資料保證*-此設定僅在磁碟區已啟用資料保證（DA）時才會顯示。DA會檢查並修正資料經由控制器向下傳輸到磁碟機時可能發生的錯誤。使用此選項可在選取的磁碟區上永久停用DA。停用時、無法在此磁碟區上重新啟用DA。*啟用預先讀取備援檢查*-此設定僅在磁碟區為厚磁碟區時才會顯示。預先讀取備援檢查可決定在執行讀取時、磁碟區上的資料是否一致。如果控制器韌體判定資料不一致、啟用此功能的磁碟區會傳回讀取錯誤。



 a| 
控制器擁有權
 a| 
定義指定為磁碟區擁有或主要控制器的控制器。控制器擁有權非常重要、因此應謹慎規劃。控制器應盡量平衡整體I/O。



 a| 
區段規模調整
 a| 
顯示區段大小調整的設定、僅適用於Volume群組中的磁碟區。您可以變更區段大小以最佳化效能。*允許的區段大小轉換*-系統會決定允許的區段大小轉換。無法在下拉式清單中使用不適當的從目前區段大小轉換的區段大小。允許的轉換通常是目前區段大小的兩倍或一半。例如、如果目前的Volume區段大小為32 KiB、則允許新的Volume區段大小為16 KiB或64 KiB。*啟用SSD快取的磁碟區*-您可以為啟用SSD快取的磁碟區指定4-KiB區段大小。請務必針對啟用SSD快取的磁碟區選取4-KiB區段大小、以便處理小區塊I/O作業（例如、16個KiB I/O區塊大小或更小）。如果您選取4 KiB做為啟用SSD快取的磁碟區的區段大小、以處理大量區塊循序作業、效能可能會受到影響。*變更區段大小所需的時間。*變更磁碟區區區段大小所需的時間取決於下列變數：

** 主機的I/O負載
** 磁碟區的修改優先順序
** Volume群組中的磁碟機數量
** 磁碟機通道數
** 儲存陣列控制器的處理能力


當您變更磁碟區的區段大小時、I/O效能會受到影響、但您的資料仍可繼續使用。



 a| 
修改優先順序
 a| 
顯示修改優先順序的設定、僅適用於Volume群組中的磁碟區。修改優先順序會定義相對於系統效能、為磁碟區修改作業分配多少處理時間。您可以提高磁碟區修改優先順序、但這可能會影響系統效能。移動滑桿以選取優先順序層級。*修改優先率*：最低優先率有利於系統效能、但修改作業需要較長時間。最高優先順序率有利於修改作業、但系統效能可能會受損。



 a| 
快取
 a| 
顯示快取設定、您可以變更此設定、以影響磁碟區的整體I/O效能。



 a| 
SSD快取
 a| 
（EF600或EF300儲存系統無法使用此功能。） 顯示SSD快取設定、您可以在相容磁碟區上啟用此設定、藉此提升唯讀效能。如果磁碟區共用相同的磁碟機安全性和資料保證功能、則磁碟區會相容。SSD快取功能使用單一或多個固態磁碟（SSD）來實作讀取快取。由於SSD的讀取時間較短、因此應用程式效能有所提升。由於讀取快取位於儲存陣列中、因此快取會在所有使用儲存陣列的應用程式之間共享。只要選取您要快取的磁碟區、就能自動動態快取。

|===
====
. 按一下「 * 儲存 * 」。


Volume設定會根據您的選擇而變更。
