---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-check-volume-redundancy.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 您可以檢查集區或磁碟區群組中某個磁碟區的備援、以判斷該磁碟區上的資料是否一致。如果資源池或磁碟區群組中的某個磁碟機故障、備援資料可用於快速重建替換磁碟機上的資訊。 
---
= 檢查磁碟區備援
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在技術支援的指導下或依照Recovery Guru的指示、您可以檢查集區或磁碟區群組中磁碟區的備援、以判斷該磁碟區上的資料是否一致。

如果資源池或磁碟區群組中的某個磁碟機故障、備援資料可用於快速重建替換磁碟機上的資訊。

.開始之前
* 集區或磁碟區群組的狀態必須為最佳。
* 集區或Volume群組必須沒有進行中的Volume修改作業。
* 除了RAID 0之外、您可以檢查任何RAID層級的備援、因為RAID 0沒有資料備援。（集區僅設定為RAID 6。）



NOTE: 請僅在Recovery Guru指示下、並在技術支援指導下檢查Volume備援。

.關於這項工作
您一次只能在一個集區或磁碟區群組上執行此檢查。磁碟區備援檢查會執行下列動作：

* 掃描RAID 3 Volume、RAID 5 Volume或RAID 6 Volume中的資料區塊、並檢查每個區塊的備援資訊。（RAID 3只能使用命令列介面指派給Volume群組。）
* 比較RAID 1鏡射磁碟機上的資料區塊。
* 如果控制器韌體判定資料不一致、則傳回備援錯誤。



NOTE: 在相同的集區或磁碟區群組上立即執行備援檢查可能會導致錯誤。若要避免此問題、請先等待一到兩分鐘、再在同一個集區或磁碟區群組上執行另一個備援檢查。

.步驟
. 從「Manage（管理）」頁面中、選取具有Pool（資源池）或Volume（磁碟區）群組的儲存陣列。
. 選取功能表：資源配置[設定資源池和磁碟區群組]。
. 選取功能表：非常見工作[檢查磁碟區備援]。
+
「檢查備援」對話方塊隨即出現。

. 選取您要檢查的磁碟區、然後輸入檢查以確認您要執行此作業。
. 按一下*檢查*。
+
檢查磁碟區備援作業隨即開始。從對話方塊表格頂端開始、會依序掃描集區或Volume群組中的磁碟區。掃描每個Volume時會執行下列動作：

+
** Volume會在Volume表格中選取。
** 備援檢查的狀態會顯示在「Status（狀態）」欄中。
** 檢查會在發生任何媒體或同位元檢查錯誤時停止、然後回報錯誤。下表提供有關備援檢查狀態的詳細資訊：


+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 狀態 | 說明 


| 擱置中 | 這是第一個要掃描的磁碟區、您尚未按一下「Start（開始）」來開始備援檢查。或-正在對集區或磁碟區群組中的其他磁碟區執行備援檢查作業。 


| 正在檢查 | 磁碟區正在進行備援檢查。 


| 通過 | 磁碟區通過備援檢查。在備援資訊中未偵測到不一致的情形。 


| 失敗 | 磁碟區未通過備援檢查。在備援資訊中偵測到不一致的情況。 


| 媒體錯誤 | 磁碟機媒體故障且無法讀取。依照Recovery Guru中顯示的指示操作。 


| 同位元檢查錯誤 | 同位元檢查並非特定部分資料應有的同位元檢查。同位元檢查錯誤可能很嚴重、可能導致資料永久遺失。 
|===
====
. 檢查完池或Volume群組中的最後一個Volume之後、按一下「*完成*」。

