---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-media-scan-settings-for-a-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 媒體掃描是一種背景作業、可掃描磁碟區中的所有資料和備援資訊。使用此選項可啟用或停用一或多個Volume的媒體掃描設定、或變更掃描持續時間。 
---
= 變更Volume的媒體掃描設定
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
媒體掃描是一種背景作業、可掃描磁碟區中的所有資料和備援資訊。使用此選項可啟用或停用一或多個Volume的媒體掃描設定、或變更掃描持續時間。

.開始之前
瞭解下列事項：

* 媒體掃描會根據要掃描的容量和掃描持續時間、以固定的速度持續執行。背景掃描可能會由較高優先順序的背景工作（例如重建）暫停、但會以相同的固定速率繼續。
* 只有在儲存陣列和該磁碟區啟用媒體掃描選項時、才會掃描磁碟區。如果該磁碟區也啟用備援檢查、則會檢查磁碟區中的備援資訊是否與資料一致、前提是磁碟區具有備援。建立每個磁碟區時、預設會啟用具有備援檢查的媒體掃描。
* 如果掃描期間發生無法恢復的媒體錯誤、資料將會使用備援資訊（如果有）進行修復。
+
例如、最佳RAID 5磁碟區或最佳或僅有一個磁碟機故障的RAID 6磁碟區中都有備援資訊。如果無法使用備援資訊修復不可恢復的錯誤、資料區塊將會新增至無法讀取的區段記錄。可修正和不可修正的媒體錯誤都會報告到事件記錄中。

* 如果備援檢查發現資料與備援資訊不一致、則會將其報告至事件記錄。


.關於這項工作
媒體掃描會偵測並修復應用程式不常讀取的磁碟區塊上的媒體錯誤。這可防止磁碟機故障時發生資料遺失、因為故障磁碟機的資料是使用備援資訊和磁碟區群組或集區中其他磁碟機的資料來重建。

您可以執行下列動作：

* 啟用或停用整個儲存陣列的背景媒體掃描
* 變更整個儲存陣列的掃描持續時間
* 啟用或停用一或多個Volume的媒體掃描
* 啟用或停用一或多個磁碟區的備援檢查


.步驟
. 從「Manage（管理）」頁面中、選取包含您要變更媒體掃描設定之磁碟區的儲存陣列。
. 選取功能表：資源配置[管理磁碟區]。
. 選取任何Volume、然後選取功能表：More（更多）[變更媒體掃描設定]。
+
此時會出現變更磁碟機媒體掃描設定對話方塊。儲存陣列上的所有磁碟區都會顯示在此對話方塊中。

. 若要啟用媒體掃描、請選取「*掃描媒體的過程...*」核取方塊。停用媒體掃描核取方塊會暫停所有媒體掃描設定。
. 指定要執行媒體掃描的天數。
. 針對您要執行媒體掃描的每個磁碟區、選取「*媒體掃描*」核取方塊。系統會針對您選擇執行媒體掃描的每個磁碟區啟用備援檢查選項。如果您不想執行備援檢查的個別磁碟區、請取消選取「*備援檢查*」核取方塊。
. 按一下「 * 儲存 * 」。


.結果
系統會根據您的選擇、將變更套用至背景媒體掃描。
