---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-use-ca-signed-certificates.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 取得並匯入CA簽署的憑證、以安全存取裝載Storage Plugin for vCenter的管理系統。 
---
= 使用CA簽署的憑證
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以取得並匯入CA簽署的憑證、以安全地存取裝載Storage Plugin for vCenter的管理系統。

使用CA簽署的憑證是三個步驟的程序：

* <<步驟1：完成CSR檔案>>。
* <<步驟2：提交CSR檔案>>。
* <<步驟3：匯入管理憑證>>。




== 步驟1：完成CSR檔案

您必須先產生憑證簽署要求（CSR）檔案、以識別您的組織和執行外掛程式的主機系統。或者、您也可以使用諸如OpenSSL的工具來產生CSR檔案、然後跳至 <<步驟2：提交CSR檔案>>。

.步驟
. 選擇*憑證管理*。
. 從*管理*索引標籤、選取*完整的csr*。
. 輸入下列資訊、然後按一下*下一步*：
+
** *組織*：貴公司或組織的完整法定名稱。包括尾碼、例如Inc.或Corp.
** *組織單位（選用）*：您組織處理憑證的部門。
** *城市/地區*：您的主機系統或企業所在的城市。
** *州/地區（選用）*：主機系統或企業所在的州或地區。
** *國家ISO代碼*：您所在國家/地區的兩位數ISO（國際標準化組織）代碼、例如US。


. 輸入外掛程式執行所在主機系統的下列資訊：
+
** *一般名稱*：執行外掛程式之主機系統的IP位址或DNS名稱。請確定此位址正確無誤、而且必須完全符合您輸入的內容、才能在瀏覽器中存取外掛程式。請勿包含http：//或https：//。DNS名稱不能以萬用字元開頭。
** *備用IP位址*-如果一般名稱是IP位址、您可以選擇輸入主機系統的任何其他IP位址或別名。對於多個項目、請使用以逗號分隔的格式。
** *備用DNS名稱*-如果通用名稱是DNS名稱、請輸入主機系統的任何其他DNS名稱。對於多個項目、請使用以逗號分隔的格式。如果沒有替代DNS名稱、但您在第一個欄位中輸入DNS名稱、請在此處複製該名稱。DNS名稱不能以萬用字元開頭。


. 確認主機資訊正確無誤。如果不是、當您嘗試匯入CA時、從CA傳回的憑證將會失敗。
. 單擊*完成*。




== 步驟2：提交CSR檔案

建立憑證簽署要求（CSR）檔案之後、您會將產生的CSR檔案傳送給CA、以接收裝載外掛程式之系統的已簽署管理憑證。

E系列系統要求簽署的憑證使用PEm格式（Base64 Ascii編碼）、其中包含下列檔案類型：.pem、.crt、.cer或.key。

.步驟
. 找到下載的CSR檔案。
+
下載的資料夾位置取決於您的瀏覽器。

. 將CSR檔案提交給CA（例如、Verisign或Digiting）、並以PEV格式要求簽署的憑證。



CAUTION: 將CSR檔案提交給CA之後、請勿重新產生另一個CSR檔案。

每當您產生CSR時、系統都會建立私密與公開金鑰配對。公開金鑰是CSR的一部分、而私密金鑰則保留在系統的Keystore中。當您收到簽署的憑證並匯入時、系統會確保私密金鑰和公開金鑰都是原始配對。如果金鑰不符、簽署的憑證將無法運作、您必須向CA要求新的憑證。



== 步驟3：匯入管理憑證

從憑證授權單位（CA）收到簽署的憑證後、請將憑證匯入安裝外掛程式的主機系統。

.開始之前
* 您必須擁有CA所簽署的憑證。這些檔案包括根憑證、一或多個中繼憑證和伺服器憑證。
* 如果CA提供鏈結的憑證檔案（例如.p7b檔案）、您必須將鏈結的檔案解壓縮至個別檔案：根憑證、一或多個中繼憑證及伺服器憑證。您可以使用Windows certmanager公用程式來解壓縮檔案（按一下滑鼠右鍵、然後選取功能表：All Tasks [Export（所有工作[匯出]）。建議使用Base 64編碼。匯出完成後、會針對鏈中的每個憑證檔案顯示一個CER.檔案。
* 您必須將憑證檔案複製到執行外掛程式的主機系統。


.步驟
. 選擇*憑證管理*。
. 從*管理*索引標籤、選取*匯入*。
+
隨即開啟一個對話方塊、用於匯入憑證檔案。

. 按一下*瀏覽*以先選取根和中繼憑證檔案、然後選取伺服器憑證。如果您是從外部工具產生CSR、也必須匯入與CSR一起建立的私密金鑰檔案。
+
檔案名稱會顯示在對話方塊中。

. 按一下*匯入*。


.結果
檔案會上傳並驗證。憑證資訊會顯示在「憑證管理」頁面上。
