---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-how-does-my-selected-workload-impact-volume-creation.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 在磁碟區建立期間、系統會提示您提供工作負載使用的相關資訊。 
---
= 我所選的工作負載如何影響磁碟區建立？
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在磁碟區建立期間、系統會提示您提供工作負載使用的相關資訊。系統會使用此資訊為您建立最佳Volume組態、並可視需要加以編輯。您也可以在磁碟區建立順序中跳過此步驟。

工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。對於某些應用程式、系統會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。

* *應用程式專屬*-當您使用應用程式專屬的工作負載來建立磁碟區時、系統可能會建議最佳化的磁碟區組態、以將應用程式工作負載I/O與應用程式執行個體的其他流量之間的爭用降至最低。對於針對下列應用程式類型所建立的工作負載、會自動建議並最佳化I/O類型、區段大小、控制器擁有權、讀寫快取等Volume特性。
+
** Microsoft SQL Server
** Microsoft Exchange Server
** 視訊監控應用程式
** VMware ESXi（適用於與虛擬機器檔案系統搭配使用的磁碟區）
+
您可以使用「新增/編輯磁碟區」對話方塊來檢閱建議的磁碟區組態、以及編輯、新增或刪除系統建議的磁碟區和特性。



* *其他（或不支援特定磁碟區建立的應用程式）*- 其他工作負載則使用Volume組態、您必須手動指定何時要建立與特定應用程式無關的工作負載、或是儲存陣列上未針對您要使用的應用程式進行內建最佳化。您必須使用「新增/編輯磁碟區」對話方塊手動指定磁碟區組態。

