---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-configuration-settings-for-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 編輯Volume群組的設定、包括其名稱和RAID層級。 
---
= 變更Volume群組的組態設定
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以編輯Volume群組的設定、包括其名稱和RAID層級。

如果您要變更RAID層級以符合存取Volume群組之應用程式的效能需求、請務必符合下列先決條件：

* Volume群組必須處於最佳狀態。
* 您必須在Volume群組中擁有足夠的容量、才能轉換成新的RAID層級。


.步驟
. 在「Manage（管理）」頁面中、選取含有Volume群組的儲存陣列。
. 選取功能表：資源配置[設定資源池和磁碟區群組]。
. 選取您要編輯的Volume群組、然後按一下*檢視/編輯設定*。
+
Volume Group Settings（Volume群組設定）對話方塊隨即出現。

. 選取*設定*索引標籤、然後視需要編輯Volume群組設定。
+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
名稱
 a| 
您可以變更使用者提供的Volume群組名稱。必須指定Volume群組的名稱。



 a| 
RAID層級
 a| 
從下拉式功能表中選取新的RAID層級。

** * RAID 0分段*-提供高效能、但不提供任何資料備援。如果磁碟區群組中的單一磁碟機故障、則所有相關的磁碟區都會故障、而且所有資料都會遺失。分段RAID群組將兩個或多個磁碟機合併成一個大型邏輯磁碟機。
** * RAID 1鏡射*：提供高效能與最佳資料可用度、適合在企業或個人層級儲存敏感資料。自動將一個磁碟機的內容鏡射到鏡射配對中的第二個磁碟機、以保護您的資料。它可在單一磁碟機故障時提供保護。
** * RAID 10分段/鏡射*-提供RAID 0（分段）和RAID 1（鏡射）的組合、並可在選取四個以上磁碟機時達成。RAID 10適用於需要高效能和容錯能力的大量交易應用程式、例如資料庫。
** * RAID 5*-最適合多使用者環境（例如資料庫或檔案系統儲存設備）、其中典型的I/O大小較小、而且讀取活動比例較高。
** * RAID 6*-最適合需要RAID 5以外的備援保護、但不需要高寫入效能的環境。RAID 3只能使用命令列介面（CLI）指派給Volume群組。當您變更RAID層級時、無法在作業開始後取消此作業。在變更期間、您的資料仍可繼續使用。




 a| 
最佳化容量（僅限EF600陣列）
 a| 
建立Volume群組時、會產生建議的最佳化容量、以平衡可用容量與效能、以及磁碟機使用壽命。您可以將滑桿移至右側、以獲得更佳的效能和更長的使用壽命、同時犧牲更高的可用容量、或是將滑桿移至左側以增加可用容量、同時犧牲更好的效能和更長的使用壽命。當SSD磁碟機的一部分容量未配置時、其壽命將更長、寫入效能將更高。對於與磁碟區群組相關聯的磁碟機、未分配的容量由群組的可用容量（磁碟區未使用的容量）和保留為額外最佳化容量的部分可用容量組成。額外的最佳化容量可藉由減少可用容量來確保最小程度的最佳化容量、因此無法建立磁碟區。

|===
====
. 按一下「 * 儲存 * 」。


如果容量減少、磁碟區備援遺失、或由於RAID層級變更而失去機櫃/藥櫃遺失保護、則會出現確認對話方塊。選擇* Yes*繼續；否則請按* No*。

如果您變更Volume群組的RAID層級、外掛程式會變更組成Volume群組之每個Volume的RAID層級。在作業期間、效能可能會稍微受到影響。
