---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-host-access.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 若要使用vCenter的儲存外掛程式來管理儲存設備、您必須探索或定義網路中的每個主機。 
---
= 建立主機存取
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要使用vCenter的儲存外掛程式來管理儲存設備、您必須探索或定義網路中的每個主機。

.關於這項工作
藉由建立主機、您可以定義主機參數、以便連線至儲存陣列、並存取磁碟區的I/O。

建立主機時、請謹記以下準則：

* 您必須定義與主機相關聯的主機識別碼連接埠。
* 請確定您提供的名稱與主機指派的系統名稱相同。
* 如果您選擇的名稱已在使用中、則此作業不會成功。
* 名稱長度不得超過30個字元。


.步驟
. 在「Manage（管理）」頁面中、選取具有主機連線的儲存陣列。
. 選取功能表：資源配置[設定主機]。
+
此時會開啟「設定主機」頁面。

. 按一下功能表：Create [Host]（建立[主機]）。
+
此時會出現Create Host（建立主機）對話方塊。

. 視需要選取主機的設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
名稱
 a| 
輸入新主機的名稱。



 a| 
主機作業系統類型
 a| 
從下拉式清單中選取新主機上執行的作業系統。



 a| 
主機介面類型
 a| 
（選用）如果儲存陣列支援多種主機介面類型、請選取您要使用的主機介面類型。



 a| 
主機連接埠
 a| 
執行下列其中一項：

** *選擇I/O介面*-一般而言、主機連接埠應該已登入、並可從下拉式清單中使用。您可以從清單中選取主機連接埠識別碼。
** *手動新增*-如果清單中未顯示主機連接埠識別碼、表示主機連接埠尚未登入。HBA公用程式或iSCSI啟動器公用程式可用來尋找主機連接埠識別碼、並將其與主機建立關聯。您可以手動輸入主機連接埠識別碼、或從公用程式（一次一個）複製/貼到主機連接埠欄位。您一次必須選取一個主機連接埠識別碼、才能將其與主機建立關聯、但您可以繼續選取與主機相關聯的識別碼數目。每個識別碼都會顯示在主機連接埠欄位中。如有必要、您也可以選取旁邊的* X*來移除識別碼。




 a| 
設定CHAP啟動器密碼
 a| 
（選用）如果您選取或手動輸入iSCSI IQN的主機連接埠、且想要要求嘗試存取儲存陣列以使用Challenge Handshake驗證傳輸協定（CHAP）進行驗證的主機、請選取「Set CHAP Initiator secret（設定CHAP啟動器密碼）」核取方塊。針對您選取或手動輸入的每個iSCSI主機連接埠、執行下列動作：

** 輸入在每個iSCSI主機啟動器上為CHAP驗證設定的相同CHAP密碼。如果您使用的是相互CHAP驗證（雙向驗證、可讓主機驗證自己是否為儲存陣列、以及讓儲存陣列驗證自己是否為主機）、則您也必須在初始設定或變更設定時、為儲存陣列設定CHAP機密。
** 如果不需要主機驗證、請將欄位留白。目前唯一使用的iSCSI驗證方法是CHAP。


|===
====
. 按一下「 * 建立 * 」。
. 如果您需要更新主機資訊、請從表格中選取主機、然後按一下「*檢視/編輯設定*」。


.結果
成功建立主機之後、系統會針對為主機設定的每個主機連接埠建立預設名稱（使用者標籤）。預設別名為「<主機名稱連接埠號碼>」。例如、為主機IPT建立的第一個連接埠的預設別名為「IPT_1」。

.完成後
您必須將磁碟區指派給主機、以便用於I/O作業。前往 link:vc-olh-assign-volumes-to-hosts.html["將磁碟區指派給主機"]。
