---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-do-i-need-to-know-about-the-resource-provisioned-volumes-feature.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 資源資源配置是EF300和EF600儲存陣列的一項功能、可讓磁碟區立即投入使用、而無需背景初始化程序。 
---
= 關於資源配置的Volume功能、我需要知道什麼？
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
資源資源配置是EF300和EF600儲存陣列的一項功能、可讓磁碟區立即投入使用、而無需背景初始化程序。


NOTE: 目前無法使用資源配置功能。在某些檢視中、元件可能會回報為資源資源配置功能、但在未來更新中重新啟用之前、建立資源配置的磁碟區的功能已停用。



== 資源配置的磁碟區

資源配置的磁碟區是SSD磁碟區群組或集區中的一個完整磁碟區、在建立磁碟區時、會將磁碟機容量分配給該磁碟區（指派給該磁碟區）、但磁碟區塊會被取消分配（未對應）。相較之下、在傳統的厚磁碟區中、所有磁碟區區塊都會在背景磁碟區初始化作業期間對應或配置、以便初始化Data Assurance保護資訊欄位、並使每個RAID等量磁碟區的資料和RAID同位元保持一致。使用資源配置的Volume、就不會進行時間限制的背景初始化。相反地、每個RAID等量磁碟區都會在第一次寫入等量磁碟區塊時初始化。

資源配置的磁碟區僅支援SSD磁碟區群組和集區、群組或集區中的所有磁碟機都支援NVMe取消分配或未寫入的邏輯區塊錯誤啟用（DULBE）錯誤恢復功能。建立資源配置的Volume時、會取消分配指派給該磁碟區的所有磁碟區塊（未對應）。此外、主機可以使用NVMe資料集管理命令取消分配磁碟區中的邏輯區塊。取消分配區塊可改善SSD的耗損壽命、並提高最大寫入效能。每個磁碟機機型和容量的改善程度各不相同。



== 啟用和停用功能

預設會在磁碟機支援DULBE的系統上啟用資源配置。您可以從資源池和Volume群組停用該預設設定。停用資源資源配置是現有磁碟區的永久性動作、無法回復（亦即、您無法重新啟用這些磁碟區群組和資源池的資源配置）。

不過、如果您想要為所建立的任何新磁碟區重新啟用資源資源配置、可以從功能表：設定[系統]執行此作業。請注意、當您重新啟用資源資源配置時、只有新建立的Volume群組和集區會受到影響。任何現有的Volume群組和集區都將維持不變。如有需要、您也可以從功能表：設定[系統]再次停用資源資源配置。
