---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 您可以為一或多個可供主機存取的磁碟區建立磁碟區群組。 
---
= 建立Volume群組
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以為一或多個可供主機存取的磁碟區建立磁碟區群組。Volume群組是一個容器、用於具有RAID層級和容量等共享特性的磁碟區。

.開始之前
請檢閱下列準則：

* 您至少需要一個未指派的磁碟機。
* 單一磁碟區群組中的磁碟機容量有多少限制。這些限制會根據您的主機類型而有所不同。
* 若要啟用機櫃/藥櫃遺失保護、您必須建立一個磁碟區群組、使用位於至少三個磁碟櫃或藥櫃中的磁碟機、除非您使用的是RAID 1、其中兩個磁碟櫃/藥櫃為最小值。
* 在設定EF600或EF300儲存陣列時、請確定每個控制器在前12個插槽中有相同數量的磁碟機、以及在最後12個插槽中有相同數量的磁碟機。此組態可協助控制器更有效地使用兩個磁碟機端PCIe匯流排。建立Volume群組時、系統目前允許在「進階」功能下選取磁碟機。


檢閱您選擇的RAID層級如何影響磁碟區群組的最終容量。

* 如果您選取RAID 1、則必須一次新增兩個磁碟機、以確保已選取鏡射配對。選取四個以上的磁碟機時、即可實現鏡射和分段（稱為RAID 10或RAID 1+0）。
* 如果您選取RAID 5、則必須至少新增三個磁碟機才能建立Volume群組。
* 如果您選取RAID 6、則必須至少新增五個磁碟機才能建立Volume群組。


.關於這項工作
在磁碟區群組建立期間、您可以判斷群組的特性、例如磁碟機數量、安全功能、資料保證（DA）功能、機櫃損失保護、以及藥櫃損失保護。

對於EF600和EF300儲存陣列、設定也包括資源配置、磁碟區塊大小和磁碟區區塊大小。


NOTE: 由於磁碟容量較大、而且能夠跨控制器分散磁碟區、因此每個磁碟區群組建立一個以上的磁碟區、是充分利用儲存容量及保護資料的好方法。

.步驟
. 從「Manage（管理）」頁面中、選取Volume群組的儲存陣列。
. 選取功能表：資源配置[設定資源池和磁碟區群組]。
. 按一下功能表：「Create [Volume group（建立[ Volume群組]）
+
此時將出現Create Volume Group（創建Volume組）對話框。

. 輸入Volume群組的名稱。
. 選擇最符合您資料儲存與保護需求的RAID層級。Volume群組候選資料表隨即出現、並僅顯示支援所選RAID層級的候選資料。
. （可選）如果您的儲存陣列中有多種磁碟機類型、請選取您要使用的磁碟機類型。
+
Volume群組候選資料表隨即出現、並僅顯示支援所選磁碟機類型和RAID層級的候選資料。

. （可選）您可以選擇自動方法或手動方法來定義要在Volume群組中使用的磁碟機。自動方法為預設選項。
+

CAUTION: 除非您是瞭解磁碟機備援和最佳磁碟機組態的專家、否則請勿使用手動方法。

+
若要手動選取磁碟機、請按一下*手動選取磁碟機（進階）*連結。按一下時、它會變更為*自動選取磁碟機（進階）*。

+
「手動」方法可讓您選取組成磁碟區群組的特定磁碟機。您可以選取特定的未指派磁碟機、以取得所需的容量。如果儲存陣列包含具有不同媒體類型或不同介面類型的磁碟機、您只能選擇單一磁碟機類型的未設定容量、以建立新的Volume群組。

. 根據顯示的磁碟機特性、選取您要在磁碟區群組中使用的磁碟機、然後按一下*「Create」（建立）*。


顯示的磁碟機特性取決於您選擇的是自動方法或手動方法。如需更多資訊、請參閱SANtricity 《關於系統管理程式的資訊》文件、 https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-volume-group.html["建立Volume群組"^]。
