---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-increase-capacity-of-a-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 調整磁碟區大小以增加其報告容量。 
---
= 增加磁碟區的容量
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以調整磁碟區的大小、以增加其報告的容量。

.開始之前
請確定：

* 磁碟區相關聯的資源池或磁碟區群組中有足夠的可用容量可用。
* 磁碟區是最佳的、不會處於任何修改狀態。
* 磁碟區中沒有使用熱備援磁碟機。（僅適用於Volume群組中的Volume。）


.關於這項工作
此工作說明如何使用資源池或Volume群組中可用的可用容量來增加磁碟區的報告容量（報告給主機的容量）。請務必考量此集區或磁碟區群組中其他磁碟區未來可能會有的任何容量需求。


NOTE: 增加磁碟區容量僅在某些作業系統上受支援。如果您在不受支援的主機作業系統上增加磁碟區容量、擴充的容量將無法使用、而且您無法還原原始磁碟區容量。

.步驟
. 從「*管理*」頁面中、選取包含您要調整大小之磁碟區的儲存陣列。
. 選取功能表：資源配置[管理磁碟區]。
. 選取您要增加容量的磁碟區、然後選取*增加容量*。
+
此時會出現「確認增加容量」對話方塊。

. 選擇* Yes*繼續。
+
「增加報告容量」對話方塊隨即出現。此對話方塊會顯示磁碟區目前報告的容量、以及磁碟區相關聯之資源池或Volume群組中可用的可用容量。

. 使用「*透過新增...*來增加報告容量」方塊、將容量新增至目前可用的報告容量。您可以變更容量值、以百萬位元組（mebibbytes、mibibibbytes、GiB）或tebibbytes（TiB）顯示。
. 按一下*「增加*」。
+
磁碟區容量會根據您的選擇而增加。請注意、這項作業可能會冗長、並可能影響系統效能。



.完成後
擴充磁碟區容量之後、您必須手動增加檔案系統大小以符合需求。您的做法取決於所使用的檔案系統。如需詳細資料、請參閱主機作業系統文件。
