---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-provisioning-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 您可以建立稱為Volume的資料容器、以便主機存取陣列上的儲存設備。 
---
= 資源配置總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在vCenter的儲存外掛程式中、您可以建立稱為Volume的資料容器、以便主機存取陣列上的儲存設備。



== Volume類型與特性

Volume是資料容器、可管理及組織儲存陣列上的儲存空間。

您可以從儲存陣列上可用的儲存容量建立磁碟區、以協助組織系統資源。「Volume」的概念類似於使用電腦上的資料夾/目錄來組織檔案以供快速存取。

Volume是唯一可讓主機看到的資料層。在SAN環境中、磁碟區會對應至邏輯單元編號（LUN）。這些LUN包含使用儲存陣列支援的一或多個主機存取傳輸協定（包括FC、iSCSI和SAS）存取的使用者資料。

集區或磁碟區群組中的每個磁碟區都可以根據儲存在其中的資料類型、擁有各自的特性。這些特性包括：

* *區段大小*-區段是儲存陣列移至磁碟區（RAID群組）中下一個磁碟機之前、儲存在磁碟機上的資料量（千位元組）、以千位元組（KiB）為單位。區段大小等於或小於Volume群組的容量。區段大小是固定的、無法變更集區的區段大小。
* * Capacity *：您可以從資源池或磁碟區群組中可用的可用容量建立磁碟區。在建立磁碟區之前、集區或磁碟區群組必須已經存在、而且必須有足夠的可用容量來建立磁碟區。
* *控制器所有權*-所有儲存陣列都可以有一或兩個控制器。在單一控制器陣列上、磁碟區的工作負載是由單一控制器管理。在雙控制器陣列上、磁碟區將擁有「擁有」該磁碟區的慣用控制器（A或B）。在雙控制器組態中、磁碟區擁有權會使用自動負載平衡功能自動調整、以修正工作負載在控制器之間移動時的任何負載平衡問題。自動負載平衡功能可自動進行I/O工作負載平衡、確保來自主機的傳入I/O流量能在兩個控制器之間動態管理及平衡。
* * Volume assign*（Volume assign*）-您可以在建立Volume時或稍後、讓主機存取Volume。所有主機存取都是透過邏輯單元號碼（LUN）來管理。主機會偵測LUN、然後再將其指派給磁碟區。如果您要將磁碟區指派給多個主機、請使用叢集軟體來確保該磁碟區可供所有主機使用。
+
主機類型可針對主機可存取的磁碟區數量設定特定限制。當您建立要供特定主機使用的磁碟區時、請謹記此限制。

* *資源配置*-對於EF600或EF300儲存陣列、您可以指定立即使用磁碟區、而不需進行背景初始化程序。資源配置的磁碟區是SSD磁碟區群組或集區中的一個完整磁碟區、在建立磁碟區時、會將磁碟機容量分配給該磁碟區（指派給該磁碟區）、但磁碟區塊會被取消分配（未對應）。
* *描述性名稱*：您可以任意命名Volume、但我們建議您將名稱描述成描述性名稱。


在磁碟區建立期間、每個磁碟區都會被分配容量、並指派名稱、區段大小（僅限磁碟區群組）、控制器擁有權、以及磁碟區對主機指派。磁碟區資料會視需要在不同的控制器之間自動進行負載平衡。



== Volume容量

儲存陣列中的磁碟機可為您的資料提供實體儲存容量。在開始儲存資料之前、您必須先將分配的容量設定為稱為資源池或磁碟區群組的邏輯元件。您可以使用這些儲存物件來設定、儲存、維護及保留儲存陣列上的資料。



=== 建立及擴充磁碟區的容量

您可以從資源池或磁碟區群組中未指派的容量或可用容量建立磁碟區。

* 當您從未指派的容量建立磁碟區時、可以同時建立集區或磁碟區群組和磁碟區。
* 從可用容量建立磁碟區時、您要在現有的資源池或磁碟區群組上建立額外的磁碟區。擴充磁碟區容量之後、您必須手動增加檔案系統大小以符合需求。您的做法取決於所使用的檔案系統。如需詳細資料、請參閱主機作業系統文件。



NOTE: 外掛程式介面不提供建立精簡磁碟區的選項。



=== 報告的磁碟區容量

磁碟區的報告容量等於已配置的實體儲存容量。實體儲存容量必須全部存在。實體配置的空間等於報告給主機的空間。

您通常會將磁碟區的報告容量設定為您認為該磁碟區將會增加的最大容量。Volume可為您的應用程式提供高且可預測的效能、主要是因為所有的使用者容量都是在建立時保留和配置的。



=== 容量限制

磁碟區的最小容量為1個mib、最大容量取決於集區或磁碟區群組中磁碟機的數量和容量。

增加報告的Volume容量時、請謹記下列準則：

* 您最多可以指定三個小數位數（例如、65.375 GiB）。
* 容量必須小於（或等於）Volume群組中可用的最大容量。當您建立磁碟區時、會預先配置部分額外容量以進行動態區段大小（DSS）移轉。DSS移轉是軟體的一項功能、可讓您變更磁碟區的區段大小。
* 部分主機作業系統支援大於2 TiB的磁碟區（報告容量上限由主機作業系統決定）。事實上、某些主機作業系統最多可支援128個TiB磁碟區。如需其他詳細資料、請參閱主機作業系統文件。




== 應用程式專屬的工作負載

建立磁碟區時、您可以選取工作負載來自訂特定應用程式的儲存陣列組態。

工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。對於某些應用程式、系統會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。

在磁碟區建立期間、系統會提示您回答有關工作負載使用的問題。例如、如果您要為Microsoft Exchange建立磁碟區、系統會詢問您需要多少信箱、平均信箱容量需求為何、以及您想要的資料庫複本數量。系統會使用此資訊為您建立最佳Volume組態、並可視需要加以編輯。您也可以在磁碟區建立順序中跳過此步驟。



=== 工作負載類型

您可以建立兩種類型的工作負載：應用程式專屬和其他。

* *應用程式專屬*-當您使用應用程式專屬的工作負載來建立磁碟區時、系統可能會建議最佳化的磁碟區組態、以將應用程式工作負載I/O與應用程式執行個體的其他流量之間的爭用降至最低。對於針對下列應用程式類型所建立的工作負載、會自動建議並最佳化I/O類型、區段大小、控制器擁有權、讀寫快取等Volume特性。
+
** Microsoft SQL Server
** Microsoft Exchange Server
** 視訊監控應用程式
** VMware ESXi（適用於與虛擬機器檔案系統搭配使用的磁碟區）
+
您可以使用「新增/編輯磁碟區」對話方塊來檢閱建議的磁碟區組態、以及編輯、新增或刪除系統建議的磁碟區和特性。



* *其他（或不支援特定磁碟區建立的應用程式）*- 其他工作負載則使用Volume組態、您必須手動指定何時要建立與特定應用程式無關的工作負載、或是系統沒有內建的最佳化功能、無法在儲存陣列上使用應用程式。您必須使用「新增/編輯磁碟區」對話方塊手動指定磁碟區組態。




=== 應用程式與工作負載檢視

若要檢視應用程式和工作負載、請啟動System Manager。從該介面、您可以使用幾種不同的方式來檢視與應用程式特定工作負載相關的資訊：

* 您可以在「Volumes（磁碟區）」並排顯示區中選取「Applications & Workload（應用程式與工作負載）」索引標籤、以檢視依工作負載和工作負載相關的應用程式類型所群組的儲存陣列磁碟區。
* 您可以在「效能」方塊中選取「應用程式與工作負載」索引標籤、以檢視邏輯物件的效能指標（延遲、IOPS和MB）。物件會依應用程式和相關工作負載進行分組。藉由定期收集此效能資料、您可以建立基準測量並分析趨勢、協助您調查與I/O效能相關的問題。

