---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-configuration-settings-for-a-pool.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 編輯集區的設定、包括其名稱、容量警示設定、修改優先順序及保留容量。 
---
= 在 SANtricity Storage Plugin for vCenter 中變更集區的組態設定
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以編輯資源池的設定、包括其名稱、容量警示設定、修改優先順序及保留容量。

.關於這項工作
此工作說明如何變更集區的組態設定。


NOTE: 您無法使用外掛程式介面變更集區的RAID層級。外掛程式會自動將集區設定為RAID 6。

.步驟
. 從「Manage（管理）」頁面中、選取含有集區的儲存陣列。
. 選取功能表：資源配置[設定資源池和磁碟區群組]。
. 選取您要編輯的資源池、然後按一下*檢視/編輯設定*。
+
此時將顯示Pool Settings（池設置）對話框。

. 選取*設定*索引標籤、然後視需要編輯資源池設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
名稱
 a| 
您可以變更使用者提供的集區名稱。必須指定集區名稱。



 a| 
容量警示
 a| 
當資源池中的可用容量達到或超過指定臨界值時、您可以傳送警示通知。當儲存在資源池中的資料超過指定的臨界值時、外掛程式會傳送訊息、讓您有時間新增更多儲存空間或刪除不必要的物件。警示會顯示在儀表板的「通知」區域中、並可透過電子郵件和SNMP設陷訊息從伺服器傳送給系統管理員。您可以定義下列容量警示：

** *重大警示*-當資源池中的可用容量達到或超過指定臨界值時、此重大警示會通知您。使用微調控制項來調整臨界值百分比。選取核取方塊以停用此通知。
** *早期警示*-當資源池中的可用容量達到指定臨界值時、此早期警示會通知您。使用微調控制項來調整臨界值百分比。選取核取方塊以停用此通知。




 a| 
修改優先順序
 a| 
您可以指定集區中修改作業的優先順序層級、以符合系統效能。池中修改作業的優先順序越高、作業完成速度就越快、但可能會減慢主機I/O效能。較低的優先順序會使作業時間變長、但主機I/O效能的影響較小。您可以從五個優先層級中選擇：最低、低、中、高及最高。優先等級越高、對主機I/O和系統效能的影響就越大。

** *重大重建優先順序*-當多個磁碟機故障導致某些資料沒有備援、而額外的磁碟機故障可能導致資料遺失時、此滑桿會決定資料重建作業的優先順序。
** *降級重建優先順序*：此滑桿可在磁碟機故障時決定資料重建作業的優先順序、但資料仍有備援功能、而額外的磁碟機故障不會導致資料遺失。
** *背景作業優先順序*-此滑桿可決定集區處於最佳狀態時所發生之集區背景作業的優先順序。這些作業包括動態磁碟區擴充（DVE）、即時可用度格式（IAF）、以及將資料移轉至更換或新增的磁碟機。




 a| 
保留容量（EF600或EF300的「最佳化容量」）
 a| 
*保留容量*：您可以定義磁碟機數量、以判斷資源池上保留的容量、以支援可能的磁碟機故障。發生磁碟機故障時、會使用保留容量來保留重建的資料。資源池會在資料重建程序期間使用保留容量、而非在磁碟區群組中使用熱備援磁碟機。使用微調控制項來調整磁碟機數量。根據磁碟機數量、資源池中的保留容量會顯示在Spinner方塊旁。請謹記下列關於保留容量的資訊。

** 由於保留容量會從資源池的總可用容量中減去、因此保留的容量量會影響可用的可用容量量、以建立磁碟區。如果您為保留容量指定0、則會使用集區上的所有可用容量來建立磁碟區。
** 如果您減少保留容量、就會增加可用於資源池磁碟區的容量。


*額外的最佳化容量（僅限EF600和EF300陣列）*-建立集區時、會產生建議的最佳化容量、以平衡可用容量與效能、以及磁碟機使用壽命。您可以將滑桿移至右側、以獲得更佳的效能和更長的使用壽命、同時犧牲更高的可用容量、或是將滑桿移至左側以增加可用容量、同時犧牲更好的效能和更長的使用壽命。當SSD磁碟機的一部分容量未配置時、其壽命將更長、寫入效能將更高。對於與集區相關聯的磁碟機、未分配的容量由集區的保留容量、可用容量（磁碟區未使用的容量）以及保留為額外最佳化容量的可用容量所組成。額外的最佳化容量可藉由減少可用容量來確保最小程度的最佳化容量、因此無法建立磁碟區。

|===
====
. 按一下「 * 儲存 * 」。

