---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-pool-automatically.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 當系統偵測到至少11個未指派的磁碟機、或偵測到一個符合現有集區資格的未指派磁碟機時、您可以自動建立集區。 
---
= 在 SANtricity Storage Plugin for vCenter 中自動建立集區
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
當系統偵測到至少11個未指派的磁碟機、或偵測到一個符合現有集區資格的未指派磁碟機時、您可以自動建立集區。資源池是一組邏輯分組的磁碟機。

.開始之前
當下列其中一項條件成立時、您可以啟動「Pool自動組態」對話方塊：

* 偵測到至少有一個未指派的磁碟機、可新增至具有類似磁碟機類型的現有集區。
* 偵測到十一（11）個以上的未指派磁碟機、可用來建立新的集區（如果磁碟機類型不同而無法新增至現有的集區）。


.關於這項工作
您可以使用自動建立集區、將儲存陣列中所有未指派的磁碟機輕鬆設定為一個集區、並將磁碟機新增至現有的集區。

請謹記下列事項：

* 將磁碟機新增至儲存陣列時、系統會自動偵測磁碟機、並根據磁碟機類型和目前組態、提示您建立單一集區或多個集區。
* 如果先前已定義資源池、系統會自動提示您選擇將相容磁碟機新增至現有資源池。當新磁碟機新增至現有的資源池時、系統會自動將資料重新分配至新的容量、其中包括您新增的新磁碟機。
* 在設定EF600或EF300儲存陣列時、請確定每個控制器在前12個插槽中有相同數量的磁碟機、以及在最後12個插槽中有相同數量的磁碟機。此組態可協助控制器更有效地使用兩個磁碟機端PCIe匯流排。若要建立集區、您應該使用儲存陣列中的所有磁碟機。


.步驟
. 從「Manage（管理）」頁面中、選取集區的儲存陣列。
. 選取功能表：資源配置[設定資源池和磁碟區群組]。
. 選取功能表：More（更多）[啟動集區自動組態]。
+
結果表列出新的集區、新增磁碟機的現有集區、或兩者。新的資源池預設會以連續編號命名。

+
請注意、系統會執行下列動作：

+
** 如果有足夠數量的磁碟機具有相同的磁碟機類型（HDD或SSD）、而且容量相似、就會建立單一集區。
** 如果未指派的容量包含不同的磁碟機類型、則會建立多個資源池。
** 如果儲存陣列中已定義集區、則會將磁碟機新增至現有集區、並將相同磁碟機類型的新磁碟機新增至集區。
** 將相同磁碟機類型的磁碟機新增至現有的集區、如果新磁碟機類型不同、請使用其他磁碟機類型來建立不同的集區。


. 若要變更新集區的名稱、請按一下*編輯*圖示（鉛筆）。
. 若要檢視資源池的其他特性、請將游標放在資源池上、或輕觸詳細資料圖示（頁面）。
+
此時會顯示磁碟機類型、安全功能、資料保證（DA）功能、機櫃遺失保護及藥櫃遺失保護等相關資訊。

+
對於EF600和EF300儲存陣列、也會顯示資源配置和磁碟區區塊大小的設定。

. 按一下*接受*。

