---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-array-management-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 使用「新增/探索」功能、尋找並新增您要在組織網路中管理的儲存陣列。 
---
= 陣列管理總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用「新增/探索」功能、在vCenter的儲存外掛程式中尋找並新增您要管理的儲存陣列。您也可以從「管理」頁面重新命名、移除這些探索到的陣列、並提供新密碼。



== 探索陣列的考量事項

若要讓外掛程式顯示及管理儲存資源、您必須在組織的網路中探索您要管理的儲存陣列。您可以探索並新增單一陣列或多個陣列。



=== 多個儲存陣列

如果您選擇探索多個陣列、請輸入網路IP位址範圍、然後系統會嘗試個別連線至該範圍內的每個IP位址。任何已成功連線的儲存陣列都會出現在外掛程式中、您可以將其新增至管理網域。



=== 單一儲存陣列

如果您選擇探索單一陣列、請輸入儲存陣列中其中一個控制器的單一IP位址、然後將該陣列新增至管理網域。


NOTE: 外掛程式只會探索並顯示指派給控制器之範圍內的單一IP位址或IP位址。如果指派給這些控制器的替代控制器或IP位址超出此單一IP位址或IP位址範圍、則外掛程式將不會發現或顯示這些控制器或IP位址。不過、新增儲存陣列之後、所有相關的IP位址都會被探索並顯示在「管理」檢視中。



=== 使用者認證

您必須為要新增的每個儲存陣列提供管理員密碼。



=== 憑證

在探索過程中、系統會驗證探索到的儲存陣列是否使用受信任來源的憑證。系統會使用兩種類型的憑證型驗證、來驗證其與瀏覽器建立的所有連線：

* *信任的憑證*：如果其中一個或兩個控制器憑證已過期、撤銷或鏈結中缺少憑證、您可能需要安裝憑證授權單位所提供的其他信任憑證。
* *自我簽署的憑證*-陣列也可以使用自我簽署的憑證。如果您嘗試探索陣列而不匯入簽署的憑證、外掛程式會提供額外的步驟、讓您接受自我簽署的憑證。儲存陣列的自我簽署憑證會標示為信任、儲存陣列也會新增至外掛程式。如果您不信任儲存陣列的連線、請選取*取消*、然後在將儲存陣列新增至外掛程式之前驗證儲存陣列的安全性憑證策略。




== 儲存陣列狀態

當您開啟vCenter的儲存外掛程式時、會建立與每個儲存陣列的通訊、並顯示每個儲存陣列的狀態。

在「*管理-全部*」頁面中、您可以檢視儲存陣列的狀態和儲存陣列連線的狀態。

|===
| 狀態 | 表示 


| 最佳化 | 儲存陣列處於最佳狀態。沒有憑證問題、密碼有效。 


| 密碼無效 | 提供無效的儲存陣列密碼。 


| 不受信任的憑證 | 與儲存陣列的一或多個連線不受信任、因為HTTPS憑證為自我簽署且尚未匯入、或憑證已由CA簽署、且尚未匯入根和中繼CA憑證。 


| 需要注意 | 儲存陣列發生問題、需要您介入修正。 


| 穩固定位 | 儲存陣列處於鎖定狀態。 


| 不明 | 從未聯絡過儲存陣列。當外掛程式正在啟動、但尚未與儲存陣列聯絡、或儲存陣列離線、而且自外掛程式啟動後從未聯絡過時、就會發生這種情況。 


| 離線 | 外掛程式先前曾聯絡過儲存陣列、但現在已失去與儲存陣列的所有連線。 
|===


== 外掛程式介面相較於System Manager

您可以使用Storage Plugin for vCenter來執行儲存陣列上的基本作業工作、不過有時候您可能需要啟動System Manager來執行外掛程式中沒有的工作。

System Manager是儲存陣列控制器上的內嵌應用程式、透過乙太網路管理連接埠連線至網路。System Manager包含所有陣列型功能。

下表可協助您決定是否要使用外掛程式介面或System Manager介面來執行特定的儲存陣列工作。

|===
| 功能 | 外掛程式介面 | System Manager介面 


| 多個儲存陣列群組的批次作業 | 是的 | 不可以在單一陣列上執行作業。 


| 升級到作業系統韌體SANtricity | 是的。批次作業中的一個或多個陣列。 | 是的。僅限單一陣列。 


| 將設定從一個陣列匯入多個陣列 | 是的 | 否 


| 主機與主機叢集管理（建立、指派磁碟區、更新及刪除） | 是的 | 是的 


| 資源池與磁碟區群組管理（建立、更新、啟用安全性及刪除） | 是的 | 是的 


| Volume管理（建立、調整大小、更新及刪除） | 是的 | 是的 


| SSD快取管理（建立、更新及刪除） | 是的 | 是的 


| 鏡射與快照管理 | 否 | 是的 


| 硬體管理（檢視控制器狀態、設定連接埠連線、使控制器離線、啟用熱備援、清除磁碟機、 等） | 否 | 是的 


| 管理警示（電子郵件、SNMP和系統記錄） | 否 | 是的 


| 安全金鑰管理 | 否 | 是的 


| 控制器的憑證管理 | 否 | 是的 


| 控制器的存取管理（LDAP、SAML等） | 否 | 是的 


| 系統管理AutoSupport | 否 | 是的 
|===