---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-do-i-need-to-know-before-creating-a-security-key.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 安全金鑰由儲存陣列內的控制器和啟用安全功能的磁碟機共用。 
---
= 在建立安全金鑰之前、我需要知道什麼？
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
安全金鑰由儲存陣列內的控制器和啟用安全功能的磁碟機共用。如果從儲存陣列中移除啟用安全功能的磁碟機、安全金鑰會保護資料免於未經授權的存取。

您可以使用下列其中一種方法來建立及管理安全性金鑰：

* 控制器持續記憶體的內部金鑰管理。
* 外部金鑰管理伺服器上的外部金鑰管理。




== 內部金鑰管理

內部金鑰會在控制器的持續記憶體上不可存取的位置進行維護和「隱藏」。在建立內部安全金鑰之前、您必須執行下列動作：

. 在儲存陣列中安裝具有安全功能的磁碟機。這些磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。
. 確定磁碟機安全功能已啟用。如有必要、請聯絡您的儲存設備廠商、以取得啟用磁碟機安全功能的指示。


然後您可以建立內部安全金鑰、其中包括定義識別碼和密碼。識別碼是與安全金鑰相關聯的字串、儲存在控制器和與金鑰相關聯的所有磁碟機上。密碼用於加密安全金鑰以供備份之用。完成後、安全金鑰會儲存在無法存取的控制器位置。然後您可以建立啟用安全功能的Volume群組或集區、或是在現有的Volume群組和集區上啟用安全功能。



== 外部金鑰管理

外部金鑰是使用金鑰管理互通性傳輸協定（KMIP）、在獨立的金鑰管理伺服器上維護。在建立外部安全金鑰之前、您必須執行下列動作：

. 在儲存陣列中安裝具有安全功能的磁碟機。這些磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。
. 確定磁碟機安全功能已啟用。如有必要、請聯絡您的儲存設備廠商、以取得啟用磁碟機安全功能的指示
. 取得已簽署的用戶端憑證檔案。用戶端憑證會驗證儲存陣列的控制器、因此金鑰管理伺服器可以信任其KMIP要求。
+
.. 首先、您必須完成並下載用戶端憑證簽署要求（CSR）。前往功能表：設定[憑證>金鑰管理>完整的CSR ]。
.. 接下來、您會向金鑰管理伺服器信任的CA要求已簽署的用戶端憑證。（您也可以使用下載的CSR檔案、從金鑰管理伺服器建立及下載用戶端憑證。）
.. 擁有用戶端憑證檔案之後、請將該檔案複製到您要存取System Manager的主機。


. 從金鑰管理伺服器擷取憑證檔案、然後將該檔案複製到您正在存取System Manager的主機。金鑰管理伺服器憑證會驗證金鑰管理伺服器、因此儲存陣列可以信任其IP位址。您可以將根、中繼或伺服器憑證用於金鑰管理伺服器。


然後您可以建立外部金鑰、其中包括定義金鑰管理伺服器的IP位址、以及KMIP通訊所使用的連接埠號碼。在此過程中、您也會載入憑證檔案。完成後、系統會以您輸入的認證資料連線至金鑰管理伺服器。然後您可以建立啟用安全功能的Volume群組或集區、或是在現有的Volume群組和集區上啟用安全功能。
