---
permalink: maintenance-ef50-ef80/controller-replace-prepare.html 
sidebar: sidebar 
keywords: ef50, ef80, prepare the impaired controller 
summary: 準備更換 EF50 或 EF80 儲存系統中的故障控制器，方法是打開替換控制器的包裝、確認其零件編號正確，並備份組態資料庫。 
---
= 準備更換控制器 - EF50 和 EF80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要更換 EF50 或 EF80 儲存系統中的故障控制器，請開啟替換控制器的包裝，並記下其 MAC 位址、確認其零件號碼是否正確，並備份儲存系統的組態資料庫。

.步驟
. 打開替換控制器的包裝，將其放在平坦、無靜電的表面上。
+
請保留包裝材料，以便在退回故障控制器時使用。

. 記下更換控制器側面的 MAC 位址。
+
稍後在控制器更換程序中會用到 MAC 位址。

. 確認替換控制器上的零件編號與 SANtricity System Manager 中控制器的替換零件編號相同：
+

CAUTION: *可能導致資料存取遺失*：如果兩個零件編號不相同，請勿嘗試此程序。控制器不匹配會導致更換的控制器在上線時鎖定。

+
.. 記下更換控制器側面的零件編號。
.. 在 Recovery Guru 的詳細資料區域中找到故障控制器的替換零件編號。
+
如果您需要手動尋找此號碼，請遵循以下步驟：

+
... 選擇 *Hardware* > *Controllers and components* 。
... 選擇受損控制器的控制器圖形（Controller A 或 Controller B）以檢視內容功能表。
... 選取*檢視設定*。
... 在「*基礎*」索引標籤上、記下控制器的*更換零件編號*。


.. 比較兩個零件編號以確認它們是否相同。
.. 下一步取決於零件編號是否相同：
+
[cols="1,2"]
|===
| 如果... | 然後 ... 


 a| 
這兩個零件編號相同
 a| 
繼續進行下一步。



 a| 
這兩個零件編號不同
 a| 
您無法繼續執行此程序。

聯絡 https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]以尋求協助。

|===


. 使用 SANtricity System Manager 備份儲存系統的組態資料庫。
+
如果移除控制器時出現問題，您可以使用已儲存的檔案來還原設定。系統會保存 RAID 配置資料庫的目前狀態，其中包含控制器上所有磁碟區群組和磁碟集區的資料。

+
.. 選擇 * 支援›支援中心›診斷 * 。
.. 選擇*收集組態資料*。
.. 選擇 *Collect* 。
+
檔案會以*組態Data-<arrayName>-<DateTimer>.7z*的名稱儲存在瀏覽器的「下載」資料夾中。





.接下來呢？
做好控制器更換的準備工作後，link:controller-replace-offline-controller.html["使受損的控制器離線"]。
