---
permalink: maintenance-ef50-ef80/controller-replace-requirements.html 
sidebar: sidebar 
keywords: ef50, ef80, prerequisite, replace the controller module 
summary: 在更換 EF50 或 EF80 儲存系統中的控制器之前，請確保您已符合成功更換的所有需求。這包括確認您有一個故障的控制器、檢查儲存系統的狀態、準備執行程序所需的工具，以及擁有可存取 SANtricity System Manager 的管理工作站與瀏覽器。 
---
= 更換控制器的要求 - EF50 和 EF80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在更換 EF50 或 EF80 儲存系統中的控制器之前、請確保符合成功更換的要求。這包括驗證您有故障的控制器、驗證儲存系統的狀態、取得程序所需的項目、以及擁有管理站和瀏覽器以存取 SANtricity System Manager 。

* 請確認是否有故障控制器。您可以透過以下兩種方式確定：
+
** SANtricity System Manager 中的 Recovery Guru 指示你更換控制器。
** 控制器上的琥珀色 Attention LED 亮起，表示控制器故障。




* 請驗證儲存系統的以下條件是否成立，以確保您可以在儲存系統開啟並執行主機 I/O 作業的情況下更換故障控制器：
+
** 機箱中的第二個控制器具有最佳狀態。
** SANtricity System Manager 中 Recovery Guru 的詳細資料區域內的 *OK to remove* 欄位顯示為 *Yes*，表示現在可以安全地移除故障的控制器。


* 請確定您擁有下列項目：
+
** 替換控制器，其零件編號與您要更換的控制器相同。
** 或您已採取其他防靜電預防措施。
** 無靜態的平面工作表面。
** 用於識別您將從控制器上斷開連接的每條電纜的標籤。
** 具有瀏覽器的管理站，可以存取控制器的 SANtricity System Manager。
+
您可以透過瀏覽器指向控制器的網域名稱或 IP 位址來開啟 SANtricity System Manager 介面。

+
您也可以選擇使用命令列介面（CLI）來執行某些程序。使用 SANtricity System Manager 下載 CLI 套件（zip 檔案）：*Settings* > *System* > *Add-ons*，然後選擇 *Command Line Interface*。之後，您就可以在作業系統提示字元（例如 DOS C: 提示字元）下發出 CLI 命令。





.接下來呢？
在滿足控制器更換要求後，link:controller-replace-prepare.html["準備更換控制器"]。
