---
permalink: config-windows/install-storage-manager-for-smcli-task.html 
sidebar: sidebar 
keywords: install Storage Manager Windows, install CLI Windows, install command line interface, install Host Context Agent, install HCA, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 在Windows Express方法中安裝適用於CLI和HCA的Storage Manager。 
---
= 安裝SANtricity 適用於SMcli的Syn-Storage Manager SANtricity （適用於11.53版或更早版本的軟體）
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用SANtricity 的是版本11.53或更低版本的支援、您可以在SANtricity Management Station上安裝《支援資料》軟體、以協助管理陣列。

包含用於其他管理工作的命令列介面（CLI）、以及用於透過I/O路徑將主機組態資訊推送至儲存陣列控制器的主機內容代理程式。SANtricity


NOTE: 如果您使用SANtricity 的是版本11.60及更新版本的更新版本、則不需要執行下列步驟。《支援不安全的CLI》（SMcli）包含在《支援服務》的作業系統中、可透過《支援服務》（英文）的《支援服務》（英文）下載。SANtricity SANtricity SANtricity如需如何透過 SANtricity 系統管理員下載 SMCLI 的詳細資訊、請參閱 link:https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["下載 SANtricity 系統管理員線上說明下的命令列介面（ CLI ）主題"^]


NOTE: 從 SANtricity 軟體 11.80.1 版開始、不再支援主機內容代理程式。

.開始之前
請確定您擁有下列項目：

* 軟件11.53或更早版本。SANtricity
* 正確的系統管理員或超級使用者權限。
* 適用於下列最低需求的系統：SANtricity
+
** * RAM*：2 GB用於Java執行時間引擎
** *磁碟空間*：5 GB
** *作業系統/架構*：如需判斷支援作業系統版本與架構的指引、請前往 http://mysupport.netapp.com["NetApp支援"^]。從* Downloads *（下載*）索引標籤、前往功能表：Downloads（下載）[E系列SANtricity 支援儲存管理程式]。




.步驟
. 請至下載SANtricity 更新版本的《》 http://mysupport.netapp.com["NetApp支援"^]。從* Downloads（下載）*標籤、功能表：Downloads（下載）[E系列SANtricity 支援儲存管理程式]。
. 執行SANtricity 此安裝程式。按兩下要執行的SMIA*。exe安裝套件。
. 使用安裝精靈在Management Station上安裝軟體。

