---
permalink: upgrade-controllers/complete-upgrade-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, vendor ID, upgrade status, upgrade validate 
summary: 開啟控制器機櫃電源並驗證控制器軟體版本、以完成控制器升級。然後、您可以收集支援資料並恢復作業。 
---
= 完成控制器升級
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
開啟控制器機櫃電源並驗證控制器軟體版本、以完成控制器升級。然後、您可以收集支援資料並恢復作業。

如果您要升級雙工控制器磁碟機匣中的控制器、請重複所有步驟、完成第二個控制器的升級。



== 步驟1：開啟控制器電源

您必須開啟控制器機櫃電源、以確認其運作正常。

.步驟
. 開啟連接至控制器磁碟機匣的每個磁碟機匣背面的電源開關
. 等待兩分鐘、讓磁碟機加速運作。
. 開啟控制器磁碟機匣背面的電源開關
. 等待三分鐘、讓開機程序完成。
. 如果您要對E2800或E5700控制器執行完整的控制器更換、請根據您的磁碟機安全性案例、繼續執行下列其中一個程序。
+
|===
| 完整的控制器更換類型 | 程序與先決條件 


 a| 
所有不安全的磁碟機、無論是外部或內部金鑰管理
 a| 
繼續下一步。



 a| 
混合使用安全和不安全的磁碟機、內部金鑰管理
 a| 
您必須先建立內部安全金鑰、然後手動匯入安全金鑰、才能解除鎖定受保護的磁碟機。磁碟機解鎖後、您就可以存取磁碟機。

.. 建立內部安全金鑰
.. 控制器換用內部金鑰管理、並保護一或多個磁碟機




 a| 
所有安全磁碟機、內部金鑰管理
 a| 
控制器換用內部金鑰管理、並保護一或多個磁碟機



 a| 
混合使用安全和不安全的磁碟機、外部金鑰管理
 a| 
繼續下一步。

執行控制器更換之後、控制器會自動與外部金鑰管理伺服器重新同步、磁碟機將會解除鎖定並可供存取。


NOTE: 如果您在使用內部金鑰管理來更換混合式安全磁碟機的控制器之後、收到「L5」的七區段顯示鎖定代碼、請聯絡技術支援部門。



 a| 
所有安全磁碟機（外部金鑰管理）、您已暫時切換回內部金鑰管理、以進行控制器更換程序
 a| 
您必須先使用「內部金鑰管理」程序解除鎖定安全磁碟機。磁碟機解除鎖定後、您可以建立新的外部安全金鑰來轉換回外部金鑰管理。

.. 控制器換用內部金鑰管理、並保護一或多個磁碟機
.. 建立外部安全金鑰




 a| 
所有受保護的磁碟機、外部金鑰管理、您尚未暫時切換至內部金鑰管理來進行控制器更換程序
 a| 
控制器可與外部金鑰管理及所有受保護的磁碟機交換

|===




== 步驟2：檢查控制器和磁碟匣的狀態

您可以使用LED和儲存管理軟體來檢查控制器和磁碟匣的狀態。

.步驟
. 查看控制器A上的LED、確定其開機正確。
+
重新開機期間、Host Link Service Action Required LED會變成綠色。七區段顯示器會顯示OS+ SD+空白順序、表示控制器正在執行「營業開始」（SOD）處理。

+
控制器成功完成重新開機之後、七段顯示器會顯示與第二個控制器上的七段顯示器相符的匣ID。然後您可以使用儲存管理軟體來探索新的控制器容器。

. 如果控制器磁碟機匣的任何「需要維修行動」LED為_on_、或「需要控制器維修行動」LED為_on_：
+
.. 檢查控制器機箱是否安裝正確、以及所有纜線是否都已正確安裝。如有必要、請重新安裝控制器容器。
.. 再次檢查控制器磁碟機匣的「Service Action Required（需要維修行動）」LED和「Controller Service Action Required（需要控制器維修行動）」LED。如果問題仍未解決、請聯絡技術支援部門。


. 對於雙工組態、請針對控制器B重複步驟1到步驟2
. 使用LED和儲存管理軟體、檢查儲存陣列中所有磁碟匣的狀態。如果有任何元件處於Needs Attention（需要注意）狀態、請使用Recovery Guru進行疑難排解。如果問題仍未解決、請聯絡技術支援部門。




== 步驟3：驗證控制器軟體版本

您必須確保新的控制器以正確的作業系統（控制器韌體）層級和NVSRAM.

.步驟
. 執行下列其中一項：
+
** 如果您要升級至不支援SANtricity 還原11.30和控制器韌體8.30的控制器、請確定新控制器上執行的版本與上次在原始控制器上執行的版本相符。通常、這是舊控制器支援的最新版本。如有必要、請在新的控制器上安裝適當的版本。
** 如果您要升級至執行SANtricity 《SKEE11.30》和控制器韌體8.30的控制器、請在開啟新控制器電源後、下載並安裝最新的NVSRAM.


. 如果您的控制器升級涉及傳輸協定變更（例如、光纖通道至iSCSI）、而且您已為儲存陣列定義主機、請將新的主機連接埠與主機建立關聯：
+
.. 從System Manager中選取功能表：Storage[hosts]。
.. 選取連接埠要關聯的主機、然後按一下「*檢視/編輯設定*」。
+
此時會出現一個對話方塊、顯示目前的主機設定。

.. 單擊*主機端口*選項卡。
+
對話方塊會顯示目前的主機連接埠識別碼。

.. 若要更新與每個主機相關聯的主機連接埠識別資訊、請將舊主機介面卡的主機連接埠識別碼、以新主機介面卡的新主機連接埠識別碼取代。
.. 對每個主機重複步驟d。
.. 按一下「 * 儲存 * 」。


+
如需相容硬體的相關資訊、請參閱 https://mysupport.netapp.com/NOW/products/interoperability["NetApp 互通性對照表"^] 和 http://hwu.netapp.com/home.aspx["NetApp Hardware Universe"^]。

. 如果在準備進行外框交換時、所有精簡磁碟區的「Write Back快取」都已停用、請重新啟用「Write Back快取」。
+
.. 從System Manager中選取功能表：Storage[磁碟區]。
.. 選取任何Volume、然後選取功能表：More（更多）[變更快取設定]。
+
「變更快取設定」對話方塊隨即出現。儲存陣列上的所有磁碟區都會顯示在此對話方塊中。

.. 選取* Basic *索引標籤、然後變更讀取快取和寫入快取的設定。
.. 按一下「 * 儲存 * 」。


. 如果在準備外框時停用SAML、請重新啟用SAML。
+
.. 從System Manager中選取功能表：設定[Access Management（存取管理）]。
.. 選取「* SAML *」索引標籤、然後依照頁面上的指示進行。


. 使用GUI或CLI收集有關儲存陣列的支援資料：
+
** 使用System Manager或Storage Manager的Array Management（陣列管理）窗口來收集並儲存儲存儲存陣列的支援產品組合。
+
*** 從System Manager中、選取功能表：Support（支援）[Support Center（支援中心）> Diagnostics（診斷）索引標籤]。然後選擇*收集支援資料*、再按一下*收集*。
*** 從Array Management（陣列管理）視窗工具列中、選取功能表：Monitor（監控）[Health（健全狀況）> Collect Support Data Manually（手動收集支援資料然後輸入名稱、並在系統上指定您要儲存支援服務組合的位置。
+
檔案會以「support-data.7z」的名稱儲存在瀏覽器的「下載」資料夾中。

+
如果您的磁碟櫃含有抽取器、則該磁碟櫃的診斷資料會歸檔在名為「tray -component-state -capture」的單獨壓縮檔案中



** 使用CLI執行「儲存陣列supportData」命令、收集有關儲存陣列的完整支援資料。
+

NOTE: 收集支援資料可能會暫時影響儲存陣列的效能。



. 提醒NetApp技術支援人員您對儲存陣列組態所做的變更。
+
.. 取得您在中記錄的控制器磁碟機匣序號 xref:prepare-upgrade-controllers-task.adoc[準備升級控制器]。
.. 登入NetApp支援網站： http://mysupport.netapp.com/eservice/assistant["mysupport.netapp.com/eservice/assistant"^]。
.. 從「*類別1*」下的下拉式清單中選取「*產品註冊*」。
.. 在「**Comments」（留言）文字方塊中輸入下列文字、將控制器磁碟機匣的序號取代為序號：
+
「請針對序號建立警示：序號。警示名稱應為「E系列升級」。警示文字應如下

+
「請注意：此系統中的控制器已從原始組態升級。訂購更換控制器之前、請先確認控制器組態、並通知派單系統已升級。

.. 按一下表單底部的*提交*按鈕。




如果您的控制器升級導致廠商ID從LSI變更為NetApp、請前往 link:remount-volumes-lsi-task.html["將廠商從LSI改為NetApp之後、重新掛載磁碟區"]；否則、您的控制器升級已完成、您可以恢復正常作業。
