---
permalink: upgrade-controllers/install-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, installing new controller, install new controller, install battery, installing battery, install controller canister 
summary: 移除舊控制器之後、您可以在控制器磁碟機匣中安裝新的控制器 
---
= 安裝新的控制器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
移除舊控制器之後、您可以在控制器磁碟機匣中安裝新的控制器

.關於這項工作
對控制器磁碟機匣中的每個控制器執行下列步驟如果您要升級雙工控制器磁碟機匣中的控制器、請重複所有步驟以安裝第二個控制器磁碟櫃。

.開始之前
請確定您擁有下列項目：

* 或採取其他防靜電預防措施。
* 原始控制器容器中的電池或您訂購的新電池。
* 新的控制器容器。




== 步驟1：安裝電池

安裝從原控制器容器或您訂購的新電池中取出的電池。

.步驟
. 打開新的控制器外殼、將其放在無靜電的平面上、使可拆式外蓋面朝上。
. 按下機箱蓋按鈕、然後將機箱蓋滑出。
. 調整控制器機箱的方向、使電池插槽朝向您。
. 視您的控制器機型而定、請執行下列其中一項：
+
** 對於E2600或E2700控制器機型：
+
... 將電池電路板滑向新控制器箱的正面、以插入電池電路板。
... 鎖緊指旋螺絲、將電池電路板固定在新的控制器容器卡中。
... 將新控制器容器的頂蓋往前推、直到頂蓋卡住為止、即可重新安裝。
+
當栓鎖卡入定位時、栓鎖底部會掛入機箱的金屬插槽。



** 對於其他控制器機型：
+
... 將電池插入新的控制器容器。
+
將電池滑入電池箱、確保電池位於新電池箱壁上的鉚釘下方。

... 鎖定握把保持45度角、將電池底部的連接器與電池箱上的連接器對齊。
... 將電池向下推、直到聽到卡住的聲音、然後向上移動鎖定把把、將控制器電池固定在控制器箱上。
+

TIP: 若要確定控制器電池已正確安裝在E5XX控制器磁碟機匣中、您可能需要將其滑出並重新插入。當您聽到卡入定位的聲音、以及當您搬移鎖定握把時、鎖定握把不會移出直立位置時、就會很安全。

... 將新控制器容器的頂蓋往前推、直到頂蓋卡住為止、即可重新安裝。
+
當栓鎖卡入定位時、栓鎖底部會掛入機箱的金屬插槽。





. 翻轉控制器機箱、確認電池安裝正確。




== 步驟2：安裝新的控制器容器

將新的控制器容器安裝到控制器機櫃中。

.步驟
. 將新的控制器容器完全滑入控制器磁碟機匣將釋放槓桿朝控制器箱的中央轉動、將其鎖定到位。
. 如果您的新控制器外殼具有Fibre Channel HIC或InfiniBand HIC、請將SFP+收發器（Fibre Channel）或QSFP+收發器（InfiniBand）安裝到控制器外殼、然後重新連接主機纜線。
+
視升級所涉及的HIC而定、您可能可以重複使用從舊控制器容器中移除的SFP+收發器或QSFP+收發器。

. 重新連接控制器磁碟機匣與磁碟機匣之間的所有纜線。
+
如果磁碟機纜線組態與舊控制器相同、請使用連接至纜線的標籤來正確重新連接纜線。

+

NOTE: 如果您從較早的機型升級至E2700控制器、則磁碟機纜線組態可能與舊控制器所使用的組態不同。



.接下來呢？
如果您要升級E2800和E5700控制器、而且已啟用磁碟機安全功能、請前往 link:upgrade-unlock-drives-task.html["解除磁碟機鎖定"]。否則、請前往 link:complete-upgrade-controllers-task.html["完成控制器升級"]。
