---
permalink: upgrade-controllers/overview-requirements-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade compatibility, upgrade SAS shelf, upgrade SAS shelves, upgrade SAS enclosures, SAS-2 to SAS-3 
summary: 檢閱E系列控制器的升級與更換需求。 
---
= 升級考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
升級控制器之前、請先檢閱下列考量事項。


NOTE: 如需每個 E 系列控制器支援組態的特定資訊，請參閱 https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#e2800-models["E系列硬體總覽"]。



== 硬體與韌體需求

* *雙工和單工控制器升級*
+
對於雙工控制器磁碟機匣、您需要更換兩個控制器。對於單工控制器磁碟機匣、您需要更換一個控制器。在這兩種情況下、您都必須關閉控制器磁碟機匣的電源因此、在成功完成更換之前、您無法存取儲存陣列上的資料。

* *磁碟櫃與磁碟櫃*
+
具有 E 系列控制器機櫃的儲存陣列通常是使用 SANtricity System Manager 使用者介面來管理。

* *控制器電池*
+
新的控制器在出貨時未安裝電池。如果可能、您應該從舊的控制器取出電池、然後將該電池安裝到新的控制器中。但是、對於某些控制器升級、舊控制器的電池與新控制器不相容。在這些情況下、您必須在新的控制器上訂購電池、並在開始執行這些工作之前、先準備好該電池。

* *同步鏡像和非同步鏡像*
+
如果您的儲存陣列參與同步鏡射、則主站台與遠端站台之間只支援iSCSI或Fibre Channel連線。如果新控制器中的主機介面卡（HIC）組態不包含iSCSI或Fibre Channel連線、則不支援同步鏡像。

+
對於非同步鏡射、本機儲存陣列和遠端儲存陣列可執行不同版本的韌體。支援的最低韌體版本為SANtricity 版本7.84。




NOTE: 對於 E4000 控制器，鏡射僅支援光纖通道連線。

* *儲存物件限制*
+
如果您將控制器從中階模式變更為入門級機型（例如， 5x00 機型變更為 2x00 機型），則新的儲存陣列組態會比舊組態支援較少的儲存管理軟體中部分儲存物件（例如， Volume ）數量。您必須確保舊組態不超過儲存物件限制。

+
如需詳細資訊、請參閱 http://hwu.netapp.com/home.aspx["Hardware Universe"^] 。

* * 升級至較新機型 *
+
如果您要更換控制器以升級至新機型、請記住、您目前的儲存陣列可能安裝新機型無法支援的優質功能。

+
升級 E 系列控制器時，您應該停用新控制器不支援的儲存陣列上所使用的任何進階功能。

* * 使用存取 Volume * 進行頻內管理
+
** E4000 不支援使用 Access Volume 進行頻內管理。
+
在升級至 E4000 控制器之前，請先取消對應所有已定義主機和主機叢集的存取磁碟區。







== 升級相容性

檢閱各儲存陣列機型支援的升級途徑。

[role="tabbed-block"]
====
.E4000 控制器升級相容性
--
[cols="h,d,d,d"]
|===
| 升級途徑 | 電池 | 功能支援 | SAS-3磁碟櫃 


| 從E2800到E4000  a| 
訂購新電池。
 a| 
* E4000 不支援 ARVM iSCSI
* E4000 底板連接埠僅限 iSCSI ，無法變更為 FC
* E4000 只能支援 300 個磁碟機
* E4000 只能支援 512 個磁碟區
* E4000 不支援 SAS 組態
* E4000 不支援遠端儲存磁碟區
* E4000 不支援使用 Access Volume 進行頻內管理。

 a| 
E4000 控制器必須使用 SAS-3 機櫃。



| 從E5700到E4000  a| 
訂購新電池。
 a| 
* E4000 不支援 ARVM iSCSI
* E4000 底板連接埠僅限 iSCSI ，無法變更為 FC
* E4000 只能支援 300 個磁碟機
+
** E5700 最多可支援 480 個磁碟機


* E4000 只能支援 512 個磁碟區
+
** E5700 最多可支援 2048 個磁碟區


* InfiniBand 主機介面卡支援無法使用
* E4000 不支援 SAS 組態
* E4000 不支援遠端儲存磁碟區
* E4000 不支援使用 Access Volume 進行頻內管理。

 a| 
E4000 控制器必須使用 SAS-3 機櫃。

|===
--
.EF600 與 EF300 控制器升級相容性
--
[cols="h,d,d,d"]
|===
| 升級途徑 | 電池 | 功能支援 | SAS-3磁碟櫃 


| 使用不同的主機介面卡，從 EF600 到 EF600  a| 
重複使用舊電池。
 a| 
* 不支援精簡配置的磁碟區
* 不支援同步鏡射

| EF600 控制器必須使用 SAS-3 機櫃。 


| 從EF300到EF600  a| 
重複使用舊電池。
 a| 
* 不支援精簡配置的磁碟區
* 不支援同步鏡射

 a| 
EF600 控制器必須使用 SAS-3 機櫃。

|===
--
.舊版控制器升級相容性
--
[cols="h,d,d,d,d"]
|===
| 升級途徑 | 電池 | 廠商ID | 功能支援 | SAS-3磁碟櫃 


| 從E2x00到E2x00  a| 
重複使用舊電池。
 a| 
需要其他步驟。
 a| 
E2700 不支援舊版快照。
 a| 
E2800控制器不得放入SAS-2磁碟櫃。



| 從E2x00到E5x00  a| 
訂購新電池。
 a| 
從 E2600 升級至 E5500 或 E5600 ，或從 E2700 升級至 E5400 時，需要執行其他步驟。
 a| 
* E5500或E5600不支援舊版快照。
* 使用iSCSI HIC的E5500或E5600不支援舊版遠端Volume鏡像（RVM）。
* E5500或E5600不支援搭配iSCSI HIC的資料保證。
* E5700控制器不得放入SAS-2磁碟櫃。

 a| 
E5400 ， E5500 和 E5600 控制器不得放入 SAS-3 機櫃。



| 從E5x00到E2x00  a| 
訂購新電池。
 a| 
從 E5500 或 E5600 升級至 E2600 ，或從 E5400 升級至 E2700 時，需要執行其他步驟。
 a| 
E2700 不支援舊版快照。
 a| 
5400 ， E5500 和 E5600 控制器不得放入 SAS-3 機櫃。



| 從E5x00到E5x00  a| 
重複使用舊電池。
 a| 
從 E5400 升級至 E5500 或 E5600 時所需的其他步驟。
 a| 
* E5500或E5600不支援舊版快照。
* E5400或E5500搭配iSCSI HIC不支援舊版遠端Volume鏡像（RVM）。
* E5400或E5500不支援iSCSI HIC的資料保證。
* E5700控制器不得放入SAS-2磁碟櫃。

 a| 
E5400 ， E5500 和 E5600 控制器不得放入 SAS-3 機櫃。



| 從EF5x0到EF5x0  a| 
重複使用舊電池。
 a| 
從 EF540 升級至 EF550 或 EF560 時所需的其他步驟。
 a| 
* EF51/EF560沒有舊快照。
* 對於採用iSCSI的EF51/EF560、不提供資料保證。
* EF570控制器不得放入SAS-3磁碟櫃。

 a| 
EF540 ， EF550 和 EF560 控制器不得放入 SAS-3 機櫃。

|===
--
====


== SAS機箱

E5700可透過機頭升級、支援DE5600和DE6600 SAS-2機箱。在SAS-2機箱中安裝E5700控制器時、會停用對基礎主機連接埠的支援。

|===
| SAS-2磁碟櫃 | SAS-3磁碟櫃 


 a| 
SAS-2磁碟櫃包括下列機型：

* DE1600、DE5600及DE6600磁碟機匣
* E5400、E5500及E5600控制器磁碟機匣
* EF540、EF550和EF560 Flash Array
* E2600和E2700控制器磁碟機匣

 a| 
SAS-3磁碟櫃包括下列機型：

* E4000控制器機櫃
* EF600 控制器機櫃 ^1^
* EF300 控制器機櫃 ^1^
* E2800控制器機櫃
* E5700控制器機櫃
* DE212C、DE224C、DE460C磁碟機櫃


|===
附註：

. EF600 和 EF300 控制器只能使用 SAS-3 機櫃進行擴充。




== SAS-2至SAS-3投資保護

您可以將SAS-2系統重新設定為在新的SAS-3控制器機櫃（E57XX/EF570/E28XX）後方使用。


NOTE: 此程序需要功能產品差異要求（FPVR）。若要歸檔FPVR、請聯絡您的銷售團隊。
