---
permalink: upgrade-controllers/overview-requirements-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade compatibility, upgrade SAS shelf, upgrade SAS shelves, upgrade SAS enclosures, SAS-2 to SAS-3 
summary: 檢閱E系列控制器的升級與更換需求。 
---
= 升級考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
升級控制器之前、請先檢閱下列考量事項。



== 硬體與韌體需求

* *雙工和單工控制器升級*
+
對於雙工控制器磁碟機匣、您需要更換兩個控制器。對於單工控制器磁碟機匣、您需要更換一個控制器。在這兩種情況下、您都必須關閉控制器磁碟機匣的電源因此、在成功完成更換之前、您無法存取儲存陣列上的資料。

* *磁碟櫃與磁碟櫃*
+
搭載E2800或E5700控制器機櫃的儲存陣列、通常是以SANtricity 《支援系統管理程式》使用者介面來管理。您也可以使用SANtricity 「NetApp儲存管理程式」介面來管理E2800或E5700控制器機櫃。本程序中提及的所有其他控制器磁碟機匣、都使用SANtricity 《不支援儲存管理程式》。

* *控制器電池*
+
新的控制器在出貨時未安裝電池。如果可能、您應該從舊的控制器取出電池、然後將該電池安裝到新的控制器中。但是、對於某些控制器升級、舊控制器的電池與新控制器不相容。在這些情況下、您必須在新的控制器上訂購電池、並在開始執行這些工作之前、先準備好該電池。

* *廠商識別*
+
某些控制器升級會導致SCSI查詢資料中的廠商ID從「LSI」變更為「NetApp」。當廠商ID從「LSI」變更為「NetApp」時、Windows、VMware及AIX作業系統需要採取額外步驟來回收裝置。這些作業系統的步驟已包含在此升級程序中。

* *同步鏡像和非同步鏡像*
+
如果您的儲存陣列參與同步鏡射、則主站台與遠端站台之間只支援iSCSI或Fibre Channel連線。如果新控制器中的主機介面卡（HIC）組態不包含iSCSI或Fibre Channel連線、則不支援同步鏡像。

+
對於非同步鏡射、本機儲存陣列和遠端儲存陣列可執行不同版本的韌體。支援的最低韌體版本為SANtricity 版本7.84。

* *儲存物件限制*
+
如果您將控制器從5X00機型變更為2x00機型、新的儲存陣列組態將可支援儲存管理軟體中部分儲存物件（例如磁碟區）的數量、比舊組態少。您必須確保舊組態不超過儲存物件限制。請參閱 http://hwu.netapp.com/home.aspx["Hardware Universe"^] 以取得更多資訊。





== 升級至較新機型

如果您要更換控制器以升級至新機型、請記住、您目前的儲存陣列可能安裝新機型無法支援的優質功能。例如、E2700控制器不支援舊版Snapshot優質功能。

如果您將E2600控制器更換為E2700控制器、而您的儲存陣列使用舊版Snapshot功能、則必須停用該功能、並在更換控制器之前刪除或轉換與該功能相關的所有磁碟區（即快照、儲存庫）。您可以將舊的Snapshot轉換成更新的Snapshot功能。在升級控制器磁碟機匣之前、您應該停用新控制器不支援的儲存陣列所使用的任何優質功能。



== 升級相容性

[role="lead"]
檢閱各儲存陣列機型支援的升級途徑。



=== 從E2x00到E2x00

* *電池*：重複使用舊電池。
* *廠商ID*：需要其他步驟。
* *功能支援*：E2700不支援舊版快照。
* * SAS-2磁碟櫃*：E2800控制器不得放入SAS-2磁碟櫃。




=== 從E2x00到E5x00

* *電池*：訂購新電池。
* *廠商ID*：從E2600升級至E5500或E5600時、或從E2700升級至E5400時、需要執行其他步驟。
* *功能支援*：
+
** E5500或E5600不支援舊版快照。
** 使用iSCSI HIC的E5500或E5600不支援舊版遠端Volume鏡像（RVM）。
** E5500或E5600不支援搭配iSCSI HIC的資料保證。
** E5700控制器不得放入SAS-2磁碟櫃。


* * SAS-3磁碟櫃*：E5400、E5500及E5600控制器不得放入SAS-3磁碟櫃。




=== 從E5x00到E2x00

* *電池*：訂購新電池。
* *廠商ID*：從E5500或E5600升級至E2600、或從E5400升級至E2700時、需要執行其他步驟。
* *功能支援*：E2700不支援舊版快照。
* * SAS-3磁碟櫃*：E5400、E5500及E5600控制器不得放入SAS-3磁碟櫃。




=== 從E5x00到E5x00

* *電池*：重複使用舊電池。
* *廠商ID*：從E5400升級至E5500或E5600時需要執行其他步驟。
* *功能支援*：
+
** E5500或E5600不支援舊版快照。
** E5400或E5500搭配iSCSI HIC不支援舊版遠端Volume鏡像（RVM）。
** E5400或E5500不支援iSCSI HIC的資料保證。
** E5700控制器不得放入SAS-2磁碟櫃。


* * SAS-3磁碟櫃*：E5400、E5500及E5600控制器不得放入SAS-3磁碟櫃。




=== 從EF5x0到EF5x0

* *電池*：重複使用舊電池。
* *廠商ID*：從EF540升級至EF550或EF560時所需的其他步驟。
* *功能支援*：
+
** EF51/EF560沒有舊快照。
** 對於採用iSCSI的EF51/EF560、不提供資料保證。
** EF570控制器不得放入SAS-3磁碟櫃。


* * SAS-3磁碟櫃*：EF540、EF550和EF560控制器不得放入SAS-3磁碟櫃。




=== SAS機箱

E5700可透過機頭升級、支援DE5600和DE6600 SAS-2機箱。在SAS-2機箱中安裝E5700控制器時、會停用對基礎主機連接埠的支援。

|===
| SAS-2磁碟櫃 | SAS-3磁碟櫃 


 a| 
SAS-2磁碟櫃包括下列機型：

* DE1600、DE5600及DE6600磁碟機匣
* E5400、E5500及E5600控制器磁碟機匣
* EF540、EF550和EF560 Flash Array
* E2600和E2700控制器磁碟機匣

 a| 
SAS-3磁碟櫃包括下列機型：

* E2800控制器機櫃
* E5700控制器機櫃
* DE212C、DE224C、DE460C磁碟機櫃


|===


=== SAS-2至SAS-3投資保護

您可以將SAS-2系統重新設定為在新的SAS-3控制器機櫃（E57XX/EF570/E28XX）後方使用。


NOTE: 此程序需要功能產品差異要求（FPVR）。若要歸檔FPVR、請聯絡您的銷售團隊。
