---
permalink: upgrade-controllers/prepare-upgrade-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade controller key management, prepare upgrade controller, upgrade controller preparation, preparing controller upgrade 
summary: 準備升級控制器、方法是儲存磁碟機安全金鑰、收集支援資料、以及使控制器離線。 
---
= 準備升級控制器
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存磁碟機安全金鑰（如果使用）、記錄序號、收集支援資料、停用某些功能（如果使用）、以及使控制器離線、以準備升級控制器。


NOTE: 收集支援資料可能會暫時影響儲存陣列的效能。

.步驟
. 請確定現有的儲存陣列已更新至目前控制器可用的最新版本作業系統（控制器韌體）。從「支援系統管理程式」、前往功能表：「支援」（Upgrade Center）以檢視您的軟體和韌體庫存。SANtricity
+

NOTE: 如果您要升級至支援SANtricity SRAOS 8.50版的控制器、則必須SANtricity 在安裝新控制器並開啟電源後、安裝最新版的作業系統和最新的NVSRAM.如果您不執行此升級、可能無法將儲存陣列設定為自動負載平衡（ALb）。

. 如果您正在執行完整的控制器更換、同時也在使用磁碟機安全功能、請依照下表中的安全類型（內部或外部）和磁碟機狀態、完成適當的步驟。
+

NOTE: 磁碟機安全性是一項儲存陣列功能、可透過全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機提供額外的安全層級。當這些磁碟機搭配磁碟機安全功能使用時、它們需要安全金鑰才能存取其資料。

+
|===
| 安全性類型與內容 | 步驟 


 a| 
內部金鑰管理、一個或多個磁碟機已鎖定
 a| 
.. 將內部安全金鑰檔案匯出至管理用戶端上的已知位置（使用瀏覽器存取System Manager的系統）。使用「匯出storageArray securityKey」CLI命令。您必須提供與安全金鑰相關的密碼、並指定要儲存命令的位置。如需使用此命令的相關資訊、請參閱_Command Line Reference。
.. 瞭解與內部安全金鑰相關的密碼。




 a| 
外部金鑰管理（所有磁碟機都已鎖定）、您可以暫時轉換至內部金鑰管理、以更換控制器（建議）。
 a| 
請依序執行下列步驟：

.. 記錄外部KMS伺服器位址和連接埠號碼。從系統管理員移至功能表：設定[系統>安全金鑰管理>檢視/編輯金鑰管理伺服器設定]。
.. 請確定本機主機上有可用的用戶端和伺服器憑證、以便在控制器更換完成後、儲存陣列和金鑰管理伺服器能夠相互驗證。使用「儲存陣列keyManagementCertificate」（儲存陣列金鑰管理憑證）CLI命令來儲存憑證。請務必執行兩次命令、一次將「certicateType」參數設為「client」、另一次則將參數設為「伺服器」。如需使用此命令的相關資訊、請參閱_Command Line Reference。
.. 執行「停用storageArray externalKeyManagement」CLI命令、轉換至內部金鑰管理。
.. 將內部安全金鑰檔案匯出至管理用戶端上的已知位置（使用瀏覽器存取System Manager的系統）。使用「匯出storageArray securityKey」CLI命令。您必須提供與安全金鑰相關的密碼、並指定要儲存命令的位置。如需使用此命令的相關資訊、請參閱_Command Line Reference。
.. 瞭解與內部安全金鑰相關的密碼。




 a| 
外部金鑰管理（所有磁碟機均已鎖定）、您無法暫時轉換至內部金鑰管理、以更換控制器。
 a| 
請依序執行下列步驟：

.. 記錄外部KMS伺服器位址和連接埠號碼。從系統管理員移至功能表：設定[系統>安全金鑰管理>檢視/編輯金鑰管理伺服器設定]。
.. 請確定本機主機上有可用的用戶端和伺服器憑證、以便在控制器更換完成後、儲存陣列和金鑰管理伺服器能夠相互驗證。使用「儲存陣列keyManagementCertificate」（儲存陣列金鑰管理憑證）CLI命令來儲存憑證。請務必執行兩次命令、一次將「certicateType」參數設為「client」、另一次則將參數設為「伺服器」。如需使用此命令的相關資訊、請參閱_Command Line Reference。




 a| 
外部金鑰管理、部分磁碟機已鎖定
 a| 
無需執行其他步驟。

|===



NOTE: 您的儲存陣列必須處於最佳狀態、才能擷取用戶端和伺服器憑證。如果無法擷取憑證、則必須建立並簽署新的CSR、並從EKMS下載伺服器憑證。

. 記錄儲存陣列的序號：
+
.. 從System Manager中、選取功能表：Support（支援中心）> Support Resources（支援資源）索引標籤。
.. 向下捲動至*啟動詳細的儲存陣列資訊*、然後選取*儲存陣列設定檔*。
+
報告會出現在您的螢幕上。

.. 若要在儲存陣列設定檔下找到機箱序號、請在*尋找*文字方塊中輸入*序號*、然後按一下*尋找*。
+
所有相符的詞彙都會反白顯示。若要逐一捲動所有結果、請繼續按一下「*尋找*」。

.. 記錄「機箱序號」。
+
您需要此序號才能執行中的步驟 link:complete-upgrade-controllers-task.html["完成控制器升級"]。



. 使用GUI或CLI收集有關儲存陣列的支援資料：
+
** 使用Storage Manager中的System Manager或Array Management（陣列管理）窗口來收集和保存儲存儲存陣列的支援產品組合。
+
*** 從System Manager中、選取功能表：Support（支援）[Support Center（支援中心）> Diagnostics（診斷）索引標籤]。然後選擇*收集支援資料*、再按一下*收集*。
*** 從Array Management（陣列管理）視窗工具列中、選取功能表：Monitor（監控）[Health（健全狀況）> Collect Support Data Manually（手動收集支援資料然後輸入名稱、並在系統上指定您要儲存支援服務組合的位置。
+
檔案會以「support-data.7z」的名稱儲存在瀏覽器的「下載」資料夾中。

+
如果您的磁碟櫃含有抽取器、則該磁碟櫃的診斷資料會歸檔在名為「tray -component-state -capture」的單獨壓縮檔案中。



** 使用CLI執行「儲存陣列supportData」命令、收集有關儲存陣列的完整支援資料。


. 確保儲存陣列與所有連線主機之間不會發生I/O作業：
+
.. 停止所有涉及從儲存設備對應至主機之LUN的程序。
.. 確保沒有任何應用程式將資料寫入從儲存設備對應至主機的任何LUN。
.. 卸載陣列上與磁碟區相關的所有檔案系統。
+

NOTE: 停止主機I/O作業的確切步驟取決於主機作業系統和組態、而這些步驟超出這些指示的範圍。如果您不確定如何停止環境中的主機I/O作業、請考慮關閉主機。

+

CAUTION: *可能的資料遺失*-如果您在執行I/O作業時繼續執行此程序、您可能會遺失資料。



. 如果儲存陣列參與鏡射關係、請停止次要儲存陣列上的所有主機I/O作業。
. 如果您使用的是非同步或同步鏡射、請刪除任何鏡射配對、並透過System Manager或Array Management視窗停用任何鏡射關係。
. 如果有精簡配置的磁碟區報告給主機為精簡磁碟區、而舊陣列執行的韌體（8.25韌體或更新版本）支援取消對應功能、請停用所有精簡磁碟區的「Write Back快取」：
+
.. 從System Manager中選取功能表：Storage[磁碟區]。
.. 選取任何Volume、然後選取功能表：More（更多）[變更快取設定]。
+
「變更快取設定」對話方塊隨即出現。儲存陣列上的所有磁碟區都會顯示在此對話方塊中。

.. 選取* Basic *索引標籤、然後變更讀取快取和寫入快取的設定。
.. 按一下「 * 儲存 * 」。
.. 等待五分鐘、讓快取記憶體中的任何資料都能排清到磁碟。


. 如果控制器上已啟用安全聲明標記語言（SAML）、請聯絡技術支援部門以停用SAML驗證。
+

NOTE: 啟用SAML之後、您無法透過SANtricity 「支援系統管理程式」介面來停用它。若要停用SAML組態、請聯絡技術支援部門以取得協助。

. 請等待所有進行中的作業完成、然後再繼續下一步。
+
.. 在System Manager的* Home*頁面中、選取* View Operations in progress*。
.. 繼續之前、請先確認「*作業進行中*」視窗上顯示的所有作業均已完成。


. 關閉控制器磁碟機匣的電源
+
等待控制器磁碟機匣上的所有LED變暗。

. 關閉連接至控制器磁碟機匣的每個磁碟機匣的電源
+
等待兩分鐘、讓所有磁碟機都能停止運轉。



前往 link:remove-controllers-task.html["移除控制器"]。
