---
permalink: upgrade-controllers/reconfigure-sas-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, reconfigure SAS-2, SAS-2, SAS-3, convert controller shelf, convert drive shelf, 
summary: 您可以將核准的SAS-2陣列（E2700、E550/EF5500、E5600/EF560）中的控制器機櫃轉換成磁碟機櫃、然後將該機櫃和任何相關核准的SAS-2磁碟機櫃（DE1600、DE5600、DE6600）放在新核准的SAS-3陣列（E2800、E5700/EF570）和認可的SAS-3磁碟櫃（DE224C）後面、DE2-C 不保留資料。 
---
= 在新的SAS-3控制器機櫃後方重新設定SAS-2系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如有必要、您可以將SAS-2系統重新設定為在新的SAS-3控制器機櫃後方使用。

獲核准的SAS-2陣列包括E2700、E550/EF5500及E5600/EF560。認可的SAS-2磁碟機櫃包括DE1600、DE5600和DE6600。認可的SAS-3陣列包括E2800和E57B/EF570。認可的SAS-3磁碟機櫃包括DE212C、DE224C和DE460C。

.關於這項工作
在本程序中、您可以將核准的SAS-2陣列中的控制器磁碟櫃轉換成磁碟機櫃、然後將該磁碟櫃放在新核准的SAS-3陣列和磁碟機櫃之後、而無需保留資料。

此程序適用於IOM12和IOM12B磁碟機櫃。


NOTE: IOM12B模組僅在SANtricity 不含作業系統11.70.2的版本上受支援。在安裝或升級至IOM12B之前、請先確認控制器的韌體已更新。

.開始之前
由於此程序的複雜性、因此需要下列項目：

* 您必須有「功能產品差異要求」（FPVR）。若要歸檔FPVR、請聯絡NetApp專業服務部門。
+

NOTE: 在嘗試此程序之前、若未取得FPVR、可能會導致磁碟機故障和控制器鎖定。

* 如果您能夠備份資料、則無需NetApp專業服務協助、即可執行此程序。
* 如果您無法備份資料、請聯絡NetApp專業服務部門以取得此程序的協助。
* 請確定您的兩個陣列都已準備好執行下列程序：
+
** *現有陣列*：現有陣列SANtricity 搭載支援的不支援作業系統8.25或更新版本。
** *新陣列*：新陣列已解壓縮並關機。


* 記錄您要轉換成磁碟機櫃的SAS-2控制器機櫃序號。




== 步驟1：關閉控制器電源（非資料保留）

所有作業都必須先關機、才能關閉控制器電源。

.步驟
. 如果仍可存取現有的SAS-2陣列、請刪除所有磁碟區群組、關閉兩個控制器的電源、並移除所有纜線。
. 記錄您要轉換成磁碟機櫃的SAS-2控制器機櫃序號。
. 如果現有陣列使用磁碟機安全功能、請確定安全金鑰可用。




== 步驟2：安裝控制器（非資料保留）

成功關機後、您可以更換陣列中的控制器。

.步驟
. 將現有陣列中的兩個控制器更換為IOM或ESM。
. 如果可能、請使用現有陣列的主機纜線和網路纜線、並將其連接至新陣列中的控制器。
+

NOTE: 視新陣列的主機連線而定、可能需要不同的纜線。

. 將磁碟機櫃連接至新陣列中的控制器後方。
+
現有的控制器磁碟機匣和任何附加的磁碟機匣都會變成磁碟機櫃、並可透過纜線連接至新陣列中的控制器。

+

NOTE: 將SAS-2連接至SAS-3需要SAS HD連接至Mini SAS纜線。如需特定控制器和擴充櫃組態的詳細纜線連接資訊、請參閱 link:../install-hw-cabling/index.html["纜線"] 或 https://library.netapp.com/ecm/ecm_download_file/ECMLP2588749["E系列硬體佈線指南"^]。





== 步驟3：開啟控制器電源（非資料保留）

安裝完成後、開啟控制器電源、並將您的組態變更提交給NetApp技術支援部門。

.步驟
. 開啟新陣列的電源、包括任何連接的磁碟機櫃。
. 安裝以設定管理連接埠和IP位址 https://mysupport.netapp.com/tools/info/ECMLP2563821I.html["快速連線SANtricity"^] 公用程式：
. 如果現有陣列上使用磁碟機安全功能、請匯入安全金鑰。
. 如果您在執行此程序之前、無法從現有陣列刪除磁碟區群組、則必須將所有外部磁碟機設定為原生磁碟機。如需如何將磁碟機設定為原生的詳細資訊、請參閱SANtricity 《關於線上說明》。
. 將您的組態變更傳送至NetApp技術支援部門。
+
.. 取得您在步驟2中記錄的舊控制器磁碟機匣序號。
.. 登入 http://mysupport.netapp.com/eservice/assistant["NetApp 支援網站"^]。
.. 從*意見反應類別*下的下拉式清單中、選取*安裝的產品>取消配置要求*。
.. 選取*建立案例*。在* Comments（註釋）*文字方塊中輸入下列文字、將控制器磁碟機匣的序號取代為序號：
+
「請取消委任此序號、因為授權已移至系統中的另一個序號。請參閱SN附註

.. 選擇*提交*。




完成的SAS-2至SAS-3組態變更將提交給NetApp技術支援部門。
