---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: 如果您要升級E2800和E5700控制器、而且已啟用「磁碟機安全性」功能、則必須手動解除鎖定磁碟機。 
---
= 解除磁碟機鎖定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您要升級E2800和E5700控制器、這些控制器的磁碟機安全功能將會部分鎖定磁碟機、外部或內部磁碟機。如果已啟用「磁碟機安全性」功能、您必須手動解除鎖定這些磁碟機。

請遵循下列適當程序：

*  key management
*  key management




== 內部金鑰管理

當所有磁碟機都鎖定時、請遵循下列步驟進行內部金鑰管理。

新換用的控制器將鎖定七段顯示代碼* L5*。當沒有磁碟機可以執行自動程式碼同步（ACS）時、就會發生此鎖定。匯入安全金鑰後、ACS會繼續並更新新的控制器。


NOTE: 如果您不使用管理連接埠1、請嘗試使用其他預設IP位址：+ Ctrl a連接埠1：192．168．128．101 + Ctrl a連接埠2：192．168．128．102 + Ctrl B連接埠1：192．192．168．129．101 + Ctrl B連接埠2：192．168．129．102

.步驟
. 在儲存陣列與SANtricity 該用戶端的筆記型電腦或PC之間建立直接的私有乙太網路連線。若要這麼做：
+
.. 使用RJ45乙太網路纜線將筆記型電腦連接至控制器A的管理連接埠1
.. 若要完成連線、您可能需要將筆記型電腦指派給與控制器A相同子網路的IP位址控制器鎖定期間、控制器A預設為管理位址192．168．128.101。因此您可以將筆記型電腦指派至子網路、例如「192．168．128．201」。


. 使用IP位址192.168.1.128.101加上使用者名稱* admin*和密碼空白、使用匯入內部金鑰 `import storageArray securityKey file` CLI命令、並儲存安全金鑰 link:prepare-upgrade-controllers-task.html["準備升級控制器"]。如需使用此命令的相關資訊、請參閱 https://docs.netapp.com/us-en/e-series-cli/index.html["命令列介面參考"]。
+
*範例：*「Mcli 192．168．128.101 -u admin－c「Import storageArray securityKey file=\"Directory & Filene\" phraser=\"passPhraserString\""；」

+
或者、您也可以透過REST API透過下列呼叫匯入內部金鑰： `/storage-systems/{system-id}/security-key/import`



控制器將繼續執行磁碟機的自動程式碼同步程序、然後重新開機。重新開機後、控制器將可透過原始IP組態存取。



== 外部金鑰管理

當所有磁碟機都鎖定時、請遵循下列外部金鑰管理步驟。

新換用的控制器將鎖定七段顯示代碼* L5*。當沒有磁碟機可以執行自動程式碼同步（ACS）時、就會發生此鎖定。匯入安全金鑰後、ACS會繼續並更新新的控制器。


NOTE: 您的儲存陣列必須處於最佳狀態、才能擷取用戶端和伺服器憑證。如果無法擷取憑證、則必須建立新的憑證簽署要求（CSR）、然後從外部金鑰管理伺服器匯入伺服器憑證。

.步驟
. 在儲存陣列與SANtricity 該用戶端的筆記型電腦或PC之間建立直接的私有乙太網路連線。若要這麼做：
+
.. 使用RJ45乙太網路纜線將筆記型電腦連接至控制器A的管理連接埠1
.. 若要完成連線、您可能需要將筆記型電腦指派給與控制器A相同子網路的IP位址控制器鎖定期間、控制器A預設為管理位址192．168．128.101。因此您可以將筆記型電腦指派至子網路、例如「192．168．128．201」。


. 使用預設IP位址192．168．128．101、使用者名稱* admin *和密碼空白、使用設定外部金鑰管理伺服器 `set storageArray externalKeyManagement` CLI命令並提供 `serverAddress` 和 `serverPort` 儲存自 link:prepare-upgrade-controllers-task.html["準備升級控制器"]。如需使用此命令的相關資訊、請參閱 https://docs.netapp.com/us-en/e-series-cli/index.html["命令列介面參考"]。
+
*範例：*「Mcli 192.168.1.128.101 -u admin -c "set storageArray externalKeyManagement serverAddress=<ServerIPAddress> serverPort=<serverPort>;」

+
或者、您也可以透過REST API透過下列呼叫來設定外部金鑰管理伺服器： `/storage-systems/{system-id}/external-key-server`

. 使用預設IP位址192．168．128.101、使用者名稱* admin *、密碼保留空白、然後使用匯入憑證 `storageArray keyManagementCertificate` CLI命令：一次用於用戶端憑證、第二次用於伺服器憑證。
+
*範例A：*「Mcli 192．168．128.101－u admin－c「downloadstorageArray keyManagement Certificate certicateType =用戶端檔案=「Directory & FileName」；」

+
*範例B：*「Mcli 192．168．128.101－u admin－c「downloadstorageArray keyManagement Certificate certicateType = server file=\「Directory & FileName」（下載storageArray keyManagement憑證類型=伺服器檔案=）；」

+
或者、您也可以透過REST API透過下列呼叫匯入Keyserver憑證： `/storage-systems/{system-id}/external-key-server/certificate`

. 使用儲存自的安全金鑰 link:prepare-upgrade-controllers-task.html["準備升級控制器"]下，將外部金鑰匯入IP位址192．168．128.101、使用者名稱* admin *、密碼保留空白。
+
*範例：*「Mcli 192．168．128.101 -u admin－c「Import storageArray securityKey file=\"Directory & Filene\" phraser=\"passPhraserString\""；」

+
或者、您也可以透過REST API透過下列呼叫匯入外部金鑰： `/storage-systems/{system-id}/security-key/import`



控制器將繼續執行磁碟機的自動程式碼同步程序、然後重新開機。重新開機後、控制器將可透過原始IP組態存取。
