---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: 如果您要升級E2800和E5700控制器、而且已啟用「磁碟機安全性」功能、則必須手動解除鎖定磁碟機。 
---
= 解除鎖定 E 系列磁碟機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
這些控制器的磁碟機安全功能會部分，外部或內部鎖定磁碟機。如果已啟用「磁碟機安全性」功能、您必須手動解除鎖定這些磁碟機。

請遵循下列適當程序：

* <<內部金鑰管理>>
* <<外部金鑰管理>>




== 內部金鑰管理

當所有磁碟機都鎖定時、請遵循下列步驟進行內部金鑰管理。

.關於這項工作
新換用的控制器將鎖定七段顯示代碼* L5*。當沒有磁碟機可以執行自動程式碼同步（ACS）時、就會發生此鎖定。匯入安全金鑰後、ACS會繼續並更新新的控制器。


NOTE: 如果您不使用管理連接埠 1 ，請嘗試使用其他預設 IP 位址： + Ctrl A 連接埠 1 ： 169.254.128.101 + Ctrl A 連接埠 2 ： 169.254.128.102 + Ctrl B 連接埠 1 ： 169.254.128.101 + Ctrl B 連接埠 2 ： 169.254.128.102

.步驟
. 在儲存陣列與SANtricity 該用戶端的筆記型電腦或PC之間建立直接的私有乙太網路連線。若要這麼做：
+
.. 使用RJ45乙太網路纜線將筆記型電腦連接至控制器A的管理連接埠1
.. 若要完成連線，您可能需要將筆記型電腦指派給控制器 A 所在的同一子網路中的 IP 位址。在控制器鎖定期間，控制器 A 預設為管理位址 169.254.128.101 。因此您可以將筆記型電腦指派給子網路，例如「 169.254.128.201 」。


. 使用 IP 位址 169.254.128.101 （使用者名稱 * admin* 且密碼為空白），使用 CLI 命令匯入內部金鑰，並將安全金鑰 `import storageArray securityKey file`儲存在中link:prepare-upgrade-controllers-task.html["準備升級控制器"]。如需使用此命令的相關資訊，請參閱 https://docs.netapp.com/us-en/e-series-cli/index.html["命令列介面參考"]。
+
* 範例： * `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
或者、您也可以透過REST API透過下列呼叫匯入內部金鑰： `/storage-systems/{system-id}/security-key/import`



控制器將繼續執行磁碟機的自動程式碼同步程序、然後重新開機。重新開機後、控制器將可透過原始IP組態存取。



== 外部金鑰管理

當所有磁碟機都鎖定時、請遵循下列外部金鑰管理步驟。

.關於這項工作
新換用的控制器將鎖定七段顯示代碼* L5*。當沒有磁碟機可以執行自動程式碼同步（ACS）時、就會發生此鎖定。匯入安全金鑰後、ACS會繼續並更新新的控制器。

.步驟
. 在儲存陣列與SANtricity 該用戶端的筆記型電腦或PC之間建立直接的私有乙太網路連線。若要這麼做：
+
.. 使用RJ45乙太網路纜線將筆記型電腦連接至控制器A的管理連接埠1
.. 若要完成連線，您可能需要將筆記型電腦指派給控制器 A 所在的同一子網路中的 IP 位址。在控制器鎖定期間，控制器 A 預設為管理位址 169.254.128.101 。因此您可以將筆記型電腦指派給子網路，例如「 169.254.128.201 」。


. 使用從儲存的安全金鑰link:prepare-upgrade-controllers-task.html["準備升級控制器"]，將外部金鑰匯入 IP 位址 169.254.128.101 ，使用者名稱 * admin* ，密碼保持空白。
+
* 範例： * `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
或者、您也可以透過REST API透過下列呼叫匯入外部金鑰： `/storage-systems/{system-id}/security-key/import`

+
控制器將繼續執行磁碟機的自動程式碼同步程序、然後重新開機。重新開機後、控制器將可透過原始IP組態存取。

. （可選）如果需要，可通過執行以下步驟重新鍵入驅動器：
+
* 範例： * `SMcli <original_controller _ip> -u admin -p "<original_array_password>" -c "create storageArray securityKey" passPhrase=\"passPhraseString\" file=\"filename\";”`


