---
permalink: remote-storage-volumes/import-remote-storage-task.html 
sidebar: sidebar 
keywords: import Remote Storage Volumes, RTV import, import remote volumes, remote storage E-Series 
summary: 遠端儲存設備的匯入作業是透過SANtricity 「物件系統管理程式」下的「匯入遠端儲存」精靈執行。遠端儲存匯入功能可將遠端儲存設備的資料移至本機E系列陣列。 
---
= 匯入 SANtricity 遠端儲存磁碟區的遠端儲存設備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要從遠端系統將儲存設備匯入本機E系列儲存系統、請使用SANtricity 「支援系統管理程式」使用者介面中的「匯入遠端儲存」精靈。

.您需要的一切
* E系列儲存系統必須設定為與遠端儲存系統通訊。請參閱 link:setup-remote-volumes-concept.html["設定硬體"]。
* 對於遠端儲存系統、請收集下列資訊：
+
** iSCSI IQN
** iSCSI IP位址
** 遠端儲存設備（來源Volume）的LUN編號


* 對於本機E系列儲存系統、請建立或選取要用於資料匯入的磁碟區。目標Volume必須符合下列需求：
+
** 符合遠端儲存設備（來源Volume）的區塊大小。
** 容量等於或大於遠端儲存設備。
** 狀態為Optimal（最佳）且可供使用。如需完整的需求清單、請參閱 link:system-reqs-concept.html["要求與限制"]。


* 建議：在開始匯入程序之前、先備份遠端儲存系統上的磁碟區。


.關於這項工作
在此工作中、您可以在遠端儲存設備和本機E系列儲存系統上的磁碟區之間建立對應。完成組態之後、就會開始匯入。


NOTE: 由於許多變數會影響匯入作業及其完成時間、因此您應該先執行較小的「測試」匯入。使用這些測試可確保所有連線都能正常運作、並確保匯入作業在適當的時間內完成。

.步驟
. 在「系統管理程式」SANtricity 中、按一下「*儲存設備>遠端儲存設備*」。
. 按一下*匯入遠端儲存設備*。
+
隨即顯示匯入遠端儲存設備的精靈。

. 在「設定來源」面板的步驟1a中、輸入連線資訊。
+
.. 在*名稱*欄位下、輸入遠端儲存設備的名稱。
.. 在* iSCSI連線內容*下、針對遠端儲存設備輸入下列項目：IQN、IP位址和連接埠號碼（預設為3260）。
+
如果您要新增另一個iSCSI連線、請按一下「*+新增其他IP位址*」、以納入遠端儲存設備的其他IP位址。完成後、按一下*下一步*。

+
按一下「下一步」後、將顯示「設定來源」面板的步驟1b。



. 在「* LUN*」欄位下、選取遠端儲存設備所需的來源LUN、然後按一下「*下一步*」。
+
「設定目標」面板隨即開啟、並顯示要做為匯入目標的Volume候選項目。由於區塊大小、容量或磁碟區可用度的關係、部分磁碟區不會顯示在候選清單中。

. 從表中選取E系列儲存系統上的目標Volume。如有需要、請使用滑桿變更匯入優先順序。單擊 * 下一步 * 。在下一個對話方塊中輸入「Continue」（繼續）、然後按一下「* Continue *（繼續*）」以確認作業。
+
如果目標磁碟區的容量大於來源磁碟區、則不會向連接至E系列系統的主機報告額外容量。若要使用新容量、您必須在匯入作業完成並中斷連線之後、在主機上執行檔案系統擴充作業。

+
在對話方塊中確認組態之後、將會顯示「檢閱」面板。

. 從「Review（檢閱）」畫面、確認指定的遠端儲存設備、目標和匯入設定正確無誤。按一下「*完成*」以完成遠端儲存設備的建立。
+
另一個對話方塊隨即開啟、詢問您是否要啟動另一個匯入。

. 如有需要、請按一下* Yes（是）*以建立另一個遠端儲存匯入。按一下「是」返回「組態來源」面板的步驟1a、您可以在其中選取現有組態或新增組態。如果您不想建立其他匯入項目、請按一下「*否*」結束對話方塊。
+
匯入程序開始後、整個目標磁碟區會被複製的資料覆寫。如果主機在此程序期間將任何新資料寫入目標磁碟區、則新資料會傳回遠端裝置（來源磁碟區）。

. 在「遠端儲存」面板下的「檢視作業」對話方塊中、檢視作業進度。
+
完成匯入作業所需的時間取決於遠端儲存系統的大小、匯入的優先順序設定、以及儲存系統及其相關磁碟區的I/O負載量。匯入完成後、本機磁碟區即為遠端儲存設備的複本。

. 當您準備好中斷兩個磁碟區之間的關係時、請從「作業進行中」檢視中選取匯入物件上的*中斷連線*。一旦關係中斷連線、本機磁碟區的效能就會恢復正常、不再受到遠端連線的影響。

