---
permalink: remote-storage-volumes/system-reqs-concept.html 
sidebar: sidebar 
keywords: Remote Storage Volumes requirements, RTV requirements, RTV restrictions, remote volumes, remote storage E-Series 
summary: 您的系統必須符合遠端儲存磁碟區的相容要求。 
---
= 使用 SANtricity 遠端儲存磁碟區的要求與限制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在設定遠端儲存磁碟區功能之前、請先檢閱下列需求和限制。



== 硬體需求



=== 支援的傳輸協定

對於遠端儲存磁碟區功能的初始版本、只有iSCSI和IPV4傳輸協定才提供支援。

請參閱 http://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"^] 以取得用於遠端儲存磁碟區功能的主機與E系列（目的地）陣列之間的最新支援與組態資訊。



=== 儲存系統需求

E系列儲存系統必須包括：

* 兩個控制器（雙工模式）
* 兩個E系列控制器的iSCSI連線、可透過一或多個iSCSI連線與遠端儲存系統通訊
* 作業系統11.71或更新版本SANtricity
* 子機型ID（SMID）中啟用的遠端儲存功能


遠端系統可以是E系列儲存系統、也可以是其他廠商的系統。它必須包含iSCSI介面。



== Volume需求

用於匯入的磁碟區必須符合大小、狀態及其他條件的要求。



=== 遠端儲存Volume

匯入的來源Volume稱為「遠端儲存Volume」。 此Volume必須符合下列條件：

* 無法成為另一個匯入的一部分
* 必須具有線上狀態


匯入開始後、控制器韌體會在背景中建立遠端儲存磁碟區。由於背景程序、遠端儲存磁碟區在System Manager中無法管理、只能用於匯入作業。

建立後、遠端儲存Volume會與E系列系統上的任何其他標準Volume一樣處理、但下列例外情況除外：

* 可作為遠端儲存設備的Proxy。
* 無法做為其他Volume複本或快照的候選對象。
* 匯入進行中時、無法變更「資料保證」設定。
* 無法對應至任何主機、因為這些主機是專為匯入作業保留的。


每個遠端儲存磁碟區只會與一個遠端儲存物件相關聯、但是一個遠端儲存物件可以與多個遠端儲存磁碟區相關聯。遠端儲存磁碟區使用下列組合加以唯一識別：

* 遠端儲存物件識別碼
* 遠端儲存設備LUN編號




=== 目標Volume候選對象

目標Volume是本機E系列系統上的目的地Volume。

目的地Volume必須符合下列條件：

* 必須是RAID/DDP Volume。
* 容量必須等於或大於遠端儲存Volume。
* 區塊大小必須與遠端儲存磁碟區相同。
* 必須具有有效狀態（最佳）。
* 無法建立下列任何關係：磁碟區複本、快照複本、非同步或同步鏡射。
* 無法進行任何重新設定作業：動態Volume擴充、動態容量擴充、動態區段大小、動態RAID移轉、動態容量減量、 或重組。
* 無法在匯入開始之前將其對應至主機（不過、匯入開始後即可將其對應）。
* 無法啟用Flash讀取快取（FRC）。


System Manager會在匯入遠端儲存精靈中自動檢查這些需求。只有符合所有需求的磁碟區才會顯示以供選擇目的地磁碟區。



== 限制

遠端儲存功能有下列限制：

* 鏡射必須停用。
* E系列系統上的目的地Volume不得有快照。
* 在開始匯入之前、不得將E系列系統上的目的地Volume對應至任何主機。
* E系列系統上的目的地Volume必須停用資源資源配置。
* 不支援將遠端儲存磁碟區直接對應至主機或多個主機。
* 不支援Web服務Proxy。
* 不支援iSCSI CHAP機密。
* 不支援SMcli。
* 不支援VMware資料存放區。
* 當存在匯入配對時、一次只能升級關係/匯入配對中的一個儲存系統。




== 準備正式作業匯入

您應該在正式作業匯入之前執行測試或「演習」匯入、以驗證適當的儲存和網路組態。

許多變數可能會影響匯入作業和完成時間。為了確保正式作業匯入成功並取得持續時間預估、您可以使用這些測試匯入來確保所有連線都能正常運作、而且匯入作業會在適當的時間內完成。然後您可以在正式作業匯入開始之前、進行調整以達成所需的結果。
