---
permalink: install-hw-ef50-ef80/install-prepare.html 
sidebar: sidebar 
keywords:  
summary: 準備安裝您的 EF50 或 EF80 儲存系統，請先準備好場地、了解儲存系統的吊掛注意事項、打開包裝箱並將內容物與裝箱單進行比較，以及註冊儲存系統以存取支援服務。 
---
= 準備安裝 - EF50 和 EF80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
準備安裝您的 EF50 或 EF80 儲存系統，請先準備好場地、了解儲存系統的吊掛注意事項、打開包裝箱並將內容物與裝箱單進行比較，以及註冊儲存系統以存取支援服務。



== 步驟 1 ：準備站台

請確保場地和您計劃使用的機櫃或機架符合您儲存系統的規格。

.步驟
. 使用 https://hwu.netapp.com["NetApp Hardware Universe"^]確認您的站台是否符合儲存系統的環境和電力需求。
. 請確保您的儲存系統和任何交換器有足夠的機櫃或機架空間。
+
如有需要，請參閱 https://hwu.netapp.com["NetApp Hardware Universe"^]以了解儲存系統的確切尺寸。

+
** 2U 儲存系統
** 大多數交換器為 1U


. 安裝所有必要的網路交換器。
. 請確保您的瀏覽器支援管理軟體：
+
** Google Chrome （第 89 版及更新版本）
** Microsoft Edge （ 90 版及更新版本）
** Mozilla Firefox （ 80 版及更新版本）
** Safari （版本 14 及更新版本）


. 請準備以下安裝所需的設備和工具：
+
** 靜電放電（ESD）腕帶
** Philips #2 螺絲起子
** 手電筒






== 步驟 2：了解搬運注意事項

在拆箱之前，以及之後安裝儲存系統時，您應該了解儲存系統的重量，以便在提起和移動時採取必要的預防措施。

EF50 或 EF80 儲存系統的重量可達 61.5 磅（27.9 公斤）。搬運儲存系統時，需兩人或使用液壓升降機。

image::../media/drw_g_lifting_weight_ieops-1831.svg[AFF A20 A30 A50 、 C30 和 C60 重量警告圖示]



== 步驟 3 ：拆箱

在確認場地和計劃使用的櫃子或機架符合儲存系統的規格，並了解搬運注意事項後，請打開所有箱子，並將內容物與裝箱單上的物品進行比較。

.步驟
. 小心地打開所有箱子，並將裡面的物品有條不紊地擺放好。
. 將您拆開的包裝內容與裝箱單核對。
+
您可以透過掃描運輸箱側面的 QR 碼來取得裝箱單。

+

NOTE: 如有任何出入，請記錄下來以便採取進一步行動。

+
以下項目是您可能會在盒子中看到的部分內容。

+
如有需要，請查看 https://hwu.netapp.com/["NetApp Hardware Universe"^]其他支援的線纜並確定其用途。

+
[cols="9,9,5"]
|===


| *硬體* | *纜線* |  


 a| 
** 具有磁碟機的儲存系統
** 交換器
** 機架安裝硬體及說明
** 邊框

 a| 
** 控制器間鏡像乙太網路纜線
** 管理乙太網路纜線（RJ-45 纜線）
** 網路纜線
** 電源線

|  
|===




== 步驟 4：註冊您的儲存系統

在您確認您的站台符合儲存系統的規格，並且您已確認所有訂購的零件都已到位後，您應該註冊您的儲存系統。

. 建立帳戶並在註冊硬體 http://mysupport.netapp.com/["NetApp支援"^]。
+
註冊過程需要每個控制器的序號（SN）。您可以在以下位置找到序號：

+
** 在每個控制器上
** 在裝箱單上
** 在您的確認電子郵件中
+
image::../media/drw_ef50-ef80_sn_label_ieops-2689.svg[序號標籤範例]





.接下來呢？
準備好安裝儲存系統後，link:install-hardware.html["安裝硬體"]。
