---
permalink: upgrade-santricity/overview-upgrade-consider-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: 檢閱儲存陣列SANtricity 的更新考量事項、瞭解如何使用作業系統的更新軟體和韌體、以及其磁碟機韌體。 
---
= 升級考量
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要確保升級成功、請檢閱下列升級考量事項。



== 控制器升級（單一或多個）

在升級控制器之前、請先檢閱這些重要考量事項。



=== 目前版本

您可以檢視軟體和韌體的目前版本、如下所示：

* 對於單一控制器、請使用SANtricity 「系統管理程式」介面。移至功能表：Support[升級中心]、然後按一下*軟體與韌體庫存*的連結。
* 若為多個控制器、請使用SANtricity 「支援統一化管理程式」介面。請前往*管理*頁面、尋找探索到的儲存陣列。版本顯示於* SANtricity 《OS Software*》（*《作業系統軟體*》）欄。當您按一SANtricity 下每列的「還原OS版本」時、控制器韌體和NVSRAM資訊 會出現在快顯對話方塊中。




=== 升級所含的元件

下列元件包含在SANtricity 整個作業系統升級程序中：

* *系統管理程式*-系統管理程式是管理儲存陣列的軟體。
* *控制器韌體*-控制器韌體可管理主機與磁碟區之間的I/O。
* * IOM韌體*- I/O模組（IOM）韌體可管理控制器與磁碟機櫃之間的連線。它也會監控元件的狀態。
* *監控軟體*-監控軟體是軟體執行所在控制器上的虛擬機器。




=== 元件需個別升級

下列元件必須個別升級：

* *控制器NVSRAM*-控制器NVSRAM-是控制器檔案、可指定控制器的預設設定。有關升級NVSRAM的 說明、請參閱升級控制器的說明。
* *磁碟機韌體*-請參閱 link:upgrade-drive-firmware-task.html["升級磁碟機韌體"] 以取得個別指示。
* *多重路徑/容錯移轉驅動程式*-在升級程序中、主機的多重路徑/容錯移轉驅動程式可能也需要升級、以便主機能夠正確地與控制器互動。如果執行Microsoft Windows以外作業系統的主機與您的儲存系統有I/O連線、請升級這些主機的多重路徑驅動程式。如需相容性資訊、請參閱 https://mysupport.netapp.com/NOW/products/interoperability["NetApp 互通性對照表"^]。如需升級指示、請參閱 link:../config-linux/index.html["Linux Express組態"]、 link:../config-windows/index.html["Windows Express組態"]或 link:../config-vmware/index.html["VMware Express組態"]。
* *《統一化管理程式》*—Unified Manager軟體可管理多個儲存系統、包括E2800、E5700、EF300和EF600機型。SANtricityUnified Manager是SANtricity 《支援Web服務的Proxy》的一部分、這是一部獨立安裝在主機系統上的RESTful API伺服器、可管理數百個全新和舊版NetApp E系列儲存系統。如需詳細資訊、請參閱 link:../web-services-proxy/index.html["Web服務代理概述SANtricity"]。
* * Utilities *（公用程式）-其他管理公用程式需要個別的升級、例如SANtricity ：Windows主機公用程式、SANtricity Linux主機公用程式、SANtricity 以及Windows DSM。如需這些公用程式的詳細資訊、請參閱 link:../config-linux/index.html["Linux Express組態"]、 link:../config-windows/index.html["Windows Express組態"]或 link:../config-vmware/index.html["VMware Express組態"]。
* *舊版系統*-如果您的儲存系統屬於包含舊版儲存系統的儲存網路、您可能需要使用舊SANtricity 版的《不支援儲存管理程式企業管理》（EMW）、才能提供所有儲存系統的企業檢視。在此案例中、請查看SANtricity 是否有更新版本的《支援》更新版本的《支援》。




=== 雙控制器與I/O處理

如果儲存陣列包含兩個控制器、而且您已安裝多重路徑驅動程式、則儲存陣列可在升級時繼續處理I/O。在升級期間、會發生下列程序：

. 控制器A將其所有LUN容錯移轉至控制器B
. 在控制器A上進行升級
. 控制器A會恢復其LUN及控制器B的所有LUN。
. 在控制器B上進行升級


升級完成後、您可能需要在控制器之間手動重新分配磁碟區、以確保磁碟區回到正確的擁有控制器。



=== 健全狀況檢查

健全狀況檢查會在升級程序中執行。這項健全狀況檢查會評估所有儲存陣列元件、以確保升級能夠繼續進行。下列情況可能會導致升級無法進行：

* 指派的磁碟機故障
* 使用中的熱備援磁碟機
* 不完整的Volume群組
* 執行專屬作業
* 遺失磁碟區
* 控制器處於非最佳狀態
* 事件記錄事件過多
* 組態資料庫驗證失敗
* 使用舊版的DACStore磁碟機


您也可以單獨執行升級前的狀況檢查、而不需進行升級。



=== 立即或分段升級

您可以立即啟動升級、或稍後再進行登入。您可以選擇稍後啟動、原因如下：

* *每天的時間*-啟動軟體可能需要很長時間、因此您可能需要等待I/O負載變輕。控制器升級通常需要15到25分鐘才能完成、視I/O負載和快取大小而定。控制器會在啟動期間重新開機並容錯移轉、因此在升級完成之前、效能可能會比平常低。
* *套件類型*：在升級其他儲存陣列上的檔案之前、您可能需要在一個儲存陣列上測試新的軟體和韌體。




== 磁碟機韌體升級

在升級磁碟機韌體之前、請先檢閱這些重要考量事項。



=== 磁碟機相容性

每個磁碟機韌體檔案都包含執行韌體的磁碟機類型相關資訊。您只能將指定的韌體檔案下載至相容的磁碟機。系統管理員會在升級過程中自動檢查相容性。



=== 磁碟機升級方法

磁碟機韌體升級方法有兩種：線上和離線。

|===
| 線上升級 | 離線升級 


 a| 
在線上升級期間、磁碟機會依序升級、一次升級一個。儲存陣列會在升級時繼續處理I/O。您不需要停止I/O如果磁碟機可以進行線上升級、則會自動使用線上方法。

可進行線上升級的磁碟機包括：

* 最佳集區中的磁碟機
* 最佳備援磁碟區群組中的磁碟機（RAID 1、RAID 5和RAID 6）
* 未指派的磁碟機
* 備用熱備援磁碟機


執行線上磁碟機韌體升級可能需要數小時的時間、使儲存陣列面臨潛在的磁碟區故障。在下列情況下、可能會發生磁碟區故障：

* 在RAID 1或RAID 5磁碟區群組中、有一個磁碟機在升級磁碟區群組中的另一個磁碟機時故障。
* 在RAID 6集區或磁碟區群組中、有兩個磁碟機在升級集區或磁碟區群組中的不同磁碟機時故障。

 a| 
在離線升級期間、同一磁碟機類型的所有磁碟機都會同時升級。此方法需要停止與所選磁碟機相關聯之磁碟區的I/O活動。由於可同時升級多個磁碟機（平行）、因此整體停機時間大幅縮短。如果磁碟機只能執行離線升級、則會自動使用離線方法。

下列磁碟機必須使用離線方法：

* 非備援磁碟區群組中的磁碟機（RAID 0）
* 非最佳集區或磁碟區群組中的磁碟機
* SSD快取中的磁碟機


|===