---
permalink: upgrade-santricity/upgrade-multiple-controller-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: 使用「支援支援統一化管理程式」、在同類型的多個儲存陣列上升級支援不支援的作業系統軟體。SANtricity SANtricity 
---
= 升級多個控制器的軟體與韌體
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用SANtricity 《Sings統一 化管理程式》來升級同類型的多個控制器。

.開始之前
* 檢閱 link:overview-upgrade-consider-task.html["升級考量"]。
* 判斷您要立即或更新版本啟動軟體升級。您可以選擇稍後啟動、原因如下：
+
** *每天的時間*-啟動軟體可能需要很長時間、因此您可能需要等待I/O負載變輕。控制器會在啟動期間容錯移轉、因此在升級完成之前、效能可能會比平常低。
** *套件類型*：在升級其他儲存陣列上的檔案之前、您可能會想要在一個儲存陣列上測試新的作業系統軟體。


* 請檢閱下列預防措施：



CAUTION: 資料遺失或有損壞儲存陣列的風險-升級期間請勿變更儲存陣列。維持儲存陣列的電力。


CAUTION: 如果您要在SANtricity 某個不支援的應用裝置上升級支援功能（StorageGRID 例如SG5612或SG5760）、您必須先將應用裝置置於維護模式、然後再繼續執行此程序、否則資料可能會遺失。如需詳細步驟、請參閱StorageGRID 您的應用程式的安裝與維護說明。



== 步驟1：執行升級前狀態檢查

健全狀況檢查會在升級程序中執行、但您也可以在開始之前分別執行健全狀況檢查。健全狀況檢查會評估儲存陣列的元件、以確保升級能夠繼續進行。

.步驟
. 開啟Unified Manager。
. 從主檢視畫面選取*管理*、然後選取功能表：升級中心[升級前狀況檢查]。
+
「預先升級健全狀況檢查」對話方塊隨即開啟、並列出所有探索到的儲存系統。

. 如有需要、請篩選或排序清單中的儲存系統、以便檢視目前未處於最佳狀態的所有系統。
. 選取要執行健全狀況檢查之儲存系統的核取方塊。
. 按一下* Start*。
+
執行健全狀況檢查時、進度會顯示在對話方塊中。

. 健全狀況檢查完成後、您可以按一下每列右側的省略符號（...）、以檢視更多資訊並執行其他工作。
+

NOTE: 如果有任何陣列未通過健全狀況檢查、您可以跳過該特定陣列並繼續升級其他陣列、或是停止整個程序、並疑難排解未通過的陣列。





== 步驟2：從支援網站下載軟體檔案

在此步驟中、您可前往NetApp支援網站、將新的可下載套件（DLP）軟體檔案儲存至管理主機系統。

.步驟
. 如果您的儲存陣列只包含一個控制器、或是未使用多重路徑驅動程式、請停止儲存陣列的I/O活動、以避免應用程式錯誤。如果您的儲存陣列有兩個控制器、而且安裝了多重路徑驅動程式、則不需要停止I/O活動。
. 從Unified Manager的主視圖中、選取*管理*、然後選取您要升級的一或多個儲存陣列。
. 選擇功能表：Upgrade Center[升級SANtricity 版作業系統軟體]。
+
此時會出現「Upgrade SANtricity VMware OS軟體」頁面。

. 從SANtricity NetApp支援網站下載最新的支援作業系統軟體套件至您的本機電腦。
+
.. 按一下*「新增檔案至軟體儲存庫」*。
.. 按一下連結以尋找最新的* SANtricity 《支援作業系統下載*》。
.. 按一下*下載最新版本*連結。
.. 請依照其餘指示、將SANtricity 作業系統的支援檔案和NVSRAM/檔案下載到您的本機機器。


+

NOTE: 8.42版及更新版本需要數位簽署的韌體。如果您嘗試下載未簽署的韌體、將會顯示錯誤、且下載會中止。





== 步驟3：將軟體檔案傳輸至控制器

您可以將SANtricity SKETOS軟體檔案和NVSRAM/檔案載入儲存庫、以便Unified Manager Upgrade Center存取。


CAUTION: 資料遺失或有損壞儲存陣列的風險-升級期間請勿變更儲存陣列。維持儲存陣列的電力。

.步驟
. 從Unified Manager的主視圖中、選取*管理*、然後選取您要升級的一或多個儲存陣列。
. 選擇功能表：Upgrade Center[升級SANtricity 版作業系統軟體]。
+
此時會出現「Upgrade SANtricity VMware OS軟體」頁面。

. 從SANtricity NetApp支援網站下載最新的支援作業系統軟體套件至您的本機電腦。
+
.. 按一下*「新增檔案至軟體儲存庫」*。
.. 按一下連結以尋找最新的* SANtricity 《支援作業系統下載*》。
.. 按一下*下載最新版本*連結。
.. 請依照其餘指示、將SANtricity 作業系統的支援檔案和NVSRAM/檔案下載到您的本機機器。


+

NOTE: 8.42版及更新版本需要數位簽署的韌體。如果您嘗試下載未簽署的韌體、將會顯示錯誤、且下載會中止。

. 選取您要用來升級控制器的OS軟體檔案和NVSRAM..
+
.. 從* Select a SANtricity Se OS software file*下拉式清單中、選取您下載到本機電腦的OS檔案。
+
如果有多個檔案可用、檔案會從最新日期排序至最舊日期。

+

NOTE: 軟體儲存庫會列出與Web服務Proxy相關的所有軟體檔案。如果您沒有看到要使用的檔案、可以按一下「*新增檔案至軟體儲存庫*」連結、瀏覽至您要新增的OS檔案所在的位置。

.. 從*選取一個NVSRAM*下拉式清單中、選取您要使用的控制器檔案。
+
如果有多個檔案、檔案會從最新日期排序至最舊日期。



. 在「相容儲存陣列」表中、檢閱與您所選OS軟體檔案相容的儲存陣列、然後選取您要升級的陣列。
+
** 您在「管理」檢視中選取且與所選韌體檔案相容的儲存陣列、預設會在「相容的儲存陣列」表格中選取。
** 無法以所選韌體檔案更新的儲存陣列無法在相容的儲存陣列表中選取、狀態*不相容*會顯示此資訊。


. （可選）要將軟件文件傳輸到儲存陣列而不進行激活，請選中*將操作系統軟件傳輸到儲存陣列、將其標記爲分段並在稍後時間激活*複選框。
. 按一下* Start*。
. 視您選擇現在或之後啟動而定、請執行下列其中一項：
+
** 鍵入* transfit*以確認您要在您選擇要升級的陣列上傳輸建議的作業系統軟體版本、然後按一下* Transfing*。
+
若要啟動傳輸的軟體、請選取功能表：Upgrade Center[啟動分段作業系統軟體]。

** 鍵入*升級*以確認您要傳輸並啟動所選陣列上建議的作業系統軟體版本、然後按一下*升級*。
+
系統會將軟體檔案傳輸至您選擇要升級的每個儲存陣列、然後啟動重新開機以啟動該檔案。



+
升級作業期間會執行下列動作：

+
** 升級前的狀況檢查會在升級程序中執行。升級前的健全狀況檢查會評估所有儲存陣列元件、以確保升級能夠繼續進行。
** 如果儲存陣列的任何健全狀況檢查失敗、升級就會停止。您可以按一下省略符號（...）、然後選取*「Save Log*」（儲存記錄*）以檢閱錯誤。您也可以選擇置換健全狀況檢查錯誤、然後按一下*繼續*繼續升級。
** 您可以在升級前狀況檢查之後取消升級作業。


. （可選）升級完成後、您可以按一下省略符號（...）、然後選取*「Save Log*」（儲存記錄*）、查看特定儲存陣列的升級項目清單。
+
此檔案會以名稱'升級_log-<date>.json'儲存在瀏覽器的「下載」資料夾中。





== 步驟4：啟動階段式軟體檔案（選用）

您可以選擇立即啟動軟體檔案、或等到更方便的時間再啟動。此程序假設您選擇稍後啟動軟體檔案。


NOTE: 啟動程序之後、您無法停止啟動程序。

.步驟
. 從Unified Manager的主視圖中、選取*管理*。如有必要、請按一下「Status（狀態）」欄、將狀態為「OS Upgrade（waiting activation）（OS升級（等待啟動））」的所有儲存陣列排序。
. 選取您要啟動軟體的一或多個儲存陣列、然後選取功能表：升級中心[啟動分段作業系統軟體]。
+
升級作業期間會執行下列動作：

+
** 升級前的狀況檢查會在啟動程序中執行。預先升級的健全狀況檢查會評估所有儲存陣列元件、以確保啟動作業能夠繼續進行。
** 如果儲存陣列的任何健全狀況檢查失敗、啟動就會停止。您可以按一下省略符號（...）、然後選取*「Save Log*」（儲存記錄*）以檢閱錯誤。您也可以選擇置換健全狀況檢查錯誤、然後按一下*繼續*繼續啟動。
** 您可以在升級前狀況檢查之後取消啟動作業。成功完成升級前的健全狀況檢查後、就會啟動。啟動所需的時間取決於儲存陣列組態和您要啟動的元件。


. （可選）完成激活後，您可以通過單擊省略號（...），然後選擇* Save Log*（保存日誌*）來查看特定儲存陣列的已激活內容列表。
+
檔案會儲存在瀏覽器的「Downloads（下載）」資料夾中、名稱為「actaction_log-<date>.json」。



.接下來呢？
您的控制器軟體升級已完成。您可以恢復正常作業。
