---
permalink: upgrade-santricity/upgrade-single-controller-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: 升級單一E系列控制器的軟體與韌體。 
---
= 升級單一控制器的軟體與韌體
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升級單一控制器、確保您擁有所有最新的功能與修正程式。

此程序涉及升級儲存陣列軟體、以及選擇性的IOM韌體和非揮發性靜態隨機存取記憶體（NVSRAM）。

.開始之前
* 檢閱 link:overview-upgrade-consider-task.html["升級考量"]。
* 確定您是否要在作業系統韌體的同時升級控制器的NVSRAM檔。
+
一般而言、您應該同時升級所有元件。不過、如果您的檔案已修補或是自訂版本、而且您不想覆寫、您可能會決定不升級控制器的NVSRAM/檔案。

* 確定是否要升級IOM韌體。
+
一般而言、您應該同時升級所有元件。不過、如果您不想將IOM韌體升級為SANtricity 更新版的一部分、或是技術支援部門指示您降級IOM韌體（您只能使用命令列介面降級韌體）、則可能會決定不升級IOM韌體。

* 決定您現在或之後是否要啟動作業系統升級。
+
日後啟用的理由可能包括：

+
** *每天的時間*–啟動軟體和韌體可能需要很長的時間、因此您可能需要等待I/O負載變輕。控制器會在啟動期間容錯移轉、因此在升級完成之前、效能可能會比平常低。
** *套件類型*：您可能需要先在一個儲存陣列上測試新的軟體和韌體、然後再升級其他儲存陣列上的檔案。






== 步驟1：從支援網站下載軟體檔案

在此步驟中、您可前往NetApp支援網站、將新的可下載套件（DLP）軟體檔案儲存至管理主機系統。

升級所需的時間取決於您的儲存陣列組態和要升級的元件。

.步驟
. 如果您的儲存陣列只包含一個控制器、或您沒有安裝多重路徑驅動程式、請停止儲存陣列的I/O活動、以避免應用程式錯誤。如果您的儲存陣列有兩個控制器、而且安裝了多重路徑驅動程式、則不需要停止I/O活動。
+

CAUTION: 如果您要在SANtricity 某個不支援的應用裝置上升級支援功能（StorageGRID 例如SG5612或SG5760）、您必須先將應用裝置置於維護模式、然後再繼續執行此程序、否則資料可能會遺失。如需詳細步驟、請參閱StorageGRID 您的應用程式的安裝與維護說明。

. 從System Manager介面中、選取功能表：Support（支援）[Upgrade Center]（升級中心）。
. 在標有SANtricity 「RES針對OS軟體升級」的區域中、按一下「* NetApp SANtricity 支援OS Downloads *」以開啟NetApp支援網站。
. 從「Downloads（下載）」頁面中、選取* E系列SANtricity 《Se OS Controller Software*》。
+

NOTE: 8.42版及更新版本需要數位簽署的韌體。如果您嘗試下載未簽署的韌體、將會顯示錯誤、且下載會中止。

. 依照螢幕上的指示、為您的控制器機型下載最新的作業系統軟體。如果您也想要升級NVSRAM/、請下載單一控制器的NVSRAM.檔案。




== 步驟2：將軟體檔案傳輸至控制器

在此步驟中、您會將軟體檔案傳輸至控制器、以便開始升級程序。這些元件會從管理用戶端複製到控制器、並放在Flash記憶體的暫存區域中。


CAUTION: *資料遺失的風險或儲存陣列受損的風險*-升級期間請勿變更儲存陣列。維持儲存陣列的電力。

.步驟
. （選用）。如果您打算在特定維護期間執行升級、您可能需要執行升級前健全狀況檢查、以事先判斷是否有任何重大的儲存陣列問題。如果是這種情況、請在System Manager的Upgrade Center（升級中心）中選取* pre-Upgrade healsection*（功能表：Support[升級中心]）、然後依照任何螢幕上的指示進行。否則、您可以跳過此步驟、因為健全狀況檢查是升級程序的一部分。
. 如果您目前不想升級IOM韌體、請按一下*暫停IOM自動同步*、然後依照對話方塊中的指示進行。
+
如果您有單一控制器的儲存陣列、則不會升級IOM韌體。

. 在System Manager的Upgrade Center中、按一下* BEGIN Upgrade（*開始升級）* from "VMware SANtricity OS Software Upgrade"（從「VMware OS軟體升級」升級）。
+
此時會出現「Upgrade SANtricity VMware OS軟體」對話方塊。

. 選取一或多個檔案以開始升級程序：
+
.. 按一下*瀏覽*並SANtricity 瀏覽至從Support網站下載的OS軟體檔案、以選取「支援OS軟體」檔案。
.. 單擊*瀏覽*並瀏覽至從Support（支持）站點下載的NVSRAM/文件，以選擇Controller NVSRAM/文件。控制器的NVSRAM,檔案名稱類似於「N2800-830000-000.dlp」。


+
這些動作會發生：

+
** 根據預設、只會顯示與目前儲存陣列組態相容的檔案。
** 當您選取要升級的檔案時、會顯示檔案名稱和大小。


. （選用）如果您選擇SANtricity 要升級的支援功能作業系統軟體檔案、您可以選擇*立即傳輸檔案、但不要升級（稍後啟動升級）*核取方塊、將檔案傳輸至控制器、而不啟動檔案。
. 按一下* Start*（開始*）、然後確認您要執行此作業。
+
您可以在升級前的狀況檢查期間取消作業、但在傳輸或啟動期間無法取消。

. （可選）要查看已升級內容的列表，請單擊*保存日誌*。
+
檔案會儲存在瀏覽器的「Downloads（下載）」資料夾中、名稱為「drive_升級_log-timestamp.txt"。



如果您已經啟動軟體檔案、請前往  4: Complete software and firmware upgrade；否則、請前往  3: Activate software files。



== 步驟3：啟動軟體檔案

只有在軟體或韌體已傳輸但尚未啟動時、才需遵循此步驟。若要檢查此狀態、請在System Manager首頁的「通知」區域或「升級中心」頁面中尋找通知。

當您執行啟動作業時、目前的軟體和韌體會被新的軟體和韌體取代。啟動程序之後、您無法停止啟動程序。

.步驟
. 從System Manager介面中、選取功能表：Support（支援）[Upgrade Center]（升級中心）。
. 在標示SANtricity 為「RESIT OS Software Upgrade」的區域中、按一下「* Activate*」、然後確認您要執行此作業。
. （可選）要查看已升級內容的列表，請單擊*保存日誌*。
+
檔案會儲存在瀏覽器的「Downloads（下載）」資料夾中、名稱為「drive_升級_log-timestamp.txt"。





== 步驟4：完成軟體與韌體升級

在「軟體與韌體詳細目錄」對話方塊中驗證版本、以完成軟體與韌體升級。

.開始之前
* 您必須已啟動軟體或韌體。


.步驟
. 從系統管理員中、確認所有元件都顯示在「硬體」頁面上。
. 核取「軟體與韌體庫存」對話方塊（前往功能表：「Support[升級中心]」、然後按一下「*軟體與韌體庫存*」連結）、以驗證新的軟體與韌體版本。
. 如果您升級控制器的NVSRAM,則在啟動程序期間會遺失任何已套用至現有的NVSRAM/R的自訂設定。啟動程序完成後、您需要再次將自訂設定套用至NVSRAM.
. 如果在升級程序期間發生下列任何錯誤、請採取適當的建議行動。
+
|===
| 如果您遇到此韌體下載錯誤... | 然後執行下列動作... 


 a| 
指派的磁碟機故障
 a| 
故障的原因之一可能是磁碟機沒有適當的簽名。確定受影響的磁碟機是授權的磁碟機。如需詳細資訊、請聯絡技術支援部門。

更換磁碟機時、請確定更換磁碟機的容量等於或大於您要更換的故障磁碟機。

您可以在儲存陣列接收I/O時更換故障磁碟機



 a| 
檢查儲存陣列
 a| 
** 確定已將IP位址指派給每個控制器。
** 確保連接至控制器的所有纜線均未損壞。
** 確定所有纜線都已緊密連接。




 a| 
整合式熱備援磁碟機
 a| 
您必須先修正此錯誤狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
不完整的Volume群組
 a| 
如果一個或多個Volume群組或磁碟集區不完整、您必須先修正此錯誤狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
目前在任何Volume群組上執行的排他性作業（背景媒體/同位元檢查除外）
 a| 
如果正在進行一或多個專屬作業、則必須先完成作業、才能升級韌體。使用System Manager來監控作業進度。



 a| 
遺失磁碟區
 a| 
您必須先修正遺失的磁碟區狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
任一控制器處於非最佳狀態
 a| 
其中一個儲存陣列控制器需要注意。必須先修正此狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
控制器物件圖表之間的儲存分割資訊不相符
 a| 
驗證控制器上的資料時發生錯誤。請聯絡技術支援部門以解決此問題。



 a| 
SPM驗證資料庫控制器檢查失敗
 a| 
控制器上發生儲存分割區對應資料庫錯誤。請聯絡技術支援部門以解決此問題。



 a| 
組態資料庫驗證（如果儲存陣列的控制器版本支援）
 a| 
控制器上發生組態資料庫錯誤。請聯絡技術支援部門以解決此問題。



 a| 
MEL相關檢查
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內報告了超過10個「DDE資訊」或「重大MEL」事件
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內報告超過2頁2C重大MEL事件
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內報告超過2個降級的磁碟機通道嚴重MEL事件
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內有4個以上的重要MEL項目
 a| 
請聯絡技術支援部門以解決此問題。

|===


您的控制器軟體升級已完成。您可以恢復正常作業。
