---
permalink: web-services-proxy/array-intro-concept.html 
sidebar: sidebar 
keywords: Web Services, WSP, SANtricity API, discover storage WSP, 
summary: 若要管理網路中的儲存系統、您必須先探索儲存系統、然後將其新增至管理清單。 
---
= 使用 SANtricity Web 服務 Proxy 管理儲存系統
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要管理網路中的儲存系統、您必須先探索儲存系統、然後將其新增至管理清單。



== 探索儲存系統

您可以設定自動探索或手動探索儲存系統。



=== 自動探索儲存系統

您可以修改wsconfig.xml檔案中的設定、指定在網路中自動探索儲存系統。根據預設、IPv6自動探索會停用、並啟用IPv4。

您只需提供一個管理IP或DNS位址、即可新增儲存系統。當路徑尚未設定或路徑已設定且可旋轉時、伺服器會自動探索所有管理路徑。


NOTE: 如果您嘗試在初始連線之後、使用IPv6傳輸協定從控制器組態自動探索儲存系統、則此程序可能會失敗。可能導致故障的原因包括：在儲存系統上啟用IP位址轉送或IPv6時發生問題、但伺服器上卻未啟用IPv6。

.開始之前
啟用IPv6探索設定之前、請先確認您的基礎架構支援IPv6連線至儲存系統、以減輕任何連線問題。

.步驟
. 開啟wsconfig.xml檔案、網址為：
+
** （Windows）- C：\Program Files\NetApp\SANtricity Web Services Proxy
** （Linux）-/opt/netapp/SANtricity _web_services代理


. 在自動探索字串中、視需要將設定從「true」變更為「假」。請參閱下列範例。
+
[listing]
----
<env key="autodiscover.ipv6.enable">true</env>
----
+

NOTE: 當路徑設定完成、但未設定為伺服器可以路由傳送到位址時、會發生間歇性的連線錯誤。如果無法將IP位址設定為可從主機路由傳送、請關閉自動探索（將設定變更為「假」）。

. 儲存檔案。




=== 使用API端點探索及新增儲存系統

您可以使用API端點來探索儲存系統、並將其新增至受管理清單。此程序會在儲存系統與API之間建立管理連線。


NOTE: 本工作說明如何使用REST API探索及新增儲存系統、以便您在互動式API文件中管理這些系統。不過、您可能想要改用Unified Manager來管理儲存系統、因為Unified Manager提供簡單易用的介面。如需詳細資訊、請參閱Unified Manager提供的線上說明。

.開始之前
若儲存系統SANtricity 使用的是11、30版及更新版本、則必須在SANtricity 「系統管理程式」介面中啟用符號的舊版管理介面。否則、探索端點就會失敗。您可以開啟System Manager來尋找此設定、然後前往功能表：設定[系統>其他設定>變更管理介面]。

.步驟
. 登入 link:install-login-task.html["互動式API文件"]。
. 探索儲存系統、如下所示：
+
.. 從API文件中、確定下拉式清單中選取* V2*、然後展開* Storage-Systems*類別。
.. 按一下「* POST：/dredle*」端點、然後按一下「*試試看*」。
.. 輸入表格中所述的參數。
+
|===


 a| 
startIP

endIP
 a| 
將字串取代為網路中一或多個儲存系統的起始和結束IP位址範圍。



 a| 
使用代理程式
 a| 
將此值設為：

*** 是=使用頻內代理程式進行網路掃描。
*** 否=請勿使用頻內代理程式進行網路掃描。




 a| 
ConnectionTimeDOut
 a| 
輸入連線逾時之前允許掃描的秒數。



 a| 
最大連接埠使用
 a| 
輸入用於網路掃描的連接埠數量上限。

|===
.. 按一下*執行*。
+

NOTE: API動作會在使用者未提示的情況下執行。

+
探索程序會在背景執行。

.. 請確定程式碼傳回202。
.. 在「*回應本文*」下、找到要求ID傳回的值。您需要申請ID、才能在下個步驟中檢視結果。


. 檢視探索結果、如下所示：
+
.. 按一下「* Get：/dredle*」端點、然後按一下「* Try it Out *（*試用*）」。
.. 輸入上一個步驟的要求ID。如果您將*要求ID*保留空白、端點預設為上次執行的要求ID。
.. 按一下*執行*。
.. 請確定程式碼傳回200。
.. 在回應本文中、找出您的Request ID和storageSystems字串。字串看起來類似下列範例：
+
[listing]
----
"storageSystems": [
    {
      "serialNumber": "123456789",
      "wwn": "000A011000AF0000000000001A0C000E",
      "label": "EF570_Array",
      "firmware": "08.41.10.01",
      "nvsram": "N5700-841834-001",
      "ipAddresses": [
        "10.xxx.xx.213",
        "10.xxx.xx.214"
      ],
----
.. 記下WWN、標籤和IP地址的值。您需要這些資源來執行下一步。


. 新增儲存系統、如下所示：
+
.. 按一下* POST：/STA-system*端點、然後按一下*試用*。
.. 輸入表格中所述的參數。
+
|===


 a| 
ID
 a| 
輸入此儲存系統的唯一名稱。您可以輸入標籤（顯示於Get:/Discovery的回應中）、但名稱可以是您選擇的任何字串。如果您未提供此欄位的值、Web Services會自動指派唯一的識別碼。



 a| 
控制器地址
 a| 
輸入回應中顯示的IP位址：Get/Discovery。對於雙控制器、請以逗號分隔IP位址。例如：

「IP位址1」、「IP位址2」



 a| 
驗證
 a| 
輸入「true」、您就能收到Web Services可連線至儲存系統的確認訊息。



 a| 
密碼
 a| 
輸入儲存系統的管理密碼。



 a| 
WWN
 a| 
輸入儲存系統的WWN（顯示在Get:/Discovery的回應中）。

|===
.. 刪除"enableTrace"之後的所有字串：true（真）、使整個字串集類似於下列範例：
+
[listing]
----
{
  "id": "EF570_Array",
  "controllerAddresses": [
    "Controller-A-Mgmt-IP","Controller-B-Mgmt_IP"
  ],
  "validate":true,
  "password": "array-admin-password",
  "wwn": "000A011000AF0000000000001A0C000E",
  "enableTrace": true
}
----
.. 按一下*執行*。
.. 請確定程式碼回應為201、表示端點已成功執行。
+
「*貼文：/storage系統*」端點已排入佇列。您可以在下一步中使用* Get:/media-Systems*端點來檢視結果。



. 確認新增清單、如下所示：
+
.. 按一下* Get:/media-system*端點。
+
不需要任何參數。

.. 按一下*執行*。
.. 請確定程式碼回應為200、表示端點已成功執行。
.. 在回應本文中、尋找儲存系統詳細資料。傳回的值表示已成功新增至託管陣列清單、類似下列範例：
+
[listing]
----
[
  {
    "id": "EF570_Array",
    "name": "EF570_Array",
    "wwn": "000A011000AF0000000000001A0C000E",
    "passwordStatus": "valid",
    "passwordSet": true,
    "status": "optimal",
    "ip1": "10.xxx.xx.213",
    "ip2": "10.xxx.xx.214",
    "managementPaths": [
      "10.xxx.xx.213",
      "10.xxx.xx.214"
  ]
  }
]
----






== 擴充託管儲存系統的數量

根據預設、API最多可管理100個儲存系統。如果您需要管理更多資源、則必須滿足伺服器的記憶體需求。

伺服器設為使用512 MB記憶體。對於網路中每100個額外的儲存系統、請將250 MB新增至該數目。請勿增加比實際擁有的記憶體更多的記憶體。為您的作業系統和其他應用程式提供足夠的額外資源。


NOTE: 預設的快取大小為8、192個事件。MEL事件快取的大約資料使用量為每8、192個事件的1MB。因此、保留預設值後、儲存系統的快取使用量應約為1MB。


NOTE: 除了記憶體、Proxy也會針對每個儲存系統使用網路連接埠。Linux和Windows將網路連接埠視為檔案處理。作爲一項安全措施、大多數作業系統都會限制處理程序或使用者一次可以開啟的檔案處理數量。尤其是在Linux環境中、開放式TCP連線被視為檔案處理、Web服務Proxy很容易超過此限制。由於此修正程式是系統相依的、因此您應該參閱作業系統的文件、以瞭解如何提高此值。

.步驟
. 執行下列其中一項：
+
** 在Windows上、前往appserver64.init檔案。找到「vmarg.3=-Xmx512M」這一行
** 在Linux上、前往webserver.sh檔案。找到行「Java_options="-Xmx512M"」


. 若要增加記憶體容量、請將「512」換成所需的記憶體（以MB為單位）。
. 儲存檔案。

