---
permalink: web-services-proxy/polling-intro-concept.html 
sidebar: sidebar 
keywords: polling Web Services Proxy, WSP statistics, poll WSP, 
summary: 您可以針對探索到的儲存系統上的所有磁碟和磁碟區統計資料、設定自動輪詢。 
---
= 管理 SANtricity Web 服務 Proxy 統計資料的自動輪詢
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以針對探索到的儲存系統上的所有磁碟和磁碟區統計資料、設定自動輪詢。



== 統計資料總覽

統計資料提供有關資料收集率和儲存系統效能的資訊。

Web服務Proxy可存取下列類型的統計資料：

* 原始統計資料-資料收集時資料點的總計計數器。原始統計資料可用於總讀取作業或總寫入作業。
* 分析統計資料-間隔的計算資訊。分析統計資料的範例包括每秒讀取輸入/輸出作業（IOPs）或寫入處理量。


原始統計資料是線性的、通常需要至少兩個收集的資料點、才能從中衍生可用的資料。分析的統計資料是原始統計資料的推導、提供重要的指標。許多可從原始統計資料衍生的值、都會以可用的時間點格式顯示在分析統計資料中、以方便您使用。

無論是否啟用自動輪詢、您都可以擷取原始統計資料。您可以將「useclace=true」查詢字串新增至URL的結尾、以從上次輪詢擷取快取的統計資料。使用快取的結果可大幅提升統計資料擷取的效能。不過、多個呼叫的速率等於或小於設定的輪詢時間間隔快取、則會擷取相同的資料。



== 統計功能

Web服務Proxy提供API端點、可從支援的硬體模型和軟體版本擷取原始和分析的控制器及介面統計資料。



=== 原始統計資料API

* 「+」/「儲存系統」/「｛system-id｝/控制器統計資料+」
* 「+/儲存系統/｛system-id｝/磁碟機統計資料/｛選擇性磁碟ID清單｝+」
* 「+」/「儲存系統」/｛system-id｝/「介面統計資料」/「｛可選介面ID清單｝+」
* 「+/儲存系統/｛system-id｝/ Volume統計資料/｛Optional list of volume ID｝+」




=== 分析統計資料API

* 「+/儲存系統/｛id｝/分析控制器統計資料/+」
* 「+/儲存系統/｛id｝/分析磁碟機統計資料/｛選擇性磁碟ID清單｝+」
* 「+/儲存系統/｛id｝/分析介面統計資料/｛可選介面ID清單｝+」
* 「+/儲存系統/｛id｝/分析磁碟區統計資料/｛可選磁碟區ID清單｝+」


這些URL會從上次輪詢擷取分析的統計資料、而且只有在啟用輪詢時才可使用。這些URL包括下列輸入輸出資料：

* 每秒作業數
* 處理量（以每秒MB為單位）
* 回應時間（毫秒）


這些計算是根據統計輪詢迭代之間的差異而進行、這是儲存效能最常見的測量方法。這些統計資料優於未分析的統計資料。


NOTE: 系統啟動時、先前沒有統計資料集合可用來計算各種度量、因此分析的統計資料在啟動後至少需要一個輪詢週期才能傳回資料。此外、如果重設累積計數器、則下一個輪詢週期的資料數目將無法預測。



== 設定輪詢時間間隔

若要設定輪詢時間間隔、請修改wsconfig.xml檔案、以指定輪詢時間間隔（秒）。


NOTE: 由於統計資料會快取到記憶體中、因此每個儲存系統的記憶體使用量可能會增加約1.5 MB。

.開始之前
* 儲存系統必須由Proxy探索。


.步驟
. 開啟wsconfig.xml檔案、網址為：
+
** （Windows）- C：\Program Files\NetApp\SANtricity Web Services Proxy
** （Linux）-/opt/netapp/SANtricity _web_services代理


. 在「<env-entries >」標記中新增下列行、其中「n」是輪詢要求之間的間隔秒數：
+
[listing]
----
<env key="stats.poll.interval">n</env>
----
+
例如、如果輸入60、輪詢會以60秒的時間間隔開始。也就是系統會要求輪詢在前一個輪詢期間完成後60秒開始（無論前一個輪詢期間的持續時間為何）。所有統計資料都會以擷取的確切時間加上時間戳記。系統會使用時間戳記或時間差異、以60秒計算為基礎。

. 儲存檔案。

